import pesquisa from '../../assets/pesquisageo.jpg';
function GeoBr(){
    return(
        <>
        <p>No Brasil, os primeiros registros científicos acerca da temática do Geoturismo datam do início da década de 2000. O Brasil, pela sua dimensão, dificulta uma inventariação uniforme de potenciais sítios para uso geoturístico, mesmo que boa parte deles possua um intenso fluxo turístico devido às características da geodiversidade, em especial suas espetaculares formas de relevo, como os famosos pães de açúcar, que ocorrem na cidade do Rio de Janeiro, as cataratas do Iguaçu (PR), as falésias das belas praias nordestinas e os cânions dos Aparados da Serra (RS), entre outros.</p>

        <p>Destacam-se como atividades importantes para a disseminação dessa temática no Brasil, as ações da SIGEP e da CPRM; encontros científicos; revistas/periódicos de Geociências ou Turismo; dissertações de mestrado e teses de doutoramento; websites exclusivos sobre geoturismo, entre outras (NASCIMENTO, 2008). Não existe, no entanto, eventos ou revistas exclusivas sobre essa temática, diferentemente de outras regiões do globo, especialmente da Europa.</p>
          
        <p>Um dos trabalhos pioneiros de divulgação da geodiversidade para fins geoturísticos, mesmo que indiretamente, foi o Projeto ‘Caminhos Geológicos’ do Rio de Janeiro, criado em 2001 sob os auspícios do DRM/RJ. Essa difusão se dá por meio de 81 painéis informativos instalados em geossítios distribuídos em 23 municípios, compostos por textos e ilustrações que retratam a evolução geológica do local amostrado[1].</p>
          
        <p>O primeiro projeto estadual voltado diretamente para a integração das Ciências da Terra ao turismo foi denominado ‘Sítios geológicos e paleontológicos do Paraná’, desenvolvido pela MINEROPAR e já citado anteriormente. De maneira semelhante à dos ‘Caminhos Geológicos’, consiste na instalação de painéis em locais estratégicos do Estado, assim como na promoção de roteiros geoturísticos, com o apoio de órgãos públicos e privados (PIEKARZ e LICCARDO, 2006).</p>
          
        <p>Em dezembro de 2004, com a criação do grupo denominado ‘Patrimônio-Geológico’, no Yahoo Groups pelo geólogo Marcos Nascimento e colaboradores, as discussões acerca do tema, assim como a articulação de um movimento de inserção de uma sessão temática no próximo congresso, de maneira sistematizada e amadurecida, fez com que o geoturismo tomasse forma no país. Nesse grupo são disponibilizadas publicações e links sobre os 5G’s (NASCIMENTO et al., 2008), contando, em novembro de 2017, com 393 participantes de nacionalidades diversas.</p>
          
        <p>A introdução do tema ‘geoturismo’ em eventos científicos nacionais completou cerca de 15 anos. Data de 2004, no XLI Congresso Brasileiro de Geologia, em Araxá (MG), quando a temática foi introduzida pela primeira vez ainda numa perspectiva de atividade de ‘Turismo’, apesar de associada ao ‘Desenvolvimento Sustentável e Geologia’, portanto de maneira irrisória e sem a devida articulação. Outro evento científico importante pra a difusão da temática do geoturismo no Brasil foi o Simpósio Brasileiro do Patrimônio Geológico, introduzido em 2011 e realizado de dois em dois anos, conforme já referido no subcapítulo 2.2.2.</p>
          
        <p>Em fevereiro de 2007, foi lançado o site “#geoturismobrasil.com”, pelo geólogo e fotógrafo paranaense Antônio Liccardo, servindo como uma ferramenta para disseminação de trabalhos, ideias e discussões acerca desse e de outros temas, como geodiversidade, geopatrimônio e geoconservação, além de propiciar ao público leigo conhecimentos sobre o assunto e de permitir o acesso a um acervo de belíssimas fotografias que retratam a geodiversidade brasileira. O fato de possuir uma versão em inglês faz com que o site seja visitado por estudiosos da área do mundo inteiro (NASCIMENTO et al., 2008).</p>
          
        <p>Na área científica da Geografia, o geoturismo é uma discussão ainda incipiente. Para se ter uma ideia, apenas no XVI Simpósio Brasileiro de Geografia Física Aplicada, realizado em Teresina (PI), em 2015, foi introduzido um eixo temático sobre o tema, o ET09 - “Geoconservação, Geoturismo, Patrimônio Geomorfológico e Impactos Ambientais”, onde, dos 50 resumos expandidos publicados, apenas dez tratavam especificamente sobre geoturismo (dois em geoparques e oito em áreas não associadas a geoparques), o que mostra a pouca participação dos geógrafos nessa temática.</p>
          
        <p>Quanto à publicação de monografias, mestrados e teses, o trabalho pioneiro foi produzido por Barreto, em 2007, acerca da proposta de um roteiro geoturístico na Chapada Diamantina, pertencente ao “Circuito Nacional da Estrada Real” (BARRETO, 2007 apud RUCHKYS et al., 2017). Data de 2008 a publicação da primeira tese de doutoramento acerca da temática do geoturismo, defendida pela aluna da Universidade Federal de Santa Catarina (UFSC), Jasmine Moreira, com o título “Patrimônio Geológico em Unidades de Conservação: unidades interpretativas, educativas e geoturísticas” (MOREIRA, 2008), premiada com o ‘Prêmio CAPES de teses’, em 2011. A mesma autora publicou, nesse ano, o primeiro livro exclusivo sobre o tema, intitulado “Geoturismo e interpretação ambiental’, enfatizando a importância da atividade geoturística para a geoconservação e como uma ferramenta para a disseminação das Geociências a partir da educação ambiental (MOREIRA, 2011).</p>
          
        <p>A partir dessas publicações, vários trabalhos de graduação, dissertações de mestrado e teses de doutorado sobre o tema foram defendidos, a exemplo de Carvalho (2010), Santos (2014), Pinto (2015), entre outros. Ainda assim, quando comparado às discussões acerca da geodiversidade, geopatrimônio ou geoconservação, esse tema ainda é incipiente no país.</p>
          
        <p>Em 2011, foi criado o Núcleo de Apoio à Pesquisa em Patrimônio Geológico e Geoturismo (Geohereditas), por parte do corpo docente da Escola de Artes, Ciências e Humanidades e do Instituto de Biociências da Universidade de São Paulo (USP), além do Instituto Geológico da Universidade Federal do Rio de Janeiro (UFRJ) e da Universidade Complutense de Madrid. O núcleo tem por objetivo fomentar e promover atividades de pesquisa, de debate e de extensão nas áreas de Geoturismo, Geoconservação e Educação Ambiental em diversas unidades da USP, instituições associadas e outros setores da sociedade, por meio da pesquisa geológica básica, da divulgação científica do conhecimento geológico e ambiental e do apoio à inserção profissional da população por meio de atividades ligadas ao patrimônio geológico[2].</p>
          
        <p>De modo particular, a temática do geoturismo costeiro, no Brasil, é incipiente, restrita basicamente a pesquisadores de Pernambuco e de São Paulo, com publicações, principalmente, em anais de eventos científicos (GUIMARÃES et al., 2014; CANDEIAS et al., 2014; MOTA et al., 2014; GUIMARÃES et al., 2015). Destaca-se a Dissertação de Mestrado de Thaís Guimarães (GUIMARÃES, 2013), que faz referência a uma proposta de inserção de práticas geoturísticas em um parque metropolitano costeiro nas proximidades de Recife, visando a geoconservação e o Projeto “Roteiro Geoturístico Litoral Norte de São Paulo”, sob responsabilidade do Geohereditas, da USP.</p>
          
          <p>Por sua vez, o primeiro trabalho acerca de geoturismo urbano executado no Brasil, mesmo que indiretamente, envolveu estudos acerca de geologia urbana e foi publicado em 2001 como um relatório de conclusão de curso de Graduação em Geologia, na USP. Nesse trabalho, Stern (2001) traçou um roteiro geológico por vários prédios do Centro Histórico de São Paulo, identificando e descrevendo as litologias a eles pertencentes.</p>
          
          <p>A partir de então, existem várias propostas de estudo da geodiversidade em ambientes urbanos brasileiros, seja na forma de roteiros geológicos para fins de geoturismo urbano ou para conhecimento científico puro, ao se estudarem detalhes, como obras em cantaria ou patologias litológicas nas edificações[3]. Como exemplos, temos a cidade de Natal (DANTAS, 2001; CARVALHO, 2010); São Paulo (STERN et al., 2006; REYS et al., 2008; AUGUSTO e DEL LAMA, 2011; MACHADO e DEL LAMA, 2014; DEL LAMA et al., 2015); Belo Horizonte (FERNANDES et al., 2007); os municípios históricos do Ciclo do Ouro, em Minas Gerais (LICCARDO, 2007; PEREIRA et al., 2007c; COSTA, 2014); Porto Alegre (PHILLIPP e BENEDETTI, 2007; BENEDETTI et al., 2007; PHILLIPP et al., 2009); Salvador (SILVA, 2008; PINTO et al., 2012; PINTO, 2015); Região Metropolitana de Recife (RIECK e SOUZA, 2008); Curitiba (LICCARDO et al., 2008; LICCARDO, 2010); Pirenópolis (CONCEIÇÃO et al., 2009); Ouro Preto (MORAES et al., 2011; PAULA, 2013); Rio de Janeiro (MELLO et al., 2014); João Pessoa (PEREIRA e AMARAL, 2014; PEREIRA et al., 2015a; 2015b; 2016b; PEREIRA, 2017a), entre outros.</p>
          
          <p>Na Região Sudeste brasileira, por exemplo, o piso do Shopping Center Eldorado, em São Paulo, é revestido por um mármore com estromatólitos que datam de mais de dois bilhões de anos (LICCARDO et al., 2012), proveniente da formações geológicas da própria região, tendo sido divulgado à população apenas em 2006, mesmo sendo conhecido dos meios acadêmicos desde 1976 (SALLUN FILHO e FAIRCHILD, 2005; FAIRCHILD et al., 2006). Convém salientar que esse shopping, em 2008, recebeu a visita de 1,5 milhões de pessoas por mês, que trafegam sobre essas rochas ornamentais sem reconhecer sua importância científica. Para efeito de comparação, as Cataratas do Iguaçu, um importante monumento natural, considerado Patrimônio Mundial pela UNESCO, recebeu 1,15 milhões de habitantes em todo o ano de 2008 (LICCARDO et al., 2012). Esse é um claro exemplo do potencial que o meio urbano possui para o geoturismo.</p>
          
          <p>Uma outra atividade geoturística que pode ocorrer em ambientes urbanos ou rurais é o do geoturismo em peças ex situ, em museus, que podem estar instalados nas proximidades do geopatrimônio visitado ou em centros urbanos. Em qualquer que seja o caso, o papel do museu deve ser traçar um diálogo entre o objeto e o visitante, como um local educativo, cultural e turístico (MAGALHÃES-GOMES e AZEVEDO, 2003 apud NASCIMENTO et al., 2008). A maneira como o acervo será apresentado ao visitante é crucial para potencializar seu papel educativo e de entretenimento.</p>
          
          <p>O turismo cemiterial também é uma vertente muito particular do geoturismo urbano, em ascensão no país (KUZMICKAS e DEL LAMA, 2012, 2015; LICCARDO e GRASSI, 2014; RODRIGUES e DEL LAMA, 2014), cuja observação da estética e análise dos materiais pétreos utilizados nos túmulos fazem com que muitos turistas e estudiosos se desloquem para esse novo segmento geoturístico.</p>
          
          <p>Ruban (2015) enfatiza que o Brasil está entre os principais centros de pesquisa acerca do geoturismo no mundo. Analisando publicações em revistas e jornais, publicadas entre 2012 e 2014, o autor posiciona o Brasil em 2º lugar, com 59 publicações, atrás da Itália, com 61 publicações, seguido da China (52) e da Polônia (38). Esses dados comprovam que a comunidade científica brasileira adotou e apoia o tema, que tem abertamente crescido e se dinamizado nos meios acadêmicos e fora deles também.</p>
          
          Assim, baseado em Ruban (2015), propomos quatro estágios para a disseminação do tema “geoturismo” no Brasil, conforme a figura 4.2: <br />
          <a href={pesquisa}><img src={pesquisa} alt="" className="img-fluid mx-auto d-block" /></a>
          <p><b>Fig 4.2</b></p><br />
          i) até 2004, quando a temática era ainda incipiente e o número de publicações era reduzido, resultava em publicações praticamente inexistentes, restringindo-se a roteiros envolvendo geologia urbana, desenvolvimento da teoria, com ideias básicas ou a discussão acerca de propostas de geoparques, onde o geoturismo era uma atividade secundária; <br />ii) a partir da criação do Yahoo Groups “Patrimônio-Geológico” e do XLI Congresso Brasileiro de Geologia, em 2004, a disseminação do tema, mesmo que tímida, se espalha, mostrando o interesse que os pesquisadores possuem por ela;<br /> iii) entre 2007-2008, a temática se consolida no país, a partir da proposta do site #geoturismobrasil.com”, somado à publicação do livro ‘Geodiversidade, Geoconservação e Geoturismo’ (NASCIMENTO et al., 2008) e a tese de doutorado de Moreira, no mesmo ano;<br /> iv) a partir de 2008, incrementam as publicações sobre geoturismo, assim como diversificam-se os objetos e métodos estudados, com publicações nacionais e estrangeiras.
          
          <p>Conclui-se que ao se inserirem elementos da paisagem natural, em especial o patrimônio abiótico, assim como o patrimônio cultural à atividade turística, como resultado de um mercado mais exigente, acaba-se por proporcionar a ascensão de turismos de nicho, e o geoturismo se encaixa nesse contexto, como uma atividade integrada entre as Geociências, a cultura e a história do local em que estão inseridas.</p>
          
          <hr />
          [1] DEPARTAMENTO DE RECURSOS MINERAIS DO RIO DE JANEIRO-DRM/ RJ. Caminhos Geológicos. Disponível em http://www.drm.rj.gov.br/index.php/downloads/section/13-placas-caminhos-geologicos. Acesso em 09 novembro 2017.<br />
          
          [2] UNIVERSIDADE DE SÃO PAULO-USP. Núcleo de Apoio à Pesquisa. Geohereditas. Extraído de http://www.igc.usp.br/index.php?id=605. Acesso em 22 agosto 2015.<br />
          
         [3] No caso do estudo e caracterização das rochas que compõem igrejas, monastérios, etc., ascendeu, recentemente, um novo ramo da geologia urbana denominado ‘Geologia Eclesiástica’, cujos resultados podem ser inseridos em trilhas geoturísticas urbanas. Para um maior aprofundamento deste tema, sugere-se para leitura Sutherland (2000), Potter (2005) e Caetano et al. (2006), entre outros.
        </>
        
    )
}


export default GeoBr;