import aguadoce from '../media/aguadoce.png'



export function ENAguadoce(){
    return(
        <>
        <p class="paragraphy">The <b>fresh water sources</b> sprout throughout the project area, and some, especially those located in the Historic Center, were extremely important for their historical and economic content, as they supplied the population for centuries. from the nascent city of Nossa Senhora das Neves. The description of the quality and characteristics of water resources, including the fresh water sources of the Captaincy of Parahyba, dates back to the beginnings of the colonial period. Without drinking water, the establishment and evolution of an urban site was unfeasible and, in the case of João Pessoa, it was no different, as recorded in the historical documents.</p>
        <p class="paragraphy">Thus, some sources in particular stand out in these documents, as they are true hydrological heritage, configuring themselves in <b>hydrosites</b>, here classified as Places of Interest. Specific characteristics of these places will be prioritized, such as natural aspects, involving geology and geomorphology, historical information on their importance for urban evolution and lithological aspects of the building attached to the sources, if any, but which will be detailed in the inventory of these Places. In this case, we highlight the Fonte de Tambiá, Bica da Maria Feia, Cacimba do Povo, Santo Antônio and Fonte dos Milagres, all located in the center of João Pessoa. Other important main sources are Cacimba<sup>1</sup> from Jaqueira and Gravatá, analyzed below.</p>
        <p class="paragraphy">According to figure 1, which locates the sources in the Historic Center, it can be seen that all sources occupy marginal positions in relation to the city, on the slopes facing, mainly towards the Sanhauá River, having a direct relationship with the normal fault plane <sup>2</sup> which exposed the sandstones that serve as aquifers to the sources, as well as the limestones in contact underlying them, at altitudes ranging between 16 and 22 meters. Exceptions are the Fontes de Tambiá and Bica da Maria Feia, which are on the slope facing the River Tambiá Grande. As will be seen further on, time and human action have made a significant part of this cultural and hydrological heritage disappear.</p>
        <p class="paragraphy">The lithological characteristics of the <b>Barreiras Formation</b> (Plio-Pleistocene), together with the flat topography, favor the infiltration of water to the detriment of its flow. The subsequent concentration of solutions and colloids in the iluvial horizon favors the genesis of hardened levels and, therefore, impermeable, in the subsurface of the tableland soil, which is related to the genesis of the Barreiras sandization. This horizon of fragipan ends up retaining the water that infiltrates, forming a suspended aquifer, the Barreiras aquifer, which is also related to the drainage headwater areas of several basins (such as the Balustrada das Trincheiras), with some sources (such as the de Tambiá and Maria Feia), where the sandy levels intersect the slopes, as well as the Dolina dos Irerês. In the contact of the <b>Barreiras Formation</b> with the Maastrichtian limestone of the <b>Gramame Formation</b> a deeper level of the Barreiras Aquifer is formed, this time 'free', with the Cacimba do Povo and the Santo Antônio and Milagres springs outcrop at the intersection of these layers with the slope formed by the 'Falha de Sanhauá'.</p>
        <div class="text-center">
            <figure class="figure">
                <a href={aguadoce}><img src={aguadoce} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figure 1 - Location of the main sources and some streets and buildings in the city of Paraíba, in 1913. Legend: Symbols (streets): 1-Ladeira de São Francisco; 2-Mandacaru Road (current Desemb. Botto Meneses); 3-Road of Tambaú (currently Mons. Walfredo Leal); 4-Rua da Gameleira (current Des. Trindade); 5-Slope of Borborema; 6-Rua da Tesoura (now Rua Vidal de Negreiros); 7-Rua da Lagoa da Frente (current Rua 13 de Maio); 8-Rua da lagoon back (now Rua Nova da Lagoa); 9-Caminho da Cacimba do Povo (now Rua Rodrigues Chaves); 10-Rua das Trencheiras; 11-Rua da Palmeira (now Rua Rodrigues de Aquino). Blue circles (buildings): A-Igreja de Santo Antônio; B-Church Matrix; C-Church of São Bento; D-Igreja do Carmo; E-New Santa Casa Hospital under construction (current Santa Isabel Hospital); F-Police Headquarters; G-Holy House of Mercy; H-Igreja da Conceição; I-Church of Bom Jesus. Red triangles (fountains/cacimbas): a-Fonte dos Milagres; b-Source of Santo Antônio; c - Source of Tambiá; d-Bica of Maria Feia; e-Cacimba da Jaqueira; f-Source from Gravata; g-Cacimba do Povo. Source: SOUSA and VIDAL (2010) apud ARAÚJO (2012).</figurecaption>
            </figure>
        </div>
        <hr />
        <span>
            <sup>1</sup>Cacimba is a name given to bodies of water that emerge from the opening of shallow wells with the use of shovels or pickaxes.
            <sup>2</sup>According to Leinz and Amaral (2001), they can be classified as 'failure sources'
        </span>
        </>
    )
}