import introclima1 from '../media/introclima1.png';
import introclima2 from '../media/introclima2.png';



export function ENIntroduçãohidro(){
    return(
        <>
            <p class="paragraphy">Water, as an element of geodiversity and a geopatrimonial element, will be approached through two aspects: the <b>fluvial aspects</b> and the <b>fresh water sources</b>. Whenever possible, an attempt will be made to correlate these aspects with geomorphology, geology, tectonics and the environmental problems involved with anthropization, serving as a basis for, subsequently, analyzing them through a heritage vision, aiming to insert them in the geotouristic itinerary. Thus, the detailing of these features will be given in the case of those that were selected as Place of Interest, being present in the inventory of chapter 8.</p>
            <p class="paragraphy">Field trips were carried out between February and May 2016 on the coast of the study area, aiming at the <i>in situ</i> observation of phenomena related to geodiversity, as well as aerophotogrammetric and orbital image analysis and relatively bibliographical research. scarce for the subject in question, as well as the sources inserted in the Historic Center, with the subsequent objective of valuation for geopatrimonial purposes.</p>
            <p class="paragraphy">Organizing the area from the point of view of the hydrographic basins, according to the classification proposed by the National Department of Water and Electric Energy (DNAEE), the research area is fully inserted in the <b>Northeast Atlantic Hydrographic Basin</b> (IBIAPINA et al., 1999). Thinking at the state scale, in turn, the proposal of the Executive Agency for Water Management of the State of Paraíba (AESA) was used. The project area is drained by three major basins: the lower course of the Paraíba Basin; eastern portion of the Gramame River Basin; and the eastern portion of the Abiaí River Basin, in addition to some adjacent micro-basins.</p>
            <p class="paragraphy">In addition to these basins, some water courses form microbasins that flow into the Atlantic Ocean and were inserted in the aforementioned basins. Following the concept of <b>hydrographic basin</b><sup>1</sup> , we chose to separate them from these basins and group them into two secondary basins, here named <b>João Pessoa Secondary Basins</ b> and <b>Secondary Basins of the South Coast of Paraíba</b>, separated by the Gramame River Basin, as can be seen in Figure 1. Table 1 summarizes the main micro-basins and sub-basins inserted in the urban grid of João Pessoa or in its periphery, as well as its main rivers and streams and the dimension, in Km<sup>2</sup>.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={introclima1}><img src={introclima1} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Figure 1 - Hydrographic basins in the thesis area, outlined in red.</figurecaption>
                </figure>
            </div>
            <div class="text-center">
                <figure class="figure">
                    <figurecaption class="figure-caption">Table 1 - João Pessoa micro-basins and sub-basins, with their main tributaries and total area, in Km<sup>2</sup>.</figurecaption>
                    <a href={introclima2}><img src={introclima2} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Source: SEPLAN (2007).</figurecaption>
                </figure>
            </div>
            <h3>Paraíba River Basin-low course</h3>
            <p class="paragraphy">The Paraíba River, also known as the Paraíba do Norte River, is the main river in the homonymous basin and the longest river in Paraíba. The Paraíba River Basin is the second largest basin in Paraíba, inferior to the Piranhas River Basin.</p>
            <p class="paragraphy">It has an area of about 20 thousand Km<sup>2</sup>, bathing 38% of the State area, with coordinates of 6º51'47" - 8º18'12" of lat. South and 34º47’37" - 37º21’22" long. West. It comprises the Taperoá River sub-basin and geographically subdivided into Upper, Middle and Lower Course. It is its low course that bathes the municipalities of João Pessoa and Cabedelo, inserted in the area of this project. Thus, as it also bathes the municipality of Campina Grande, the second municipality in the state, this basin has the highest demographic density in the state, including more than half of the population of Paraíba.<sup>2</sup>.</p>
            <p class="paragraphy">The Paraíba River is the longest river in Paraíba, originating in the Serra de Jabitacá, municipality of Monteiro, more than a thousand meters above sea level, in one of the driest areas in the country, belonging to the 'Polígono das Secas', in the micro-region of Cariri in Paraíba. (LACERDA, 2003). To reach its mouth, which limits the municipalities of Cabedelo, João Pessoa, Santa Rita, Bayeux and Lucena, it travels 380 km and several geomorphological units and different climates, in addition to three mesoregions<sup>3</sup>.</p>
            <p class="paragraphy">Along this route, the Paraíba River suffers from several environmental and anthropic problems. Due to the fact that it was born in an arid region, much of the basin has an intermittent character, which forced several government administrations to build dams and dams, such as the Epitácio Pessoa Dam, in Boqueirão, responsible for supplying the municipality of Campina Grade, the second largest urban center of the State (CUNHA, 1998). However, according to AESA (2009), the water storage capacity in these dams is greater than one billion m<sup>3</sup>, whose dams change their fluvial dynamics, resulting in greater spacing of floods along the its course (SILVA, 2003), these floods that reach its estuary since the first records of colonial occupation began to be documented, that is, in the 17th century.</p>
            <p class="paragraphy">Another problem that occurs in its medium and upper course and that ends up affecting its estuary is the silting process, the result of inadequate agricultural practices, associated with the cultivation of sugarcane and the intense deforestation of its riparian forests. Large volumes of sediment reach the lower course of the river, much of it from the erosion of nearby slopes, and are deposited as river capacity decreases. The result is the accumulation of these sediments, forming sand banks, islets, reducing the width and depth of the river and making its waters more turbid.</p>
            <p class="paragraphy">The estuary of the Rio Paraíba has about 22 km, from its mouth, in Cabedelo, to the bridge of the River Sanhauá, in João Pessoa. Its main left bank tributaries are the Portinho, Tiriri, Ribeira and Guia rivers, all outside the project area. The tributaries on the right bank, in the area of work, are the River Sanhauá-Marés, Paroeira and Mandacaru (SUDENE, 1974). The Jaguaribe River, which forms one of João Pessoa's main urban micro-basins, flows into the Mandacarú River, a right bank tributary of the Paraíba River and, therefore, will be considered a sub-basin of the Paraíba Basin in its lower course.</p>
            <h3>Marés-Sanhauá River Sub-basin</h3>
            <p class="paragraphy">At the meeting of Rio do Meio and Marés, the Sanhauá River is formed. This river touches the lower town of João Pessoa, in the historic center, for about 8 km, while shaping the trays to the east, serving as a natural border, along with the Rio Marés, between João Pessoa and Bayeux, to the west, flowing into the river Paraíba (COSTA, 2009). Its main problem was having received, between 1957 and 2003, effluents from the <b>Roger's dump</b>, located near its lower course. It corresponds to an area with a relatively poor drainage network, although the denudational notches of the Rio Marés are relatively intense, resulting in steep slopes (FURRIER, 2007).</p>
            <p class="paragraphy">The handshake between the leader Piragibe and João Tavares, representing the Portuguese Crown, which sealed the peace agreement and later led to the foundation of the city of Nossa Senhora das Neves, took place on the banks of the Sanhauá River, hence its importance not only ecological-environmental, but historical.</p>
            <p class="paragraphy">In general, both rivers are relatively linear, with predominantly SW-NW flow direction and little sinuous escarpments. Barbosa and Furrier (2012) performed a morphological and morphometric assessment in the Rio Marés, concluding that the relief configuration pointed to evidence of neotectonic activities. Both rivers are characterized as the subsequent type, corroborated by Andrades Filho (2010), who studied the sub-basin through remote sensing techniques, suggesting that this region was affected by Quaternary age neotectonic faults.</p>
            <hr />
            <span>
                <sup>1</sup>A complex of areas drained by a river and its tributaries, the hydrographic basins can be considered as main, secondary and tertiary, and may also be, depending on their subaffluents, such as coastal, central or inland (GUERRA, 1987).<br />
                <sup>2</sup>EFSA. Rio Paraíba Committee. extracted from <a href="http://www.aesa.pb.gov.br/comites/paraiba/">http://www.aesa.pb.gov.br/comites/paraiba/</a>. Accessed on Feb 15, 2015.<br />
                <sup>3</sup>From the source to the mouth: Borborema, Agreste and Litoral.
            </span>
        
        </>
    )
}