export function ENNeotectonica(){
    return(
        <>
        <p class="paragraphy">The drainage network in the area is strongly influenced by faults, whose predominantly dendritic pattern, over the crystalline shield, commonly presents deflection along the Pre-Cambrian shear zones. When entering the sedimentary terrain, the drainage pattern parallels the NE direction faults, which suggests a tectonic control (BEZERRA et al., 2001a; BARBOSA, 2007). The drainage network that exudes the Plio-Pleistocene sediments of the <b>Barreiras Formation</b>, sometimes exposing the underlying layers, forms a V-shaped valley, whose larger rivers, such as the Paraíba, Abiaí and Gramame rivers , form well-developed alluvial and fluvial-marine plains at the bottom of these valleys. The different levels of fluvial carvings can be considered inheritances from the tectonic movements that shaped the terrain where these rivers pass.</p>
        <p class="paragraphy">The estuarine complex of the lower Paraíba River with all its tributaries is associated with the Graben of João Pessoa. According to Barbosa and Lima Filho (2006) and Barbosa (2007), this basin is associated with the exposure and erosion of the Maastrichtian limestones of the <b>Gramame Formation</b> and its fracturing. The Paraíba River, which flows straight in its low course in the NE-SW direction, abruptly bends towards the NS direction, in the vicinity of João Pessoa, from there reaching the coast, having been selected as a Place of Interest (Praia do Jacaré) . The importance of neotectonic phenomena can be seen by analyzing the configuration of certain rivers in the area's hydrographic network, through which we present some examples below.</p>
        <p class="paragraphy">On the south coast, through the analysis of digital elevation data acquired by the SRTM, integrated with fieldwork, Rossetti et al. (2009) analyzed the behavior of the Alhandra sub-basin drainage network, as well as the Barreiras sediments that it exudes, in relation to the neotectonic activities that influence them. The authors compartmentalized the sub-basin into two areas: the first extends from the Abiaí Depression, extreme south of the area of this thesis to the Gramame River, encompassing the Guruji, Graú, Água Boa and Salsa rivers; the second, an area that involves the first, referring to the Gramame River basins, to the north and Papocas-Taperubus, to the south, outside the area of this thesis.</p>
        <p class="paragraphy">The first compartment has a greater degree of inclination and a more pronounced convexity pattern at the interfluves than the surrounding compartment. The rivers in the first area are straight, with curves at closed angles, corroborating the dendritic pattern proposed by Bezerra et al. (2001a), while the drainage network of the second compartment presents rivers that change their direction sharply, almost at right angles, with a curved trellis pattern, and with straight and short tributaries flowing into the main river at right angles. This change in the behavior of the hydrographic network is related to the ‘<b>High Structural Coqueirinho</b>’, a structural feature mapped by Furrier et al. (2006) and Furrier (2007), considered in this thesis as a Place of Interest mainly due to its high aesthetic and scientific value.</p>
        <p class="paragraphy">The general direction of the hydrographic network of the <b>Gramame River Basin</b>, in the SW-NE direction, presupposes that it coincides with billing lines that have this direction. Most of the basin is inserted in the domain of the coastal tablelands, with the exception of its extreme west, on the crystalline basement and east in the coastal plain. With an east-west extension of about 60 km, in the low plateaus the altitudes vary from more than 200 m to 30-40 m, in this same direction, but outside the study area, which suggests that there is a terrain uplift in the western portion. Its slopes are elongated, and may vary from concave to predominantly convex, quite dissected, whose deforestation along its edges aggravates erosive phenomena with the deepening of furrows and ravines. Generally narrow, their valleys may widen in some portions, with the formation of fluvial terraces and the presence of colluvial deposits, visible in aerophotogrammetry.</p>
        </>
    )
}