import evolução1 from './media/evolução1.png';
import evolucao from './media/evolucao.png';





export function ENEvolucao(){
    return(
        <>
        <p class="paragraphy">The coastal marginal basins are divided into Sergipe-Alagoas, Pernambuco, Paraíba, Potiguar and Barreirinhas. Its formation is directly related to the continental drift that separated the African and South American continents, with the <b>Paraíba Basin</b> being the last to maintain contact with Africa. The area of ​​this thesis is entirely within the Paraíba Basin, one of the northeastern basins belonging to the Brazilian marginal basins, called <b>Coastal Province</b> (Almeida et al., 1977). For this work, the limits of the Paraíba Basin will be considered, from the Pernambuco Lineament to the Paraíba Lineament<sup>1</sup> . In the literature, this basin was part, until the mid-1990s, of the Pernambuco-Paraíba Coastal Sedimentary Basin<sup>2</sup> , when a separation was proposed by Lima Filho (1998) into two basins, Pernambuco and Paraíba , for presenting the origin, evolution and distribution of distinct formations, having the Pernambuco Lineament as a limiting element. To date, the delimitation of the contour of the Paraíba-Pernambuco-Potiguar basins is not consensual, as are discussions about the stratigraphic column and evolutionary history.</p>
        <p class="paragraphy">Figure 1 shows the northeastern portion of some marginal basins, locating the <b>Paraíba Basin</b> between the Pernambuco Shear Zone and the Mamanguape Fault. This basin is subdivided, from south to north, into sub-basins: Olinda, Alhandra (where our study area is located) and Miriri. It borders: to the north, with the Natal Platform of the Potiguar Basin, through the Paraíba Lineament, which extends through the Mamanguape Fault; to the south, with the Pernambuco Basin, through the Pernambuco Lineament; and, to the west, with the crystalline basement. This will be the configuration that will be followed in this thesis.</p>
        <div class="text-center">
            <figure class="figure">
                <a href={evolução1}><img src={evolução1} alt="" class="img-fluid" /></a><br /> 
                <figurecaption class="figure-caption">Figure 1 - Location map of the northeastern Brazilian marginal basins, with the position of the project area (in red). Source: modified from Barbosa and Lima Filho (2006).</figurecaption>
            </figure>
        </div>
        <p class="paragraphy">All the evolutionary proposals presented below, for the sedimentary range between Recife and Natal, covering, therefore, the <b>Paraíba Basin</b> and the eastern portion of the Potiguar Basin, were elaborated from a sum of data obtained of geophysical studies, paleoecological and paleontological investigations, field studies, stratigraphy, sedimentology, among others, by several authors. However, it is worth noting that, of the marginal basins, the Paraíba Basin is one of the least studied.</p>
        <p class="paragraphy">After the advent of the <b>Theory of Plate Tectonics</b>, in the 1970s, explanatory proposals for the dynamics of continental drift were intensified, especially between the South American and African plates, and about the tectonic consequences of this event, such as the expansion of the ocean floor, the opening of the Atlantic Ocean and, pertinent to our research area, the formation of coastal marginal sedimentary basins in Brazil.</p>
		<p class="paragraphy">In that decade, there was a certain unanimity among international scientists that the separation of South America and Africa, with the complete opening of the Atlantic Ocean, without a delayed connection, would have occurred in the Lower Cretaceous<sup>3</sup>. The Brazilian Northeast would be the last link between the two plates. From studies carried out in Brazil, this age began to be questioned, through information involving paleontology, geophysics and sedimentology (BEURLEN, 1971; TINOCO, 1971) where, until the Late Cretaceous, there would be a link, in the form of a “<b><i>land bridge</i></b>” between the two continents (RAND, 1976; RAND and MABESOONE, 1982).</p>
        <p class="paragraphy">According to Rand and Mabesoone (1982), before the beginning of the separation between Africa and South America, in the region where the Paraíba Basin would later form, there probably already existed a fault system, with an EW direction, which crossed both continents, such as the Pernambuco Lineament, for example, still in the Early Cretaceous. From the opening of the proto-ocean, to the north and south of this connection between them, the existing faults, as the separation progressed, facilitated the sliding of the plates, acting as transcurrent faults, until the bridge ruptured, in the Campaniano (83.6-72.1 Ma.) - Maastrichtian (72.1-66 Ma.). From there, the transverse faults changed to transform faults and the Equatorial Atlantic Ocean joined the South Atlantic in the Upper Cretaceous<sup>4</sup>.</p>
        <p class="paragraphy">Before the rupture of this bridge, during the Jurassic-Cretaceous, according to Asmus (1975) and Porto and Asmus (1978), adapting their evolutionary model for the Paraíba Basin, in the so-called pre-rift stage, there is a pre-volcanic swelling and stretching. of the continental crust, with subsequent block failure and subsidence, in a mixture of tectonic and eustatic factors (LIMA FILHO, 1998; LIMA FILHO et al., 2005), forming the marginal intracratonic basins and the horst-grabens system that characterizes them and which will be duly analyzed in the next subchapter.</p>
        <p class="paragraphy">With basement stabilization, as plate divergence advances, the thinned and fractured crust of the northeastern coast cools and the terrain sinks at the end of the Turonian (93.9-89.8 Ma, sensu PETRI, 1987; FEITOSA et al. al., 2002), along fault planes previously formed, generating a homocline and staggered ramp, gently sloping to the east, while the Pernambuco Basin rises (PETRI, 1987; LIMA FILHO et al., 2005). The Alto de Mamanguape serves as a barrier that limits the Paraíba Basin, to the south, with the Natal Platform, to the north (FEITOSA et al., 2002).</p>
        <p class="paragraphy">In the Lower Santonian-Campanian, deposition begins in the Paraíba Basin, in a depressed region, with clastic sedimentation of the <b>Beberibe Formations</b> and, later, the <b>Itamaracá</b>, typical of the environment coastal (continental-estuarine) and transitional-marine, respectively (AMARAL et al., 1977), forming a continental clastic wedge. Asmus (1975) proposes that this filling has started much earlier, in the Aptian (125-113 Ma), while Lima Filho (1998) and Lima Filho et al. (2005) propose the Conaciano (89.8-86.3 Ma) as the beginning of sedimentation, representing a regressive marine event, which shows that, despite the intense studies carried out in the scope of the basin's evolution, the controversy remains.</p>
        <p class="paragraphy">At the beginning of the Campaniano, there will be a rapid submergence of the basin, as a result of the subsidence of the terrain that extends from the Alto de Mamanguape to the Alto de Touros, registered by the advance of the coastline paleoline verified in well profiles and in outcrops (BARBOSA et al., 2003). Old faults are reactivated and new ones are generated, including submerging the Alto de Mamanguape. Subsequently, with very rapid submergence, clastic sediments from the <b>Beberibe Formation</b> and the <b>Itamaracá Formation</b> mix with siltstones and sandstones from a coastal lacustrine environment. At this moment, the carbonated clastic sediments from the higher southern areas would have covered the continental clastic sediments of the <b>Beberibe Formation</b>, in the Paraíba Basin. It is considered, therefore, a great evolutionary event that would have spread throughout this east coast. Feitosa et al. (2002) suggest the name Pernambuco-Paraíba-Rio Grande do Norte Coastal Basin for this area that extends from the Pernambuco Shear Zone to Alto de Touros.</p>
        <p class="paragraphy">Convém salientar que, em pesquisas de campo, a exígua presença da sequência clástica da <b>Formação Beberibe</b> e da <b>Formação Itamaracá</b> nas proximidades da área da tese, porção norte da Bacia da Paraíba, em relação à abundância desta sedimentação na sub-bacia Olinda, nas proximidades de Recife, possibilita inferir que o comportamento da paleolinha de costa durante esta fase inicial de subsidência foi irregular (AMARAL et al., 1977). Foram encontrados alguns afloramentos de rochas da <b>Formação Beberibe</b> ao longo das vertentes do Rio Mumbaba, tendo sido selecionado um deles como Local de Interesse: Afloramento da Formação Beberibe.</p>
        <p class="paragraphy">At first, the sea only invades the sub-basins to the north, Miriri and Alhandra. Gradually, the Olinda sub-basin is submerged, while the transgression has reached kilometers inland in the northern sub-basins. Phosphate deposition in the vicinity of João Pessoa is much further away from the coastline than in the vicinity of Recife, indicating that the sea advanced much further in this portion of the basin, which corroborates the possibility that the southern portion of the basin is higher than the North center. All this information has been confirmed by an extensive study of drill cores along the coast in question by several authors, such as Souza (2006) and Barbosa (2007).</p>
        <p class="paragraphy">At the end of the Lower Campanian-Maastrichtian, a metric layer of phosphorites is deposited covering the <b>Itamaracá Formation</b>, outside the thesis area, representing the maximum submersion of the basin, called Maximum Flood Surface, in a reducing environment with the presence of organic matter and clay minerals, where there is a significant reduction in the contribution of siliciclastic sedimentation.</p>
        <p class="paragraphy">The Maximum Flood Surface represents the replacement of a continental-marine transitional system tract, with the deposition of clastic sedimentation from the <b>Beberibe Formation</b> and <b>Itamaracá Formation</b> to the carbonate sedimentation of the < b>Gramame Formation</b>, already in a marine environment, which will last throughout the Maastrichtian (LIMA FILHO and SOUZA, 2001). This phosphatic horizon was not deposited north of Alto de Mamanguape, on the east coast of Rio Grande do Norte, which may be representative that that area was topographically higher than the southern portion, not allowing submersion by ocean waters to the point of the Maximum Flood Surface reaches a large extent.</p>
        <p class="paragraphy">Phosphate deposition is a result of the reduction of sedimentary input, where clastic sediments hardly reach the interior of the basin (MENOR et al., 1977; MENOR and AMARAL, 1979; LIMA FILHO et al., 1998; SOUZA, 1999; LIMA FILHO and SOUZA, 2001; BARBOSA, 2004; SOUZA, 2006). The hot and dry climate (PETRI, 1987) favored this decrease in clastic sedimentation, associated with the influx of upwelling currents that increased the action of algae and benthic organisms, responsible for fixing phosphorus on the substrate (MABESOONE, 1981) .
        </p>
        <p class="paragraphy">As previously mentioned, the deposition of the <b>Gramame Formation</b> began, already under the influence of the Thetys and the Equatorial Atlantic Ocean, since there was no longer any connection between Africa and South America (MAURY, 1930; OLIVEIRA, 1940; TINOCO, 1971; MUNIZ, 1993; CÓRDOBA et al., 2007). Throughout the Maastrichtian, the sedimentation environment of the limestones then formed was high sea level, not more than 100-150 m deep, and a tectonic calm. At the end of the Maastrichtian, a strong regressive event occurred, influenced by the drop in the eustatic level (HAQ et al., 1988), which exposed and eroded the limestones of the <b>Gramame Formation</b>, mainly in the northern sub-basins (BARBOSA, 2004; BARBOSA, 2007; BARBOSA et al., 2003; CÓRDOBA et al., 2007), probably concomitant to a tectonic rise in this portion.</p>
        <p class="paragraphy">One of the large outcrops of the <b>Gramame Formation</b> in the area, located at the Intercement cement factory, was selected as Site of Interest: Outcrop of the Gramame Formation, whose facies were described, sampled and analyzed in a thin layer.</p>
        <p class="paragraphy">In the last stage, from the Danian (66-61.6 Ma), already in a context of wide plate divergence, the free circulation of ocean waters developed extensive carbonate platforms where, with marine regressions and transgressions, the Frankish marine stage. It is represented in the area by the limestones of the <b>Maria Farinha Formation</b>, associated with an Atlantic basin.</p>
        <p class="paragraphy">The carbonate sedimentation of the <b>Maria Farinha Formation</b>, which succeeds the Gramame Formation, was deposited in a tract of the low sea system, representing a regressive event from the Lower Paleocene, ie, in the Cretaceous-Tertiary passage . This sedimentation outcrops more abundantly in the Olinda sub-basin, where deposition was late, practically non-existent in the Alhandra and Miriri sub-basins, where the transgression arrived earlier. In the thesis area, in the Alhandra sub-basin, this sequence outcrops sporadically on the southern coast, on beaches such as Tambaba and Jacumã. Barbosa et al. (2003) suggest that the lack or restriction of Paleocene deposits from the <b>Maria Farinha Formation</b> in the northern portion of the basin may be due to its non-deposition or erosion of this sequence when the platform was exposed, at the end of Maastrichtian, by sea level regression, or that the terrain north of the Goiana Fault has undergone an uplift, generating a forced sea level regression, which would have extended through the Paleogene (BARBOSA, 2007). Two Places of Interest were selected on this lithostratographic unit (Pedra do Amor and Praia de Tambaba), due to their exclusivity in the area and textural and structural characteristics, such as dissolution features and fossiliferous abundance.</p>
        <p class="paragraphy">The evolutionary model dealt with in this subchapter up to the Late Cretaceous can be summarized in Figure 2. The final result of the basin configuration is a taphrogenic system<sup>5</sup> forming uneven blocks, through the uplift or lowering of the terrain, defined as “<b>key tectonics</b>” (FORTES, 1986), along fault planes perpendicular to the coastline, with an essentially NE direction and which will be analyzed below. The modeling exercised by exogenous factors in more current periods resulted in a set of forms of reliefs of spectacular beauty, which have intrinsic geotouristic qualities.</p>
        <p class="paragraphy">This subchapter included information about the regional geology of the basins associated with Paraíba which, for some time, with very few exceptions, were considered to belong to the same tectonic and sedimentary filling stage. It aimed to draw a historical and comparative assessment of the Paraíba and Pernambuco Basins, until recently considered a single basin, through significant bibliographical references for a better understanding.</p>
        <div class="text-center">
                <a href={evolucao}><img src={evolucao} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figure 2 - Stratigraphic evolution of the Paraíba Basin between the Coniacian and the Maastrichtian. Source: Souza (2006, p. 323).</figurecaption>
        </div>
		<hr />
		<span>
			<sup>1</sup>In the scientific world, this lineament/shear zone appears under the name of Patos or Paraíba. For geographical reasons, we will choose, in this work, the name 'Paraíba', since it corresponds to the eastern portion of this feature, in the State of Paraíba, since Patos corresponds to a municipality in the 'Alto Sertão', 400 km away from Coast. <br />
<sup>2</sup>About this grouping of the two basins, we propose the reading of Asmus and Carvalho (1978), Rand and Mabesoone (1982), Mabesoone and Alheiros (1988, 1993), Feijó (1994) and Córdoba et al . (2007). <br />
			<sup>3</sup>Among them, SCLATER et al. (1977) and SMITH and BRIDEN (1977), corroborating the proposal of Beurlen (1962). <br />
			<sup>4</sup>According to Matos (1999), this rupture would have occurred much earlier, probably in the Albian (113-110 Ma). <br />
			<sup>5</sup>According to Guerra (1987), it corresponds to a crustal sinking that leads to the formation and development of geological basins where sedimentation and/or volcanism corresponding to the development phases of a rift accumulate.
		</span>
        </>
    )
}