import tectonica1 from './media/tectonica1.jpg';
import tectonica2 from './media/tectonica2.png';


export function ENTectonica(){
    return(
        <>
        <p class="paragraphy">Even located on a passive margin, the northeast coast has suffered numerous tectonic events, at different geological times, events that directly affect the sedimentary package stratigraphically above the basement. The objective of this subchapter is to draw a theoretical framework on the tectonic compartmentalization of this coastal portion of the northeast, especially the sedimentary strip between Recife and Natal, and its substrate, as well as to analyze the consequences of these events for the overlapping basins, whose sum of factors is responsible for the current morphology. This analysis makes it possible to facilitate the selection of places of interest of a tectonic nature, inventoried and quantified, for inclusion, or not, in the geotouristic map of the area.</p>
        <p class="paragraphy"> Considering the fragile character of the rocky substrate that underlies the sediments of the Paraíba Basin, characterized by a set of normal faults, the '<b>oriental salient</b>', in the vicinity of the study area and in part of it, is represented by a grabens-horst system that Brito Neves et al. (2004) defined it as ‘<b>Tertiary Taphrogenic System</b>’, which is responsible for the structural fabric of the coastal plain. The following belong to this system: Graben de Cariatá, Horst Boqueirão and the Mamanguape River graben system. Subsequently, through new surface and subsurface geological data and geophysical data, Brito Neves et al. (2009) extended this compartmentation, adding the Graben of the Rio Mamuaba, Baixo Rio Paraíba and Grande João Pessoa; and the Horst Tabuleiro das Lagoas, from Alto També-São Miguel in Taipu-Riacho Curimataú and Ciaisa. Of these, the Graben Cariatá, Graben Baixo Rio Paraíba, Rio Mamuaba and Grande João Pessoa and Horst Tabuleiro das Lagoas, units analyzed below, belong to the study area.</p>
        <p class="paragraphy">This taphrogenic system, in the Paraíba Basin, is related to the gravitational collapse of the continental margin after the rift (JARDIM DE SÁ et al., 2004), through normal planar faults with little tailings, which occurred more intensely after the Turonian (BARBOSA, 2007). The uplift of the terrain facilitates the exhumation of the Plio-Pleistocene sedimentation of the <b>Barreiras Formation</b>, which represents the platform coverage of the Paraíba Basin, duly analyzed a posteriori, while the lowering provides the deposition of quaternary sedimentation, which includes alluvial sediments, dunes, among others (LIMA et al., 1990). The cliffs, of unique scenic beauty, correspond to the steep portion of the horst, on the coastline, and may be over 40 m high.</p>
        <p class="paragraphy">The <b>Graben de Cariatá</b> has its maximum representation in the east of the municipality of Itabaiana in Paraíba. Towards João Pessoa, the Plio-Pleistocene sediments of the <b>Barreiras Formation</b>, as well as the Quaternary sediments, thicken, showing the ramp aspect that characterizes, even in stages, this taphrogenic system.</p>
        <p class="paragraphy">The <b>Graben of Mamuaba River</b> has an NNE-SSW direction, north of the municipality of Pedras de Fogo, covers the lower course of the homonymous river and has the greatest thicknesses of the Alhandra sub-basin, as well as the highest altitudes, with 212 m, forming a domic structure that serves as a watershed for the tributaries of the Gramame and Mamuaba rivers.</p>
        <p class="paragraphy">The <b>Lower Paraíba River Graben</b> is limited to the Horst Tabuleiro das Lagoas, to the north, by a normal fault in the W-SW/E-NE direction, which passes through the municipality of Santa Rita. to Tambaú beach, in João Pessoa. It reaches a depth of about 50 m, being filled by tertiary sediments from the <b>Barreiras Formation</b> and quaternary alluvial sediments.</p>
        <p class="paragraphy">The <b>Graben of Big João Pessoa</b> is located to the east of the Horst Tabuleiro das Lagoas, having a staggered character to the east, through a fault system that reaches the municipalities of Bayeux and João Pessoa. In this graben, the overlapping sediments of the <b>Beberibe Formation</b>, <b>Gramame Formation</b> and <b>Barreiras Formation</b> are thickened by up to 300 m.</p>
        <p class="paragraphy">The <b>Tabuleiro das Lagoas Horst</b> presents a slight tilt to the east. The capping sediments reach about 40 m thick, one of the smallest in this portion of the 'salient'. It borders, to the south, with Graben Mamuaba; to the east, with the grabens system of Grande João Pessoa; to the north, with the Graben of the Lower Paraíba River. Three Places of Interest (LIG/CH 10, 11 and 12) are inserted in this horst, which plays a fundamental role in its existence. The profile of Graben from Grande João Pessoa and Horst from Tabuleiro das Lagoas can be seen in Figure 1.</p>
            <figure class="figure">
                <a href={tectonica1}><img src={tectonica1} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figure 1 - ESE-WSW profile showing the behavior of the basement, forming the Graben of Grande João Pessoa, to the east and the Horst Tabuleiro das Lagoas, to the west, and its overlapping sediments, prepared from data from dozens of tubular wells. Caption: UPEN-Engenho Novo Pedostratigraphic Unit. Source: modified from BRITO NEVES et al. (2009).</figurecaption>
            </figure>
        <p class="paragraphy">A profile elaborated based on drilling cores was proposed, starting from the horst of Alto També - São Miguel de Taipu - Riacho Curimataú, western portion of the 'Saliente' and outside the thesis area, towards the Graben of João Pessoa, in the project area, it can be seen in figure 2.</p>
            <figure class="figure">
                <a href={tectonica2}><img src={tectonica2} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figure 2 - SSW-NNE profile showing the behavior of the basement, forming the Graben da Grande João Pessoa, the NNE and the Horst do Alto També - São Miguel de Taipu - Riacho Curimataú, the SSW, and their overlapping sediments. Source: modified from ROSSETTI et al. (2012).</figurecaption>
            </figure>
        <p class="paragraphy">Nowhere on the coast of Paraíba does the crystalline shield appear. The most proximal portion of the basement is near the municipality of Conde, about 15 km from the coast. Through the analysis of hundreds of drillings along the northeastern coast, north of Recife to the vicinity of Natal, Barbosa (2007) prepared a structural contour map, characterizing the behavior of the basement along the aforementioned area, with results from regional features of this rocky substrate.</p>
        <p class="paragraphy">As a result, this graben system has a variable depth along the above-mentioned sedimentary strip. In the Pernambuco Basin, the grabens are much deeper than in the Paraíba Basin and Natal Platform, reaching eight times the depth (on average 150-200 m up to 3000 m, respectively). Thus, the depth of the basement varies along the sedimentary strip between Recife and Natal, as well as the angle of the slope that form the basins. Barbosa and Lima Filho (2005, 2006) and Barbosa (2007) prepared a structural contour map of the range between Recife and Natal, where the entire area behaves like a smooth ramp, with gradients varying between 1st and 3rd<sup>1 </sup>. The slopes of the ramp in the Paraíba Basin, however, are greater and the ramp is wider than its neighbors to the north and south, respectively, Plataforma de Natal and the Pernambuco Basin. The Olinda sub-basin is the widest of the Paraíba Basin sub-basins, with the Alto de Goiana as its northern limit. The Pernambuco Basin, located to the south, has, near the Pernambuco Shear Zone, a coastal zone so narrow that the basement practically outcrops in contact with the sea.</p>
        <p class="paragraphy">It can be concluded, therefore, that the current coastal landscape is the result of the interaction of several factors, including neotectonics, generating faults, with uplift and subsidence of blocks; marine regressions and transgressions; and weathering/erosion, with subsequent sedimentary deposition, resulting in a set of relief forms, associated with geology, with an immense geotouristic potential, according to the evaluation and quantification, subsequently carried out, of Places of Interest in the area of this thesis. </p>
        <hr />
        <span>
            <sup>1</sup>Most authors call this ramp model a homocline, gently sloping to the east. Barbosa and Lima Filho (2006) and Barbosa (2007) consider it to be a distally inclined ramp with a slope.
        </span>

        </>
    )
}