import unidade1 from './media/unidade1.png'


export function ENUnidades(){
    return(
        <>
            <p class="paragraphy">Considering the area of ​​the thesis, the <b>Paraíba Group</b> is represented by the basal clastic sequence of the <b>Beberibe Formation</b> and by the carbonate sequence of the <b>Gramame Formation</b> and <b >Maria Farinha Formation</b>, not touching on the clastic sequence of the <b>Itamaracá Formation</b>. The <b>Barreiras Formation</b>, which discordantly covers the sediments of the <b>Paraíba Group</b> and the crystalline basement, represents a platform cover, overlaid by unconsolidated Quaternary sediments, alluvium deposits, terrace sediments Pleistocene and Holocene sediments, beach sediments, reefs, fluviolagunar and mangrove deposits, among others, which occur in the geomorphological unit of the coastal-fluvial plain. This subchapter is the result of the geological mapping carried out in the project area, in which the heritage value of geodiversity was identified, characterizing the Geologically-oriented Places of Geotourism Interest (petrographic, paleontological, mineralogical, stratigraphic and tectonic). It should be noted that at least one Site of Geotourism Interest was selected in each lithostratigraphic unit.</p>
                <p class="paragraphy">Figure 1 outlines the stratigraphic column of the sedimentary belt belonging to the Alhandra Sub-basin, of the Paraíba Basin, where, with the exception of the <b>Itamaracá Formation</b> and the phosphatic horizon, the other lithostratigraphic units outcrop in the project area and will be presented below.</p>
                <div class="text-center">
                    <figure class="figure">
                        <a href={unidade1}><img src={unidade1} alt="" class="img-fluid" /></a><br />
                        <figurecaption class="figure-caption">Figure 1 - Schematic stratigraphic column of the sedimentary strip belonging to the Alhandra sub-basin, in the Paraíba Basin. Source: modified from Barbosa (2007, p. 29).</figurecaption>
                    </figure>
                </div>
                <h3>Beberibe Formation</h3>
                <p class="paragraphy">The <b>Beberibe Formation</b> represents the beginning of the sedimentary input in the Paraíba basin, in Santoniano - Campaniano Inferior (83.6 - 72.15 Ma). The name was proposed by Kegel (1953, 1955), as Member Beberibe and Beurlen (1967a) elevated the Member Beberibe, belonging to the <b>Itamaracá Formation</b>, to Formation status, while the <b>Itamaracá Formation</b> was appended to the <b>Gramame Formation</b>, which automatically became thicker.</p>
                <p class="paragraphy">The <b>Beberibe Formation</b> has a maximum thickness of 280 m, resting discordantly on the crystalline basement, through an erosive unconformity. It comprises a thick wedge of quartz sandstones, of continental origin, poorly selected, fine to coarse, friable and porous, gray to cream in color, poorly fossiliferous, with flat-parallel stratification. It contains some finer components, such as siltstones and fine to very fine sandstones, representative of the fluvial-lagunar plain, ranging from monomitic to oligomitic conglomeratic sandstones with 15 cm clasts, whose sandstone sedimentation environment is fluvio-lacustrine, specifically the fluvial channel of the '<i>braided</i>' type of high energy. Laterally, they can interdigitate with a more compact sandstone, cemented by carbonates, representing the ancient <b>Itamaracá Formation</b>, typical of a fluviolagunar to fluviodeltaic facies domain. It is important to point out that this porous facies of the formation is responsible for housing a substantial underground water reservoir, the <b>Beberibe Aquifer</b>, located at depths greater than 100 m, therefore of difficult contamination, and that supplies the Region Metropolitan of Recife and João Pessoa, in this case the Mamuaba-Gramame System, of the Water and Sewage Company of Paraíba (CAGEPA).</p>
                <p class="paragraphy">Beurlen (1967a, b) defines the Coniatian-Santonian age (89.8 – 83.6 Ma) for this deposition. According to Barbosa et al. (2003), this age was inferred from the fossiliferous content of the marine environment that was later attributed to the <b>Itamaracá Formation</b>, which presupposes that the <b>Beberibe Formation</b> is older than the Santonian. The deposition of the <b>Beberibe Formation</b> began in the Alhandra and Miriri sub-basins (central-north portion) before the Olinda sub-basin (southern portion), which was already uplifted, in the Turonian (93.9 – 89.8 Ma), when filling began, probably in the Middle-Superior Campaniano. This formation is more expressive in the Olinda sub-basin than in the north-central sub-basins, not occurring north of the Paraíba Lineament. </p>
                <p class="paragraphy">The main outcrops of this unit are located essentially along the river valleys, directly on the low-angle structural ramp of the basement, and were exposed by the action of water that eroded the overlapping layers, exhuming this formation. They are located in the middle course of the Mumbaba River, as is the case with the selected Place of Interest. It should be noted that for field geologists there is great difficulty in differentiating the sandstones of this formation from those of the <b>Barreiras Formation</b>, due to their textural similarity, even more so if the outcrop is intensely weathered.</p>
                <h3>Formação Gramame</h3>
                <p class="paragraphy">It corresponds to the first carbonate unit of the marine domain, resting accordingly on the clastic sequence of the <b>Itamaracá Formation</b>, through a nonconformity (MANSO, 1982). It is about 70 m thick (ALMEIDA, 2000b), having been first mentioned in the literature by Oliveira (1940), and respecting the marly limestone outcroppings along the Gramame River, later extrapolating its extension to Pernambuco.</p>
                <p class="paragraphy">The limestones and marls of the <b>Gramame Formation</b> are intercalated with a plane-parallel stratification of great lateral continuity, typical of an extensive low gradient carbonate platform (BARBOSA, 2007). Based on the study of fossiliferous content, Maury (1930), ratified by Muniz (1993) and Córdoba et al. (2007), proposed an age from the Upper Campanian (72 Ma), being revised by Beurlen (1967a) to the Maastrichtian (72.1 – 66 Ma), which was corroborated by Tinoco (1967, 1971).</p>
                <p class="paragraphy">The type outcrop area is located on the right bank of the homonymous river, which borders João Pessoa with the municipality of Conde, also appearing in Ilha do Bispo, on the outskirts of João Pessoa, where the Place of Interest is located and in other river valleys on the south coast, included in the area of this project: left bank of Rio Abiaí, right bank of Rio Camocim, among others. The absence of this formation west of BR-101 may reflect the non-deposition of this sequence in the area or erosion after sub-aerial exposure, generated by the regression of sea level at the end of the Maastrichtian (FURRIER, 2007). Deposition is wider in the Alhandra and Miriri sub-basins in relation to Olinda (BARBOSA, 2007).</p>
                <h3>Maria Farinha Formation</h3>
                <p class="paragraphy">The <b>Maria Farinha Formation</b> corresponds to the last sedimentation package of the Paraíba Basin, representing the top of the <b>Paraíba Group</b>, whose base refers to the Beberibe Formation. It was dated as Paleocene (66 – 56 Ma), being separated from the <b>Gramame Formation</b> by an unconformity, formed with a thin layer of detrital limestone, which marks the Cretaceous-Tertiary passage (Maastrichtian/Danian – 66 Ma , sensu ALBERTÃO, 1993; ALBERTÃO and MARTINS JUNIOR, 1996; BARBOSA, 2007; CÓRDOBA et al., 2007), with a gentle 5º dip to the east and swell in the north-south direction (OLIVEIRA and ANDRADE RAMOS, 1956).</p>
                <p class="paragraphy">The pioneer author in the name of this formation was Oliveira (1940), to characterize the fossiliferous limestone outcropping in the vicinity of Recife. Beurlen (1967a) divided the Formation into <b>Maria Farinha Inferior and Superior</b>. The lower portion refers to outcropping rocks in the Olinda sub-basin, represented by a sequence of clayey limestones and marls, with Danian age (66 – 61.6 Ma), representing an inner continental shelf, influenced by estuaries, while the upper one is associated with the Miriri and Alhandra sub-basins, represented by dolomitic limestones, locally biodetrital, associated with an extremely shallow marine environment, lagoon and/or reef (MUNIZ, 1993; ALMEIDA, 2000b; BARBOSA et al., 2006). possibly representative of a stop at sea level during the regressive event, in the Eocene (56 - 33.9 Ma), when the sea was relatively shallow and warm, providing the deposition of limestone fringes that currently outcrop on the southern coast of Paraíba (BARBOSA et al., 2006; BARBOSA, 2007). Barbosa et al. (2006) and Barbosa (2007) corroborate the existence of a paleofaunistic, lithofaciological and sedimentation environment differentiation between the lower and upper portion of the <b>Maria Farinha Formation</b>. The passage from the <b>Gramame Formation</b> to the <b>Maria Farinha Formation</b> Inferior can be seen in the Poty Quarry and in Nassau, in the Olinda sub-basin, outside the thesis area, where 15 m limestone and marl gradually become more clayey and more siliciclastic at the top, showing the gradual effect of marine regression. In this sub-basin, the <b>Maria Farinha Formation</b> is more preserved, even if the marine transgression was late, unlike the sub-basins to the north, where the platform coverage of the <b>Barreiras Formation</b> was deposited on the <b>Gramame Formation</b>. </p>
                <p class="paragraphy">In the northern sub-basins of the Paraíba Basin, the <b>Maria Farinha Formation</b> outcrops as fringes on the coast, on beaches such as Coqueirinho, Jacumã, Tabatinga and Tambaba, on the southern coast of the study area (LEAL E SÁ, 1998; ALMEIDA, 2000b; BARBOSA, 2004; SOUZA, 2006), influencing the configuration of the current coastline, as it forms beaches in 'zeta'. It can occur as submerged rocky banks, where abundant coral organisms develop (ALMEIDA, 1989) or closer to the coast or in the form of small islands, whose sedimentary deposition, in areas of lower energy, ends up forming tombolos.</p>
                <p class="paragraphy">With a thickness of about 35 m, its faunal content is represented by gastropods, molluscs, corals, lamelibranchs, remains of turtles and echinoderms (BEURLEN, 1959), typical of a shallow marine environment, close to the coast of the reef. This content provided the proposition of age of deposition as being Lower Paleocene-Eocene (MABESOONE, 1995; ALMEIDA, 2000b). From the point of view of structural features, it presents hummocky cross stratification, ascending grain decay and wave stratification, which makes it possible to characterize its deposition as being associated with storm events in a carbonate ramp platform (SOUZA, 2006).</p>
                <h3>Barriers Formation</h3>
                <p class="paragraphy">The first author to cite the name 'Barreiras' in the literature was Branner (1902), referring to outcropping rocks on the northeastern coast, a term repeated by Moraes (1928), with the name Formation of Barreiras, without formal scientific or stratigraphic connotation.</p>
                <p class="paragraphy">The <b>Barreiras Formation</b> stratigraphy is still controversial today. Oliveira and Leonardos (1943) placed the sequence at the level of Série Barreiras, referring to the salient boards that extend along the coast of Paraíba. The name <b>Barreiras Formation</b> was proposed by Oliveira and Andrade Ramos (1956) and Kegel (1957)<sup>1</sup> for the clayey-sandy sediments that outcrop on the northeastern coast, which are afossiliferous and colored alive, which even called the attention of Pero Vaz in his first letter describing the Brazilian territory. It was raised to the level of Grupo Barreiras by Bigarella and Andrade (1964), and divided into Formation Guararapes and Riacho Morno, separated by an erosive discontinuity. This subdivision was questioned by Mabesoone et al. (1972), studying Barreiras outcrops along the coast from Pernambuco to Rio Grande do Norte. For the authors, the Riacho Morno Formation would be part of an weathering event inserted in the Guararapes Formation, and the reason why they subdivided the group into two more formations: Serra dos Martins and Macaíba.</p>
                <p class="paragraphy">The definition of Training will be taken up later by Alheiros et al. (1988), whose large lateral extension will be considered as a single lithostratigraphic unit, considering its lithological characteristics and sedimentological development, through detailed studies using more modern stratigraphic techniques. We chose the name <b>Barreiras Formation</b> over the <b>Barreiras Group</b> because there are still serious problems of stratigraphic delimitation and definition of the formations that would be part of this group, due to the difficulty of distinguishing between them, which is why for which, in scientific meetings to discuss various information about the Barreiras sediments, such as the symposia attached to the Congress of the Brazilian Association of Quaternary Studies, from 2005, the vast majority of scholars use the name <b>Barreiras Formation</ b>.</p>
                <p class="paragraphy">The <b>Barreiras Formation</b>, therefore, is one of the largest sedimentary sequences in Brazil, outcropping in approximately 4,000 km of coastline, from the mouth of the Amazon River (latitude 4º N) to the coast of Rio de Janeiro (latitude 22º S; MABESOONE et al., 1972). In Paraíba, their geomorphology is dominated by coastal plateaus that end on the coast in the form of magnificent and beautiful cliffs, such as Cabo Branco, with great tourist appreciation, despite being in Rio Grande do Norte that they have the greatest heights (BARBOSA, 2007). Even with this great extension, the presence of a Tortonian discordance (11,6-7,2 Ma) in the entire sequence allowed this interregional correlation<sup>2</sup> . This disagreement is marked by the presence of a ferruginous lateritic paleosol, whose 19 samples of gheetites, taken from the Barreiras sediment in the Paraíba Basin, were dated by the (U/Th)/He method, resulting in concentration peaks of ages between 1-2 Ma (ROSSETTI et al., 2012).</p>
                <p class="paragraphy">Even so, its age remains controversial, mainly due to the weak fossiliferous content. Suguio et al. (1986) and Lima et al. (1990), through paleomagnetic dating and the study of palynological material, respectively, proposed a Pliocene age, specifically 4.5 to 5.0 Ma for the base of the deposit and 3.0 to 3.4 Ma for the top. Alheiros and Lima Filho (1991) proposed the Plio-Pleistocene age. Arai (2006), Arai et al. (1988, 1994) and Leite (2006), based on palynological studies, suggested the lower to medium Miocene, while Bezerra et al. (2001a), based on paleomagnetic and micropolynic dating, suggested ages between the Miocene and Pliocene. Lima et al. (2007) and Lima (2008) dated Barreiras sediments located between the coast of Ceará and Potiguar, using the 40Ar/39Ar and (U/Th)/He method, whose deposition age resulted between 18 and 22 Ma, that is, , Lower Miocene, and the weathering lasted up to about 7 Ma. These data, added to those proposed by Rossetti et al. (2012), allow us to state that after the deposition of the <b>Barreiras Formation</b>, in the Lower Miocene, its sediments were exposed to a long period of sub-aerial erosion that may have lasted until the Quaternary, when the post-Barreiras sedimentation deposition, in this case, the units called PB-1/PB-2.</p>
                <p class="paragraphy">Another controversy stems from the origin of the Barreiras sedimentation. The first researchers described it as having a continental origin (OLIVEIRA and LEONARDOS, 1940). This thought of continental origin returned later, with a sedimentation environment that would vary from '<i>braided</i>' fluvial to alluvial fans, passing through fluviolagunar deposits, always in a more arid phase than the current one. , during the Cenozoic, which was interspersed with humid periods that were responsible for the oxidation of the rocks, generating the aforementioned vivid coloration. The ‘<i>braided</i>’ fluvial facies is represented by coarse-grained sediments, such as gravel and coarse sand, with a yellowish to reddish cream coloration, interdigitated with siltic clays, typical of floodplain environments. They present medium to large fluted cross-bedding, with moderately selected sediments and with a low degree of rounding. In the fan facies, the rocks are polymitic conglomerates, with a reddish-cream coloration, interspersed with pelitic material and quartz pebbles and reworked clay blocks, usually in contact with the basement rocks (ALHEIROS et al., 1988; ALHEIROS and LIMA FILHO, 1991; MABESOONE and ALHEIROS, 1993; LIMA FILHO and MELO, 2007).</p>
                <p class="paragraphy">Barbosa (2007), using the isopaque map, determined a tabularity for the <b>Barreiras Formation</b> in the proximal portion of the basin, with domain of alluvial fans. The thickness is small in the Alhandra sub-basin, between Recife and João Pessoa, when the limestones of the <b>Gramame Formation</b> and <b>Maria Farinha Formation</b> outcrop, increasing in contact with the sub-basin Miriri, on the outskirts of João Pessoa, going back to thinning at the northern limit, in Alto de Mamanguape. From there towards Natal, the formation has the greatest thickness in this area. The highest altitudes, in the Paraíba Basin, are located in the furthest portion of the coastline, while in the Natal Platform, they are associated with cliffs, active or not.</p>
                <p class="paragraphy">Later, the discovery of marine fauna modified the proposals for the setting of this sedimentation (ARAI et al., 1988; ROSSETTI, et al., 1990; ARAI, 1997). According to Arai (2005), marine transgressive events of Miocene (Aquitanian-Serravalian) and Pliocene (Zanclean) ages, separated by Tortonian discontinuity, were responsible for the deposition of a thick sedimentary package, called <b>Inferior and Superior Barriers</b> , respectively. Later, in an environment of low sea tract, these sediments were eroded and reworked, giving rise to the current configuration of the coast where they are exposed, and which has a scenic beauty extremely favorable to geotourism.</p>

                <hr />
                <span>
                    <sup>1</sup>The lower layers of the Formation were called ‘Infra-barriers’.<br />
                    <sup>2</sup>This disagreement was a consequence of an erosive event of Tortonian age, caused by the eustatic fall of the Neogene, resulting from the formation of an ice cap in Antarctica and, according to some authors, separates the Inferior Barriers from the Superior. Rossetti et al. (2011, 2012), however, consider that this discontinuity, in the form of a ferruginous lateritic paleosol, represents the top of the Barreiras Formation, and the sediments superimposed on it are part of a new context of sedimentary environment, now belonging to the Quaternary, called PB-1 and PB-2, which were mapped by CPRM as eluvium-colluvial deposits, with the Gramame River Basin being the limiting factor for both. The author, however, suggests that these deposits extend over a much larger area.
                </span>
        </>
    )
}