function ENCronistas(){
    return(
        <>
        <h3>A Paisagem Cultural de João Pessoa e a geodiversidade na perspectiva dos cronistas e iconografistas do Período Colonial</h3>
        <p className="paragraphy">Este subcapítulo será dedicado à evolução urbana e socioeconômica de João Pessoa, enfatizando seu patrimônio cultural e o papel do meio abiótico, a partir dos elementos da geodiversidade, na escolha do sítio que serviu como assentamento da futura capital da Paraíba e dos meios para a sua construção. Este Patrimônio Cultural foi sendo estruturado ao longo do tempo, prioritariamente no período colonial (até 1822), <b>espaço temporal aqui abordado</b>, quando uma maior densidade de edificações foi erguida com a geodiversidade de seu substrato rochoso e se prepara o cenário para que os georecursos do Centro Histórico de João Pessoa e do litoral, através de suas edificações, pavimentação, obras de cantaria, dentre outros, sejam, no devido momento, mapeados. Esta evolução urbana e socioeconômica será analisada a partir dos relatos de cronistas e iconografistas que estiveram na Capitania da Parahyba.</p>
        <p className="paragraphy">Estas pessoas acompanhavam as expedições, a serviço do Rei ou da Igreja e registravam, através de dados escritos (textos e cartas) ou iconográficos (plantas e desenhos), todas as informações que fossem pertinentes ao Reino na perspectiva de ‘se conhecer para explorar’. Com “classNamees sociais variadas, profissão e formação intelectual diversificada, descreveram aspectos do Brasil, através de crônicas, relatos de viagem, correspondência, memórias, diários, álbuns de desenhos. O conjunto de obras deixadas por eles integra a chamada “literatura de viagem e se constitui numa<i> literatura de testemunhos </i>[...]” (CALDEIRA, 1991, p. 17). Podemos também citar a importância de viajantes estrangeiros que por aqui estiveram, sejam como invasores, a exemplo dos franceses e holandeses, ou aliados da Coroa Portuguesa, como os espanhóis na época da União Ibérica, ou os ingleses, após a ‘abertura dos portos’, em 1808, que também deixaram um rico legado para conhecermos a história de um período especial da formação de nosso território. O objetivo da maior parte destes cronistas era documentar informações que assegurassem a maior descrição possível sobre este novo território, envolvendo, por exemplo, desde os hábitos culturais dos povos indígenas, até as características da fauna e flora presentes, ou seja, sua biodiversidade.</p>
        <p className="paragraphy">A partir disto, a <b>geodiversidade</b>, que envolve <b>elementos geológicos</b> (rochas, minerais e fósseis), <b>geomorfológicos</b> (formas de relevo, depósitos e processos), <b>hidrológicos</b> (especialmente os regatos de água doce) e <b>pedológicos</b> (tipos de solo), também era objeto de análise por parte destes cronistas, uma vez que era interesse da Coroa, em um primeiro momento, explorar o substrato rochoso da colônia à procura de minérios que viessem a enriquecer o Reino, assim como, num momento posterior, se fixar no recente território ‘descoberto’. Assim, estes cronistas estavam valorizando, mesmo sem saber, a geodiversidade da terra conquistada e o seu geopatrimônio e divulgando-a além-mar, apesar destas ações irem na contramão daquilo que hoje se considera ser o geoconservacionismo. Ou seja, seu interesse era conhecer para explorar e não para fins de proteção.</p>
        <p className="paragraphy">Alguns viajantes tiveram a oportunidade de conhecer o nordeste brasileiro, assim como a Capitania Real da Parahyba e a sua capital, Nossa Senhora das Neves. Produziram farta documentação acerca da geodiversidade desta capitania, num primeiro momento restrita ao núcleo urbano da capital e proximidades e, posteriormente, com a interiorização da ocupação, aos sertões. Analisando-se por esta ótica, o objetivo aqui é descrever o resultado destas documentações, durante o período em que esta Capitania fez parte do contexto econômico da colônia, se livrando das amarras da metrópole em 1822.  Priorizar-se-á as informações obtidas no âmbito da capital e arredores, área de estudo desta tese, em especial a geologia, a geomorfologia, os recursos hídricos (regatos de água doce e estuários, especialmente o do Rio Paraíba) e solos.</p>
        <p className="paragraphy">As iconografias que retratam o cotidiano dos moradores, a arquitetura das edificações e a paisagem natural circundante também será objeto de análise neste capítulo, enfatizando os elementos da geodiversidade que tiveram um papel fundamental no assentamento humano e expansão urbana da atual cidade de João Pessoa. Em ambos os casos, o intuito é de reconhecimento do valor econômico, cultural e funcional da geodiversidade, como uma fornecedora de serviços de regulação, provisão, suporte e cultural, possibilitando elevar estes elementos a um status geopatrimonial.</p>
        <p className="paragraphy">Desta maneira, será atribuído um novo significado à paisagem, perpassando pelo estético-artístico ao funcional-econômico. É intencional, nesta fase, apresentar uma análise retrospectiva e comparativa da paisagem natural e da paisagem cultural, entrelaçando os supracitados elementos da geodiversidade às práticas culturais que forjaram a cidade e a identidade do povo que sobre ela se assentou. Mesmo que o legado deixado por estes cronistas não tenha como objeto principal os referidos elementos, é indubitável que eles influenciaram seus temas e atmosferas.</p>
        <p className="paragraphy">O somatório destes elementos, pormenorizados a seguir, aliados ao aparato cultural daquele período histórico, possibilita aferir sobre a <b>Paisagem Cultural</b> da região. Afinal, suas construções, estabelecimentos humanos, usos da terra e do mar, tradições culturais, entre outros aparatos culturais, e que foram posteriormente patrimonializados, são consequências de determinadas condições naturais ideais, particularmente das geológicas e geomorfológicas, para a criação do trabalho humano, que resultou na expansão urbana de João Pessoa.</p>
        <p> Nesse link ao lado você sera redirecionado para uma página que contém dois artigos onde falará mais sobre o assunto.</p>
        </>
    )
}

export default ENCronistas