import solo from './media/solo.jpg'

function ENSolo(){
    return(
        <>
        <p className="paragraphy">A atuação e a inter-relação entre os agentes exógenos, que esculpiram e modelaram as estruturas rochosas, geraram, por meio do intemperismo, especificamente do intemperismo químico, características específicas de solos. A <b>pedogênese</b>, assim como a participação dos efeitos do clima, tem relação direta com a cobertura vegetal, e pode ser potencializada pela ação antrópica. Assim sendo, por estarem inseridos no geopatrimônio da área, é pertinente sua classNameificação e caracterização.</p>
        <p className="paragraphy">A nova <b>ClassNameificação Brasileira de Solos</b>, realizada pela Empresa Brasileira de Pesquisa Agropecuária (Embrapa) foi iniciada em 1979 e em 1999 foi divulgada a 1ª edição da classNameificação, em 2006 a 2ª edição e, em 2013, a 3ª edição, tendo sido baseada no Sistema Americano, a partir de modificações por Thorp e Smith (1949). Segundo Jacomine (2009)</p>
        <div className="paragraphy-modifded">
            <p><i>o sistema é morfogenético, multicategórico, descendente, aberto e de abrangência nacional. Em se tratando de uma classNameificação moderna, ela se baseia em propriedades (atributos) e horizontes diagnósticos. O Sistema Brasileiro compreende 6 níveis categóricos, compreendendo 13 classNamees no 1º nível (ordens). Seguem–se os seguintes níveis: 2º nível (subordens), 3º nível (grandes grupos), 4º nível (subgrupos), 5º nível (famílias) e 6º nível (séries). As 13 classNamees do 1º nível categórico são: Argissolos, Cambissolos, Chernossolos, Espodossolos, Gleissolos, Latossolos, Luvissolos, Neossolos, Nitossolos, Organossolos, Planossolos, Plintossolos e Vertissolos (JACOMINE, 2009, p. 161).</i></p>
        </div>
        <p className="paragraphy">Convém salientar que para a área do projeto há uma escassez de trabalhos científicos que apresentam dados sobre os tipos de solos. A mais recente proposta de mapeamento dos solos data de 2004 e foi executada para todo o Estado da Paraíba, na escala 1: 500.000, constituindo o Mapa Pedológico do Estado da Paraíba (PARAÍBA, 2004a), do qual a porção oriental corresponde à área deste projeto (figura 1). Segundo esta classNameificação, na área de pesquisa, são encontrados as seguintes ordens e sub-ordens de solos: podzólico vermelho-amarelo, podzol hidromórfico, gley, aluviais e areias quartzosas marinhas. Entretanto, a nomenclatura utilizada por este projeto do Governo do Estado difere daquela da Embrapa, o <b>Sistema de ClassNameificação dos Solos</b>, em sua 3ª edição, datada de 2013 (EMBRAPA, 2013), considerada oficial pelos estudiosos de pedologia. No Apêndice F da 3ª edição, portanto, há uma proposta de conversão das antigas classNameificações para a atual, que será utilizada neste projeto. Segundo este apêndice, o solo Podzólico Vermelho-Amarelo será convertido para Argissolo Vermelho-Amarelo; Podzol Hidromórfico para Espodossolo; Gley para Gleissolo e Solos Aluviais-Areias Quartzosas Marinhas para Neossolos Flúvicos e Quartzarênicos, respectivamente.</p>
        <div className="text-center">
            <figure className="figure">
                <a href={solo}><img src={solo} alt="" className="img-fluid" /></a><br />
                <figurecaption className="figure-caption">Figura 1 - Mapa Pedológico da Paraíba, setor oriental, com a área da tese (em vermelho). Fonte: Paraíba (2004a), com modificação a partir de Furrier (2007, p. 69).</figurecaption>
            </figure>
        </div>
        <h3>Caracterização das classNamees de solos</h3>
        <p className="paragraphy">Existe uma relação clara entre os tipos de solos e o relevo na área estudada. Os solos do tipo Argissolo e Espodossolo se desenvolvem sobre os sedimentos areno-argilosos Plio-pleistocênicos da <b>Formação Barreiras</b>, portanto, possuem as maiores altitudes, associados aos tabuleiros litorâneos; nas planícies fluviais encontram-se solos do tipo Gleissolo e Neossolo Flúvico; as planícies flúvio-marinhas apresentam solos do tipo Indiscriminado de Mangue e; nas planícies marinhas predominam os Neossolos Quartzarênicos.</p>
        <p className="paragraphy">Os <b>Argissolos Vermelho-Amarelos (PV)</b> apresentam desenvolvimento de horizonte B textural, localizado imediatamente abaixo de qualquer horizonte superficial, com incremento do teor de argila da superfície para o horizonte B e com baixa atividade da fração argila. Possuem coloração vermelho-amarelada e são bastante ácidos (EMBRAPA, 2013). É o mais abundante tipo de solo da área, associado aos arenitos Plio-pleistocênicos da <b>Formação Barreiras</b>.</p>
        <p className="paragraphy">Os <b>Espodossolos (HP)</b> desenvolvem um horizonte B espódico (espodos - cinza vegetal), hidromórfico em sequência a um horizonte eluvial E ou A. O horizonte A possui coloração cinzenta a preta e o horizonte E, acinzentada a praticamente branca. O horizonte espódico varia de um cinzento, escuro a preto, até um vermelho ou amarelo, sendo relativamente espesso. Por serem provenientes de materiais quartzoarenosos, sua textura é predominantemente arenosa, com baixa fertilidade, e ácidos, podendo ocorrer altos teores de alumínio. Estão associados a ambientes úmidos, relevos planos a suavemente ondulados (EMBRAPA, 2013), como os tabuleiros litorâneos. Ocorrem em pequenas manchas na restinga de Cabedelo e na retaguarda das falésias das praias de Carapibus e Jacumã.</p>
        <p className="paragraphy">Os <b>Gleissolos (HGd)</b> se caracterizam por um forte processo de gleização-hidromorfismo, resultante da flutuação do lençol freático, que encharca os solos. Típicos de um ambiente redutor, que reduz os compostos de ferro na presença de matéria orgânica, estão associados à proximidade dos cursos d’água, como é o caso da área de estudo. O resultado é o de solos acinzentados, esverdeados ou azulados, formados por sedimentos inconsolidados, de fração argila a areia (EMBRAPA, 2013). Na área de estudo, estão relacionados ao médio curso do rio Gramame e Abiaí.</p>
        <p className="paragraphy">Assim como os gleissolos, os <b>Neossolos Flúvicos (Ae)</b> estão associados às planícies aluviais, sendo originados sobre sedimentos fluviais recentes, apresentando, portanto, um horizonte glei. Entretanto, são solos pouco desenvolvidos, cujos agentes pedogenéticos atuaram de maneira menos intensa ou em que o material litificado possui maior resistência ao intemperismo. Assim, não são muito espessos, mas a presença de matéria orgânica os torna relativamente férteis. Devido à ausência do horizonte B, o horizonte A assenta diretamente sobre o C (EMBRAPA, 2013). Na área de estudo, ocorrem essencialmente ao longo das planícies fluviais do rio Cuiá e em alguns afluentes do Rio Gramame, não atingidos pela influência das marés.</p>
        <p className="paragraphy">Os <b>Solos Indiscriminados de Mangue (SM)</b> são solos halomórficos muito pouco desenvolvidos, lamacentos, salinos, com deposição de sedimentação flúvio-marinha em ambiente de baixa energia, misturada com detritos orgânicos, oriundos da atividade biológica local. Constantemente alagados, influenciados pelas marés, possuem textura arenosa a argilosa. Não constam em nenhuma edição do <b>Sistema Brasileiro de ClassNameificação de Solos</b> da Embrapa, por não apresentarem horizonte diagnóstico, tendo sido classNameificados como ‘Tipos de Terreno’ (NETO e SILVA, 2015). Na área de estudo, localizam-se nas planícies fluviomarinhas dos principais rios, sendo que os maiores depósitos estão associados ao Rio Paraíba e ao Rio Gramame.</p>
        <p className="paragraphy">Os <b>Neossolos Quartzarênicos (AMd)</b> são solos com textura arenosa em todos os horizontes, apresentando 95% de quartzo na sua composição, extremamente resistentes ao intemperismo, daí sua baixa profundidade e ausência de minerais alteráveis. Sem diferenciação em horizontes, inexiste um contato lítico no primeiro meio metro de profundidade (EMBRAPA, 2013). Na área de estudo, aparecem na planície costeira, que se alarga a partir da praia de Cabo Branco em direção a Cabedelo, atingindo sua máxima largura na Restinga de Cabedelo, onde dividem o espaço com os solos de mangue.</p>
        <p className="paragraphy">A caracterização pedológica da área tornou-se pertinente, uma vez que os solos que possuam valor científico, estético, cultural, funcional e econômico, pensando-se no seu uso geoturístico, foram identificados como Locais de Interesse e avaliados do ponto de vista qualitativo e semiquantitativo, para sua posterior inserção, ou não, nas rotas geoturísticas, que são um dos objetivos deste trabalho.</p>

        </>
    )
}

export default ENSolo