import aguadoce from '../media/aguadoce.png'



export function Aguadoce(){
    return(
        <>
        <p class="paragraphy">As <b>fontes de água doce</b> brotam por toda a área do projeto, e algumas, em especial as localizadas no Centro Histórico, foram extremamente importantes pelo seu conteúdo histórico e econômico, visto que abasteceram, durante séculos, a população da nascente cidade de Nossa Senhora das Neves. A descrição da qualidade e das características dos recursos hídricos, entre eles as fontes de água doce da Capitania da Parahyba, remonta aos primórdios do período colonial. Sem água potável, era inviável a fixação e evolução de um sítio urbano e, no caso de João Pessoa, não foi diferente, conforme ficou registrado nos documentos históricos.</p>
        <p class="paragraphy">Assim, algumas fontes em especial se destacam nestes documentos, pois são verdadeiros patrimônios hidrológicos, configurando-se em <b>hidrossítios</b>, aqui classificados como Locais de Interesse. Priorizar-se-ão características específicas destes locais, como os aspectos naturais, envolvendo geologia e geomorfologia, informações históricas da sua importância para a evolução urbana e aspectos litológicos da edificação anexa às fontes, se houver, mas que serão detalhadas na inventariação destes Locais. Neste caso, destacam-se a Fonte de Tambiá, Bica da Maria Feia, Cacimba do Povo, Santo Antônio e Fonte dos Milagres, todas localizadas no centro de João Pessoa. Outras fontes principais importantes são a Cacimba<sup>1</sup>  da Jaqueira e Gravatá, analisadas a seguir.</p>
        <p class="paragraphy">De acordo com a figura 1, que localiza as fontes no Centro Histórico, pode-se visualizar que todas as fontes ocupam posições marginais em relação à cidade, nas vertentes voltadas, principalmente para o Rio Sanhauá, tendo relação direta com o plano de falha normal<sup>2</sup>  que expôs os arenitos que servem como aquíferos às fontes, assim como os calcários em contato subjacente a eles, em altitudes que variam entre 16 e 22 metros. São exceções as Fontes de Tambiá e da Bica da Maria Feia, que estão na vertente voltada para o Rio Tambiá Grande. Como será visto adiante, o tempo e a ação humana se encarregaram de fazer desaparecer parte significativa deste patrimônio cultural e hidrológico.</p>
        <p class="paragraphy">As características litológicas da <b>Formação Barreiras</b> (Plio-pleistocênica), aliadas à topografia plana favorecem a infiltração das águas em detrimento de seu escoamento. A posterior concentração de soluções e colóides no horizonte iluvial favorece a gênese de níveis endurecidos e, portanto, impermeáveis, em subsuperfície no solo dos tabuleiros, que tem relação com a gênese da arenização do Barreiras. Este horizonte de fragipan acaba por reter as águas que infiltram, formando um aquífero suspenso, o aquífero Barreiras, que tem relação também com as áreas de cabeceiras de drenagem de várias bacias (a exemplo da Balaustrada das Trincheiras), com algumas fontes (como a de Tambiá e Maria Feia), onde os níveis arenosos interceptam as vertentes, bem como a Dolina dos Irerês. No contato da <b>Formação Barreiras</b> com o calcário Maastrichtiano da <b>Formação Gramame</b> forma-se um nível mais profundo do Aquífero Barreiras, desta vez ‘livre’, sendo que a Cacimba do Povo e as fontes de Santo Antônio e dos Milagres afloram no intercepto destas camadas com a vertente formada pela ‘Falha de Sanhauá’.</p>
        <div class="text-center">
            <figure class="figure">
                <a href={aguadoce}><img src={aguadoce} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figura 1 - Localização das principais fontes e algumas ruas e edificações na cidade da Paraíba, em 1913. Legenda: Símbolos (logradouros): 1-Ladeira de São Francisco; 2-Estrada de Mandacaru (atual Desemb. Botto Meneses); 3-Estrada de Tambaú (atual Mons. Walfredo Leal); 4-Rua da Gameleira (atual Des. Trindade); 5-Ladeira da Borborema; 6-Rua da Tesoura (atual Rua Vidal de Negreiros); 7-Rua da Lagoa da Frente (atual Rua 13 de maio); 8-Rua da lagoa de trás (atual Rua Nova da Lagoa); 9-Caminho da Cacimba do Povo (atual Rua Rodrigues Chaves); 10-Rua das Trincheiras; 11-Rua da Palmeira (atual Rua Rodrigues de Aquino). Círculos azuis (edificações): A-Igreja de Santo Antônio; B-Igreja Matriz; C-Igreja de São Bento; D-Igreja do Carmo; E-Novo Hospital da Santa Casa em construção (atual Hospital Santa Isabel); F-Quartel da Polícia; G-Santa Casa da Misericórdia; H-Igreja da Conceição; I-Igreja do Bom Jesus. Triângulos vermelhos (fontes/cacimbas): a-Fonte dos Milagres; b-Fonte de Santo Antônio; c - Fonte de Tambiá; d-Bica da Maria Feia; e-Cacimba da Jaqueira; f-Fonte de Gravatá; g-Cacimba do Povo. Fonte: SOUSA e VIDAL (2010) apud ARAÚJO (2012).</figurecaption>
            </figure>
        </div>
        <hr />
        <span>
            <sup>1</sup>A cacimba é uma denominação dada aos corpos d’água que afloram a partir da abertura de poços rasos com a utilização de pás ou picaretas.
            <sup>2</sup>Segundo Leinz e Amaral (2001), podem ser classificadas como ‘fontes de falha’
        </span>
        </>
    )
}