import introclima1 from '../media/introclima1.png';
import introclima2 from '../media/introclima2.png';



export function Introduçãohidro(){
    return(
        <>
            <p class="paragraphy">A água, enquanto elemento da geodiversidade e elemento geopatrimonial, será abordada através de duas feições: os <b>aspectos fluviais</b> e as <b>fontes de água doce</b>. Sempre que possível, tentar-se-á correlacionar estes aspectos com a geomorfologia, a geologia, a tectônica e os problemas ambientais envolvidos com a antropização, servindo como embasamento para, posteriormente, analisá-los por meio de uma visão patrimonial, visando inseri-los no roteiro geoturístico. Assim, o detalhamento destas feições dar-se-á no caso daquelas que foram selecionadas como Local de Interesse, estando presente no inventário do capítulo 8.</p>
            <p class="paragraphy">Foram executadas saídas de campo entre fevereiro e maio de 2016 no litoral da área de estudo, visando a observação <i>in situ</i> dos fenômenos relacionados com a geodiversidade, além de análise aerofotogramétrica e de imagens orbitais e pesquisa bibliográfica, relativamente escassa para o sujeito em questão, assim como das fontes inseridas no Centro Histórico, com o objetivo posterior de valoração para fins geopatrimoniais.</p>
            <p class="paragraphy">Organizando a área do ponto de vista das bacias hidrográficas, de acordo com a classificação proposta pelo Departamento Nacional de Águas e Energia Elétrica (DNAEE), a área de pesquisa insere-se totalmente na <b>Bacia Hidrográfica do Atlântico Nordeste</b> (IBIAPINA et al., 1999). Pensando-se em escala estadual, por sua vez, utilizou-se a proposta da Agência Executiva de Gestão das Águas do Estado da Paraíba (AESA). A área do projeto é drenada por três bacias maiores: curso inferior da Bacia da Paraíba; porção oriental da Bacia do Rio Gramame; e porção oriental da Bacia do Rio Abiaí, além de algumas microbacias adjacentes.</p>
            <p class="paragraphy">Além dessas bacias, alguns cursos d’água formam microbacias que desaguam no Oceano Atlântico e que foram inseridas nas bacias anteriormente citadas. Seguindo o conceito de <b>bacia hidrográfica</b><sup>1</sup> , optamos por desmembrá-las destas bacias e agrupá-las em duas bacias secundárias, aqui denominadas <b>Bacias Secundárias de João Pessoa</b> e <b>Bacias Secundárias do Litoral Sul Paraibano</b>, separadas pela Bacia do Rio Gramame, conforme pode ser visto na figura 1. A tabela 1 resume as principais microbacias e sub-bacias inseridas na malha urbana de João Pessoa ou na sua periferia, assim como seus principais rios e riachos e a dimensão, em Km<sup>2</sup>.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={introclima1}><img src={introclima1} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Figura 1 - Bacias hidrográficas na área da tese, delimitada em vermelho.</figurecaption>
                </figure>
            </div>
            <div class="text-center">
                <figure class="figure">
                    <figurecaption class="figure-caption">Tabela 1 - Microbacias e sub-bacias de João Pessoa, com seus principais tributários e área total, em Km<sup>2</sup>.</figurecaption>
                    <a href={introclima2}><img src={introclima2} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Fonte: SEPLAN (2007).</figurecaption>
                </figure>
            </div>
            <h3>Bacia do Rio Paraíba-baixo curso</h3>
            <p class="paragraphy">O Rio Paraíba, também conhecido como Rio Paraíba do Norte, é o principal rio da bacia homônima e o mais extenso rio totalmente paraibano. A Bacia do Rio Paraíba é a segunda maior bacia paraibana, inferior à Bacia do Rio Piranhas.</p>
            <p class="paragraphy">Possui uma área de cerca de 20 mil Km<sup>2</sup>, banhando 38% da área do Estado, tendo como coordenadas limites 6º51’47” - 8º18’12” de lat. Sul e 34º47’37” - 37º21’22” de long. Oeste. É composta pela sub-bacia do Rio Taperoá e, geograficamente, subdivida em Alto, Médio e Baixo Curso. É seu baixo curso que banha os municípios de João Pessoa e Cabedelo, inseridos na área deste projeto. Assim, por banhar também o município de Campina Grande, segundo município do Estado, esta bacia possui a maior densidade demográfica do Estado, inserindo mais da metade da população paraibana<sup>2</sup>.</p>
            <p class="paragraphy">O Rio Paraíba é o mais extenso rio totalmente paraibano, nascendo na Serra de Jabitacá, município de Monteiro, a mais de mil metros de altitude, numa das áreas mais secas do país, pertencente ao ‘Polígono das Secas’, na microrregião do Cariri paraibano (LACERDA, 2003). Para atingir sua foz, que limita os municípios de Cabedelo, João Pessoa, Santa Rita, Bayeux e Lucena, percorre 380 Km e várias unidades geomorfológicas e climas distintos, além de três mesorregiões<sup>3</sup>.</p>
            <p class="paragraphy">Neste percurso, o Rio Paraíba sofre vários problemas ambientais e antrópicos. Pelo fato de nascer em uma região árida, boa parte da bacia possui caráter intermitente, o que obrigou várias gestões governamentais a construírem açudes e represas, como o Açude Epitácio Pessoa, em Boqueirão, responsável por abastecer o município de Campina Grade, o segundo maior centro urbano do Estado (CUNHA, 1998). Entretanto, segundo a AESA (2009), a capacidade de armazenamento hídrico nestes açudes é superior a um bilhão de m<sup>3</sup>, cujas barragens alteram a sua dinâmica fluvial, resultando em um maior espaçamento das inundações ao longo de seu curso (SILVA, 2003), inundações estas que atingem seu estuário desde que os primeiros registros de ocupação colonial passaram a ser documentados, ou seja, no século XVII.</p>
            <p class="paragraphy">Um outro problema que ocorre em seu médio e alto curso e que acaba por afetar seu estuário é o processo de assoreamento, resultado de práticas agrícolas inadequadas, associadas ao cultivo de cana de açúcar e ao intenso desmatamento de suas matas ciliares. Grandes volumes de sedimentos chegam ao baixo curso do rio, muito deles provenientes da erosão de encostas nas redondezas, e se depositam à medida que a capacidade fluvial diminui. O resultado é a acumulação destes sedimentos, formando bancos de areia, ilhotas, reduzindo a largura e profundidade do rio e tornando suas águas mais turvas.</p>
            <p class="paragraphy">O estuário do Rio Paraíba possui cerca de 22 Km, da sua foz, em Cabedelo, até a ponte do Rio Sanhauá, em João Pessoa. Seus principais afluentes da margem esquerda são os Rios Portinho, Tiriri, Ribeira e da Guia, todos fora da área do projeto. Os tributários da margem direita, já na área do trabalho, são o Rio Sanhauá-Marés, Paroeira e Mandacaru (SUDENE, 1974). O Rio Jaguaribe, que forma uma das principais microbacias urbanas de João Pessoa, deságua no Rio Mandacarú, um tributário da margem direita do Rio Paraíba e, portanto, será considerado uma sub-bacia da Bacia da Paraíba em seu baixo curso.</p>
            <h3>Sub-bacia do Rio Marés-Sanhauá</h3>
            <p class="paragraphy">No encontro do Rio do Meio e Marés, forma-se o Rio Sanhauá. Este rio tangencia a cidade baixa de João Pessoa, no centro histórico, por cerca de 8 Km, enquanto molda os tabuleiros a leste, servindo de fronteira natural, juntamente com o Rio Marés, entre João Pessoa e Bayeux, a oeste, desaguando no Rio Paraíba (COSTA, 2009). Seu principal problema foi ter recebido, entre 1957 e 2003, efluentes do <b>lixão do Roger</b>, localizado nas proximidades de seu baixo curso. Corresponde a uma área com uma rede de drenagem relativamente pobre, apesar dos entalhes denudacionais do Rio Marés serem relativamente intensos, resultando em declividades das vertentes acentuadas (FURRIER, 2007).</p>
            <p class="paragraphy">O aperto de mãos entre o líder Piragibe e João Tavares, representando a Coroa Portuguesa, que selou o acordo de paz e propiciou, posteriormente, a fundação da cidade de Nossa Senhora das Neves, se deu às margens do Rio Sanhauá, daí sua importância não apenas ecológica- ambiental, mas histórica.</p>
            <p class="paragraphy">No geral, ambos os rios são relativamente lineares, com direção de fluxo predominantemente SW- NW e escarpas pouco sinuosas. Barbosa e Furrier (2012) realizaram avaliação morfológica e morfométrica no Rio Marés, concluindo que a configuração do relevo apontou para evidências de atividades neotectônicas. Ambos os rios são caracterizados como do tipo subsequente, corroborada por Andrades Filho (2010), que estudou a sub-bacia através de técnicas de sensoriamento remoto, sugerindo que esta região foi afetada por falhas neotectônicas, de idade Quaternária.</p>
            <hr />
            <span>
                <sup>1</sup>Complexo de áreas drenadas por um rio e seus afluentes, as bacias hidrográficas podem ser consideradas como, principal, secundária e terciária, podendo ser ainda, dependendo de seus subafluentes, como litorâneas, centrais ou interiores (GUERRA, 1987).<br />
                <sup>2</sup>AESA. Comitê Rio Paraíba. Extraído de <a href="http://www.aesa.pb.gov.br/comites/paraiba/">http://www.aesa.pb.gov.br/comites/paraiba/</a>. Acesso em 15 fev 2015.<br />
                <sup>3</sup>Da nascente para a foz: Borborema, Agreste e Litoral.
            </span>
        
        </>
    )
}