export function Neotectonica(){
    return(
        <>
        <p class="paragraphy">A rede de drenagem da área é fortemente influenciada por falhas, cujo padrão predominantemente dendrítico, sobre o escudo cristalino, apresenta, comumente, deflexão ao longo das zonas de cisalhamento pré-cambrianas. Ao adentrar no terreno sedimentar, o padrão de drenagem se paraleliza às falhas de direção NE, o que sugere um controle tectônico (BEZERRA et al., 2001a; BARBOSA, 2007). A rede de drenagem que exuma os sedimentos Plio-pleistocênicos da <b>Formação Barreiras</b>, por vezes expondo as camadas sotopostas, forma um vale em V, cujos rios de maior porte, a exemplo dos Rios Paraíba, Abiaí e Gramame, formam planícies aluviais e fluviomarinhas bem desenvolvidas no fundo destes vales. Os diferentes níveis de entalhes fluviais podem ser considerados heranças das movimentações tectônicas que configuraram o terreno por onde estes rios passam.</p>
        <p class="paragraphy">O complexo estuarino do baixo Rio Paraíba com todos os seus afluentes tem associação com o Graben de João Pessoa. Segundo Barbosa e Lima Filho (2006) e Barbosa (2007), esta bacia está associada à exposição e erosão dos calcários Maastrichtianos da <b>Formação Gramame</b> e ao seu fraturamento. O Rio Paraíba, que flui retilineamente no seu baixo curso na direção NE-SW, abruptamente faz uma flexão para a direção N-S, nas proximidades de João Pessoa, daí atingindo o litoral, tendo sido selecionado como um Local de Interesse (Praia do Jacaré). A importância de fenômenos neotectônicos pode ser visualizada analisando-se a configuração de certos rios da malha hidrográfica da área, através da qual apresentamos alguns exemplos a seguir.</p>
        <p class="paragraphy">No litoral sul, por meio da análise de dados digitais de elevação adquiridos pelo SRTM, integrada ao trabalho de campo, Rossetti et al. (2009) analisaram o comportamento da rede de drenagem da sub-bacia Alhandra, assim como dos sedimentos Barreiras que ela exuma, em relação às atividades neotectônicas que as influenciam. Os autores compartimentaram a sub-bacia em duas áreas: a primeira se estende da Depressão do Abiaí, extremo sul da área desta tese até o Rio Gramame, abrangendo os rios Guruji, Graú, Água Boa e Salsa; a segunda, um área que envolve a primeira, referente as bacias do Rio Gramame, a norte e Papocas-Taperubus, ao sul, fora da área desta tese.</p>
        <p class="paragraphy">O primeiro compartimento apresenta um maior grau de inclinação e um padrão de convexidade mais acentuada nos interflúvios do que o compartimento envolvente. Os rios da primeira área são retilíneos, com curvaturas em ângulos fechados, corroborando com o padrão dendrítico proposto por Bezerra et al. (2001a), enquanto a rede de drenagem do segundo compartimento apresenta rios que mudam bruscamente de direção, quase em ângulo reto, com um padrão de treliça recurvada, e com tributários retilíneos e curtos desaguando no rio principal em ângulo reto. Esta mudança no comportamento da rede hidrográfica possui relação com o ‘<b>Alto Estrutural Coqueirinho</b>’, feição estrutural mapeada por Furrier et al. (2006) e Furrier (2007), considerada nesta tese como um Local de Interesse devido, principalmente, ao seu alto valor estético e científico.</p>
        <p class="paragraphy">A direção geral da rede hidrográfica da <b>Bacia do Rio Gramame</b>, no sentido SW-NE faz pressupor que coincida com linhas de faturamento que possuem esta direção. A maior parte da bacia encontra-se inserida no domínio dos tabuleiros litorâneos, com exceção dos seus extremos oeste, sobre o embasamento cristalino e leste na planície costeira. Com uma extensão leste-oeste de cerca de 60 Km, nos baixos planaltos as altitudes variam a mais de 200 m até 30-40 m, neste mesmo sentido, porém fora da área de estudo, o que faz supor que haja um soerguimento do terreno na porção ocidental. Suas vertentes são alongadas, podendo variar de côncavas a predominantemente convexas bastante dissecadas, cujo desmatamento em suas bordas agrava fenômenos erosivos com o aprofundamento de sulcos e ravinas. No geral estreitos, podem apresentar alargamento de seus vales em algumas porções, com a formação de terraços fluviais e presença de depósitos coluviais, visíveis em aerofotogrametria.</p>
        </>
    )
}