import dominio1 from '../media/dominio1.jpg'
import dominio2 from '../media/dominio2.png'




export function ENDominios(){
    return(
        <>
            <p class="paragraphy">On a regional scale, Melo and Rodriguez (2003) proposed the division of the Paraiba relief into five geomorphological units, from east to west: <b>coastal lowland, low coastal plateaus, sublittoral depression/Curimatau/Lower Paraíba River, surface of Borborema and pediplano sertanejo</b> (with the Rio do Peixe Basin). The area of this thesis is fully inserted in the domain of coastal lowlands and in the domain of low plateaus or plateaus, as can be seen in figure 1.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={dominio1}><img src={dominio1} class="img-fluid" alt="" /></a><br />
                    <figurecaption class="figure-caption">Figure 1- Geomorphological units of Paraíba, with the delimitation of the thesis area in red. Modified from Melo and Rodriguez (2003).</figurecaption>
                </figure>
            </div>
            <h4>Domain of the coastal lowlands</h4>
            <p class="paragraphy">According to Melo and Rodriguez (2003), the <b>domain of the coastal lowlands</b> is up to 8 m high, with the exception of some dunes with more than 15 m. Quaternary deposits can be grouped into two depositional systems: continental and coastal. The <b>continental system</b> includes the deposits associated with the slopes, linked to the phenomena of generalized mass movements in past climatic conditions, but belonging to the Quaternary Period. The dejection cones, fluvial deposits, eluvium-colluvial and colluvial covers belong to this system.</p>
            <p class="paragraphy">The <b>coastal system</b>, coastal or marine transitional depositional, is the result of variation in the eustatic sea level, a result of paleoclimatic conditions and coastal hydrodynamic factors, such as wind, tides, waves and maritime currents, which occurred from the Pleistocene<sup>1</sup>. This system is represented by Pleistocene and Holocene marine terraces, fluviolagunar deposits, mangrove deposits in swamps, aeolian deposits, coral reefs, beach rocks and beach sands. The most representative features were selected as Place of Geotourism Interest.</p>
            <h4>Domain of the low coastal plateaus</h4>
            <p class="paragraphy">The <b>low coastal plateaus</b> are represented by plateaus, with flat or gently undulating tops that abruptly end, in the adjacent plains, in the form of relatively steep slopes. On the coastal plain, these slopes are called <b>cliffs</b>, which can be active or not, formed by the <b>Barreiras Formation</b> and interrupted by fluvial notches, in the form of open or embedded valleys. vast amphitheaters. They continue the sedimentary deposits of the coastal lowlands, with their beaches, terraces, river plains, dune fields, among others. The boards present, as previously mentioned, a gentle inclination to the east and average altitudes that reach 40 to 50 m and a distance of up to 40 km from the coastline. Occasionally, rainwater is captured in large volume by the low slope of the land, forming internal ducts along the stratification plans, which result in the opening of spaces forming small caves, such as the 'Grotto' das Tides, which was selected as a Place of Interest. This cave was excavated in the Plio-Pleistocene sandstones, claystones and siltstones of the <b>Barreiras Formation</b>, near the Mumbaba River, a left bank tributary of the Gramame River.</p>
            <p class="paragraphy">The entire coast of Paraíba has cliffs that can suffer marine abrasion or not. The <b>active cliffs</b>, or live, continue to receive the impact of waves on the tides of living waters and, therefore, the risk of collapse, such as the Cabo Branco cliff, which had part of it collapsed in January 2018 , is imminent, deserving special care and more drastic attitudes from the authorities. The road that connected Cabo Branco beach to the lighthouse, at the top of the cliff, was closed to reduce the pressure on the cliff, and access is currently provided by a path that surrounds it. The <b>inactive</b>, or dead, cliffs are more recessed on the continent, no longer suffering from marine undermining and are important indicators of past marine transgression. A Place of Interest was selected on each type of cliff (Falésias do Cabo Branco and Inativas Urbanas, respectively).</p>
            <p class="paragraphy">On the south coast, the eastern portion of the trays, in the vicinity of the cliffs, have scars from rain erosion, forming extensive gullies and ravines, while some cliffs, a little more set back, were taken by vegetation at their base, covering sediments that formed colluvial deposits . Both features, gullies/ravines and colluviums, were selected as Place of Interest (Coqueirinho Canyon and Dejeção Cones, respectively, on the southern coast of the state).</p>
            <p class="paragraphy">The heterogeneity of the cliffs, according to Neves (1993), is explained, above all, by the lithological differences of the <b>Barreiras Formation</b>. In general, its slopes should remain stable over time, despite wear and rounding of shapes as a result of the action of exogenous agents. However, anthropic action, in the form of deforestation and irregular occupation, among others, end up destabilizing these slopes, increasing erosive processes in the form of mass movements, such as soliflux and landslides, in addition to increasing the flow of rainwater, which aggravates the possibility of flooding.</p>
            <p class="paragraphy">Thus, the continental dynamics has a predominant role in the slopes of the river valleys, located in the interior of the area, resulting in different slopes and patterns, in this case, with the slopes varying from straight, convex, concave or with more than one pattern.</p>
            <p class="paragraphy">As mentioned in the previous chapter, the morphology of the low plateaus, forming highs and lows that intersperse in the terrain, generating a gently undulating surface, with a relatively flat top, is the result of fault events that have occurred since the Pliocene, configuring graben-like structures and horsts, which end abruptly at the coastline in the form of cliffs. This failed structure, with uplifts and deepening of blocks, can be corroborated, as mentioned above, through the analysis of drill cores taken from tubular wells, where the great variation in the levels of the Gramame limestone levels attests to this occurrence (ARAÚJO, 1993; LEAL E SÁ, 1998; BARBOSA, 2007). The trays are, therefore, a fragmented compartment that touches the coastline and was filled with sediments disposed at the rear of the coastal plain.</p>
            <p class="paragraphy">In various portions of the studied area, karst and anthropic geomorphological features are present. In the case of karst features, those of dissolution are the most common, such as sinkholes and lapias. Regarding the sinkholes, based on the analysis of aerial photographs and planaltimetric maps, it is possible to identify several portions of the municipality of João Pessoa that have subsidence of the land due to the dissolution of the Maastrichtian limestone of the <b>Gramame Formation</b>, along of fault plans that serve as a conduit for the percolation of surface waters, with the abatement of the Barreiras sediments and subsequent occupation of these sinks by low-income population, which, as a topographically depressed area, is susceptible to flooding in times of intense rain . Vital (2015), through field and office work, with Shuttle Radar Topography Mission (SRTM) radar images and topographic maps, obtained morphometric data on the dolines in the region, establishing genetic relationships between these and the present tectonic lineaments, as well as relationships between superficial depressions and buried depressions were indicated, with the detection of dissolution features, along discontinuity planes, associated with the occurrence of epikarst. An example of a mapped sinkhole is located near the Oitizeiro Viaduct, called Três Lagoas, which has a direct connection with the source of the River Jaguaribe. However, the most imposing of these sinkholes, selected as a Place of Interest and therefore evaluated, was the Dolina dos Irerês, in the center of João Pessoa, which is part of the current Solon de Lucena Park.</p>
            <p class="paragraphy">Fields of lapiás outcrop in several portions of the study area, showing the carbonate origin of part of the terrains in the Paraíba Basin. The most interesting features of this type are those that outcrop between the beaches of Tambaba and Tabatinga, having also been selected as a Place of Interest (Tambaba and Pedra do Amor Beach, on the south coast) and subsequently evaluated.</p>
            <p class="paragraphy">The most common anthropogenic features are limestone mines, anthropogenic lagoons and carcinogenic ponds.</p>
            <p class="paragraphy">Figure 2 represents the geological-geomorphological map of the area, depicting the present lithostratigraphic units and the main structural features mapped at this scale, as well as idenfies the coastal relief forms, considering the 5th, 6th and 7th orders of taxonomic magnitude, with the delimitation of all selected Places of Interest for qualitative and semi-quantitative assessment.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={dominio2}><img src={dominio2} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Figure 2 - Geological-geomorphological map of the thesis area, with the demarcation of Places of Geotourism Interest. Prepared by the author.</figurecaption>
                </figure>
            </div>
        </>
    )
}