import mapeamento from '../media/mapeamento.jpg'


export function ENMapeamento(){
    return(
        <>
        <p class="paragraphy" >Geomorphology, as indicated by the Greek roots of the word, is the science of the Earth's forms. Its object is, therefore, the study of relief forms in the earth's crust, the lithosphere (TRICART, 1965). However, the terrestrial surface presents a great diversity of forms that obliges, when we systematize this study, to go through a vast path of observations, interpretations, correlations and analyses, through a multiscalar reasoning, making this task extremely complex.</p>
        <p class="paragraphy" >The objective of this subchapter is to insert the project area in a geomorphological context, with the purpose of a further evaluation of potential geomorphosites for geotouristic use as a Place of Interest, while possessing heritage value.</p>
        <p class="paragraphy" >The relief forms of the eastern northeast coast are the result of the action of endogenous and exogenous agents that acted together, but with different weights. As seen in the previous chapter, tectonics and especially neotectonics played a fundamental role in the configuration of the coastal relief, while exogenous agents, such as marine regressions and transgressions, current and past climates, rivers, wind, agents biological and anthropic, among others, shaped and formed the beautiful existing relief forms whose description, <i>per se</i>, is not sufficient for a complete understanding of their emergence and evolution.</p>
        <p class="paragraphy" >The study of relief forms presupposes a complete understanding of the causes that led to its current form, internal and external causes, their consequences, including for the fixation of the human being, in addition to the type of material involved in these evolutionary processes. Thus, Marinho (1995) proposes that relief forms can be examined under four approaches: morphology, morphogenesis, morphodynamics and morphochronology. For this thesis, however, the relief morphology will be emphasized, where the variables have a more direct application in studies focused on land planning and use (FLORENZANO, 2008), in this case the practice of geotourism. Morphogenesis, morphodynamics and morphochronology will be considered, however, as ancillary concerns.</p>
        <p class="paragraphy" >The morphology of relief forms encompasses two fields: morphography and morphometry. Considering that the role of geomorphological mapping for this thesis aims at its use for geotouristic purposes, the qualitative character of the terrain (morphography) will be emphasized, relegating the quantitative character to the background (morphometry), despite being a relevant concern.</p>
        <p class="paragraphy" >Both categories of approach were disclosed by Tricart (1965). According to the author, the relief forms, as well as their materials, ages and processes are represented in a flat medium called ´<b>geomorphological chart</b>´, which Tricart (1965, p. 83) considers as “the base of research and not the graphic realization of the research already carried out”. It should be noted that Ross (1990, p. 69) argued that geomorphological cartography was so far concerned with the general content of what was being represented, regardless of the way in which this representation was being made, lacking a standardization or uniformity of the cartographic representation, " satisfying the different interests of geomorphological studies”. On the other hand, Abreu (1982, p. 66) emphasizes that geomorphological cartography must present a result that makes it possible to “understand the essence of its dynamics and acquired properties”, whereby the form represents the maximum expression of this dynamic responsible for morphogenesis in the earth's crust.</p>
        <p class="paragraphy" >The question of scale had already been discussed by Cailleux and Tricart (1956) apud Gouveia (2010) and Tricart (1965). According to the authors, small-scale geomorphological charts (above 1:500,000) would be favorable for the representation of morphostructural features, such as anticlines, resulting from folding, grabens and horsts, among others, features corresponding to the 4th and 5th order of magnitude, with areas of 102 Km2 and 10 Km2, respectively, while large-scale charts, type 1:5,000 to 1:25,000, for example, would be suitable for mapping metric features, such as a field of lapias or a gully<sup> 1</sup>, corresponding to the 6th order of magnitude (10-2 Km2). Thus, this selected methodology was conditioned to the objectives previously outlined in this thesis, whose framing falls between the 4th and the 7th unit of magnitude. These taxonomic units are summarized in Table 1.</p>
        <div class="text-center">
        <figure class="figure">
            <figurecaption class="figure-caption">The question of scale had already been discussed by Cailleux and Tricart (1956) apud Gouveia (2010) and Tricart (1965). According to the authors, the small-scale geomorphological maps (above 1: Table 1-Taxonomic classification of geomorphological facts).</figurecaption><br />
            <a href={mapeamento}><img src={mapeamento} class="img-fluid" alt="" /></a><br /><br />
            <figurecaption class="figure-caption">Source: Cailleux and Tricart (1956) apud Gouveia (2010, p. 45).</figurecaption>        
        </figure>
    </div>
        <p class="paragraphy" >The study of scientific literature on the geology and geomorphology of the area, added to the soil, climate, vegetation and other elements of nature, whether or not containing specialized maps, is one of the first steps in the methodological process of inventorying geodiversity and its geopatrimony .</p>
        <p class="paragraphy" >Traditional geological and geomorphological studies are aimed at collecting and interpreting information on the Earth's surface, such as shapes, materials, processes and age of formations. They are essential parts of the land recognition process and subsequent inventory of potential Places of Interest. It is important to deepen the understanding of the geology and geomorphology of the mapped area, whose maps, at a scale compatible with the interests of this project, through the cartographic representation of these features, provide geological and geomorphological data, even if synthetic, but fundamental for the preparation of the roadmap geotourism.</p>
        <p class="paragraphy" >In the case of geopatrimonial studies, traditional geological and geomorphological maps can enhance projects for the assessment, planning and administration of geosites and geomorphosites, respectively, and may extend this possibility to other heritage elements, such as paedosites and hydrosites, in order to assess the values of natural resources, disseminate scientific knowledge to the general or specialized public and/or prevent risks of accidents in risk areas. Thus, the resulting maps are clearly different from the traditional ones, and their elaboration methodology is being tested in several European countries (such as CARTON et al., 2005, CORATZA and REYNARD, 2005, among others), and in which the databases and GIS technologies, such as 3D images, are key pieces.</p>
        <p class="paragraphy" >In the case of this thesis, whose mapping aimed at urban and coastal geotourism, some geological features and relief forms included in these maps, with clear geotouristic potential, which have heritage value, were inventoried and evaluated semiquantitatively. The resulting map differed from those commonly presented, as it presented specific information, whether geoscientific or tourist, in a variable proportion, with visual language, level of simplification of scientific information, linked to information about the hotel and bar/restaurant infrastructure, road structures , parking lots, among others.</p>
        <hr />
        <span>
            <sup>1</sup>Gullies will be distinguished from ravines by the presence of the water table rising at the end of the channel, in the case of the first ones (GUERRA, 1987).
        </span>
        </>
    )
}