import mapeamento from '../media/mapeamento.jpg'


export function ENMapeamento(){
    return(
        <>
        <p class="paragraphy" >A Geomorfologia, tal como o indicam as raízes gregas da palavra, é a ciência das formas da Terra. O seu objeto é, portanto, o estudo das formas de relevo da crosta terrestre, da litosfera (TRICART, 1965). Entretanto, a superfície terrestre apresenta uma grande diversidade de formas que obriga, ao sistematizarmos este estudo, a percorrermos um vasto caminho de observações, interpretações, correlações e análises, por meio de um raciocínio multiescalar, tornando esta tarefa em algo extremamente complexo.</p>
        <p class="paragraphy" >O objetivo deste subcapítulo é o de inserir a área do projeto em um contexto geomorfológico, com o intuito de uma posterior avaliação de potenciais geomorfossítios para uso geoturístico como Local de Interesse, enquanto possuidores de valor patrimonial.</p>
        <p class="paragraphy" >As formas do relevo da costa oriental nordestina são o resultado da ação de agentes endógenos e exógenos que atuaram conjuntamente, mas com pesos distintos. Conforme visto no capítulo anterior, a tectônica e, especialmente, a neotectônica tiveram um papel fundamental na configuração do relevo litorâneo, enquanto os agentes exógenos, como as regressões e transgressões marinhas, os climas atuais e pretéritos, os rios, o vento, os agentes biológicos e antrópicos, entre outros, modelaram e formaram as belíssimas formas de relevo existentes cuja descrição, de <i>per se</i>, não é suficiente para um completo entendimento de seu surgimento e evolução.</p>
        <p class="paragraphy" >O estudo das formas de relevo pressupõe um entendimento completo das causas que levaram a sua atual forma, causas estas internas e externas, suas consequências, inclusive para a fixação do ser humano, além do tipo de material envolvido nestes processos evolutivos. Assim, Marinho (1995) propõe que as formas de relevo possam ser examinadas sob quatro vias: morfologia, morfogênese, morfodinâmica e morfocronologia. Para esta tese, no entanto, será enfatizada a morfologia do relevo, onde as variáveis têm uma aplicação mais direta em estudos voltados para o planejamento e uso da terra (FLORENZANO, 2008), neste caso a prática do geoturismo. A morfogênese, morfodinâmica e morfocronologia serão considerados, entretanto, como preocupações acessórias.</p>
        <p class="paragraphy" >A morfologia das formas de relevo abarca dois campos: morfografia e morfometria. Considerando que o papel do mapeamento geomorfológico para esta tese visa o seu uso para fins geoturísticos, enfatizar-se-á o caráter qualitativo do terreno (morfografia), relegando o caráter quantitativo para segundo plano (morfometria), apesar de ser uma preocupação relevante.</p>
        <p class="paragraphy" >Ambas as categorias de abordagem foram divulgadas por Tricart (1965). Segundo o autor, as formas de relevo, assim como seus materiais, idades e processos são representados em um meio plano denominado ´<b>carta geomorfológica</b>´, que Tricart (1965, p. 83) considera como “a base de pesquisa e não a concretização gráfica da pesquisa já feita”. Convém salientar que Ross (1990, p. 69) discutia que a cartografia geomorfológica até então se preocupava com o conteúdo geral do que estava sendo representado, independentemente da maneira como estava sendo feita esta representação, faltando uma padronização ou uniformização da representação cartográfica, “satisfazendo os diferentes interesses dos estudos geomorfológicos”. Por outro lado, Abreu (1982, p. 66) ressalta que a cartografia geomorfológica deve apresentar um resultado que possibilite “compreender a essência de sua dinâmica e das propriedades adquiridas”, pelo que, a forma representa a máxima expressão desta dinâmica responsável pela morfogênese na crosta terrestre.</p>
        <p class="paragraphy" >A questão da escala já havia sido discutida por Cailleux e Tricart (1956) apud Gouveia (2010) e Tricart (1965). Segundo os autores, as cartas geomorfológicas de pequena escala (acima de 1: 500.000), seriam favoráveis para a representação de feições morfoestruturais, como anticlinais, resultantes de dobramentos, grabens e horsts, entre outros, feições estas correspondentes à 4ª e 5 ordem de grandeza, com áreas de 102 Km2 e 10 Km2, respectivamente, enquanto as cartas com grande escala, tipo 1:5.000 a 1:25.000, por exemplo, seriam propícias a mapear feições métricas, como um campo de lapiás ou uma voçoroca<sup>1</sup>, correspondente à 6ª ordem de grandeza (10-2 Km2). Desse modo, esta metodologia selecionada foi condicionada aos objetivos previamente delineados nesta tese, cujo enquadramento se insere entre a 4ª e a 7ª unidade de grandeza. Essas unidades taxonômicas estão resumidas no Quadro 1.</p>
        <div class="text-center">
        <figure class="figure">
            <figurecaption class="figure-caption">Quadro 1-Classificação taxonômica dos fatos geomorfológicos.</figurecaption><br />
            <a href={mapeamento}><img src={mapeamento} class="img-fluid" alt="" /></a><br /><br />
            <figurecaption class="figure-caption">Fonte: Cailleux e Tricart (1956) apud Gouveia (2010, p. 45).</figurecaption>        
        </figure>
    </div>
        <p class="paragraphy" >O estudo de bibliografia científica acerca da geologia e geomorfologia da área, somada à do solo, clima, vegetação e de outros elementos da natureza, contendo ou não mapas especializados, é um dos primeiros passos do processo metodológico de inventariação da geodiversidade e de seu geopatrimônio.</p>
        <p class="paragraphy" >Os estudos geológicos e geomorfológicos tradicionais são voltados à coleção e interpretação de informações na superfície da Terra, como formas, materiais, processos e idade das formações. São partes primordiais do processo de reconhecimento do terreno e posterior inventariação dos potenciais Locais de Interesse. É importante aprofundar o entendimento da geologia e geomorfologia da área mapeada, cujos mapas, a uma escala compatível com os interesses deste projeto, através da representação cartográfica destas feições, fornece dados geológicos e geomorfológicos, mesmo que sintéticos, mas fundamentais para a elaboração do roteiro geoturístico.</p>
        <p class="paragraphy" >No caso de estudos geopatrimoniais, os mapas geológicos e geomorfológicos tradicionais podem potencializar projetos de avaliação, planejamento e administração dos geossítios e geomorfossítios, respectivamente, podendo estender esta possibilidade a outros elementos patrimoniais, a exemplo de pedossítios e hidrossítios, com o intuito de avaliar os valores dos recursos naturais, disseminar conhecimento científico para o público geral ou especializado e/ou prevenir riscos de acidentes em áreas de risco. Assim, os mapas resultantes são claramente diferentes dos tradicionais, e a sua metodologia de elaboração está sendo testada em vários países da Europa (a exemplo de CARTON et al., 2005, CORATZA e REYNARD, 2005, entre outros), e em que os bancos de dados e as tecnologias dos SIGs, como imagens 3D, são peças fundamentais.</p>
        <p class="paragraphy" >No caso desta tese, cujo mapeamento visou o geoturismo urbano e costeiro, algumas feições geológicas e formas de relevo inseridas nestas cartas, com claro potencial geoturístico, que possuam valor patrimonial, foram inventariadas e avaliadas semiquantitativamente. O mapa resultante se diferenciou dos comumente apresentados, pois apresentou informações específicas, sejam geocientíficas ou turísticas, numa proporção variável, com linguagem visual, nível de simplificação das informações científicas, atrelada às informações acerca da infraestrutura hoteleira e de bares/restaurantes, estruturas viárias, estacionamentos, entre outras.</p>
        <hr />
        <span>
            <sup>1</sup>Voçorocas serão diferenciadas de ravinas pela presença do nível freático aflorando no findo do canal, no caso das primeiras (GUERRA, 1987).
        </span>
        </>
    )
}