import { Navbar } from "../../../../components/EN/Navbar";
import dolina_1 from "./media/dolina_1.png";
import dolina_2 from "./media/dolina_2.png";
import "../1/index.css";

export function Dolina(){
    return(
        <>
            <Navbar />
            <div class="container">
            <h2>Dolina dos Irerês</h2>
		<p className="text-article">The Dolina dos Irerês is one of the main postcards of the city. It is located in the heart of the Historic Center, being a point of convergence of streets and avenues that radiate to all regions of the city. Since the 17th century it has appeared in practically all the capital's iconography, especially that of Dutch origin. There, the so-called Sítio da Lagoa, owned by the Jesuits, was later called Irerês Lagoon, due to a very common mallard that swam in its waters. Only in the early 1920s did the area pass into the hands of the state.</p>
		<p className="text-article">Thus, at the beginning of the 20th century, its landscape remained practically intact: a large lagoon, surrounded by leafy trees from the Atlantic Forest biome that collaborated to maintain its perpetuity, forming a swampy scenery and some sites that denoted the human presence in the area. For a long time it was an obstacle to the advancement of urbanization, especially towards the beach. </p>
		<p className="text-article">The installation of a park on the outskirts of the lagoon dates from the government of Mayor Guedes Pereira (1921-1924), with the planting of imperial palm trees all around, in addition to drainage and sanitation works. By law No. 110 of September 27, 1924, the park is named Solon de Lucena, in honor of the governor of Paraíba. Under the government of Argemiro de Figueiredo (1935-1940), Parque Solon de Lucena enters the sanitary plan of Saturnino de Brito, which aimed to expand the water supply network, basic sanitation and the opening and widening of new streets, in addition to its urbanization , through expropriations, earthworks, paving, installation of a light source in the center of the lagoon, handled from the Casino, opened during this period, among other works (photo 1a). This project enabled the expansion of the city to the east, with the opening of Avenida Epitácio Pessoa, still in the 1930s. Thus, from the occupation of the coastal boards, urbanization would advance to the coastal plain, the last geomorphological unit occupied by the population. Currently, its landscape has been intensely transformed (photo 1b).</p>
		<div class="text-center">
				<figure class="figure">
						<a href={dolina_1}><img src={dolina_1} class="img-fluid" alt="" /></a>
						<figcaption class="figure-caption">Photo 1a and Photo 1b</figcaption>
				</figure>
		</div>
		<p className="text-article">From a geomorphological point of view, the lagoon corresponds to a doline, a form that is very common throughout the project area, but most of the time without the presence of a water body. Thus, the permanence of this mirror makes it very special, representative of a natural aquifer recharge zone, in this case suspended, being at a height of about 35 meters. Its body of water measures 750 meters of perimeter, with about 4.5 ha of area, belonging to a centripetal basin with dimensions that reach 1.0 Km2 of total area (BARBOSA, 2015). It is relatively symmetrical, being housed in porous sandstones, of Plio-Pleistocene age, from the <b> Barreiras Formation </b>. It can be classified as a shelled doline, generated by the slow subsidence of the calcareous lumps of <b> Gramame Formation </b> ((Maastrichtianos), located about 3 to 4 meters below the water depth (ARAÚJO, 2012) which does not emerge at this altitude because it is covered by the Plio-Pleistocene sediments from the <b> Barreiras Formation </b>. Vital (2015) correlated this dolina and others in the region to a series of discontinuities present in the Gramame limestone. shows its connection to the suspended water table (figure 1), which is limited at the base by an impervious layer of fragipan, similar to 'Gruta das Marés' and 'Arenização do Barreiras'. </p>
		<div class="text-center">
				<figure class="figure">
						<a href={dolina_2}><img src={dolina_2} class="img-fluid" alt="" /></a>
						<figcaption class="figure-caption">Figure 1</figcaption>
				</figure>
		</div>
		<p className="text-article">During the rainy season, its waters converge on the lagoon, causing flooding. In a renovation carried out by the administration of Mayor Luciano Cartaxo (2012-2016), a new tunnel was built to drain its waters to the Sanhauá River, in order to avoid such storms, since there is no natural channel that drains these waters downstream.</p>
		<p className="text-article">Due to its exceptional aesthetic value, combined with the very high scientific, cultural and economic values, Dolina dos Irerês is one of the representatives of the geopatrimony of the area.</p>

            </div>
        </>
    )
}