import pesquisa from '../../../assets/pesquisageo.jpg';


export function GeoBr(){
    return(
        <>
        <p>In Brazil, the first scientific records on the theme of Geotourism date from the beginning of the 2000s. Brazil, due to its size, makes it difficult to uniformly inventory potential sites for geotouristic use, even though a good part of them has an intense tourist flow due to the characteristics of geodiversity, especially its spectacular forms of relief, such as the famous sugar loaves, which occur in the city of Rio de Janeiro, the Iguaçu Falls (PR), the cliffs of the beautiful northeastern beaches and the canyons of the Aparados da Serra ( RS), among others.</p>

        <p>The activities of SIGEP and CPRM stand out as important activities for the dissemination of this theme in Brazil; scientific meetings; Geosciences or Tourism magazines / periodicals; master's dissertations and doctoral theses; exclusive websites on geotourism, among others (NASCIMENTO, 2008). However, there are no exclusive events or magazines on this subject, unlike other regions of the globe, especially in Europe.</p>
          
        <p>One of the pioneering efforts to publicize geodiversity for geotouristic purposes, even if indirectly, was the Rio de Janeiro ‘Geological Paths’ Project, created in 2001 under the auspices of DRM / RJ. This diffusion occurs through 81 information panels installed in geosites distributed in 23 municipalities, composed of texts and illustrations that portray the geological evolution of the sampled place [1].</p>
          
        <p>The first state project aimed directly at the integration of Earth Sciences and tourism was called ‘Geological and paleontological sites of Paraná’, developed by MINEROPAR and previously mentioned. Similar to the ‘Geological Paths’, it consists of installing panels in strategic locations in the State, as well as promoting geotouristic itineraries, with the support of public and private bodies (PIEKARZ and LICCARDO, 2006).</p>
          
        <p>In December 2004, with the creation of the group called 'Patrimônio-Geológico', on Yahoo Groups by geologist Marcos Nascimento and collaborators, the discussions on the theme, as well as the articulation of a movement to insert a thematic session at the next congress, in a systematized and mature way, it made geotourism take shape in the country. In this group, publications and links about the 5G’s are available (NASCIMENTO et al., 2008), counting, in November 2017, with 393 participants of different nationalities.</p>
          
        <p>The introduction of the theme ‘geotourism’ in national scientific events has been around for 15 years. It dates back to 2004, at the XLI Brazilian Congress of Geology, in Araxá (MG), when the theme was first introduced in a perspective of 'Tourism' activity, although associated with 'Sustainable Development and Geology', therefore in a derisory way and without proper articulation. Another important scientific event for the dissemination of the theme of geotourism in Brazil was the Brazilian Symposium on Geological Heritage, introduced in 2011 and held every two years, as already mentioned in subchapter 2.2.2.</p>
          
        <p>In February 2007, the site “# geoturismobrasil.com” was launched by the geologist and photographer from Paraná, Liccardo, serving as a tool for the dissemination of works, ideas and discussions on this and other topics, such as geodiversity, geopatrimony and geoconservation, in addition to providing the lay public with knowledge on the subject and allowing access to a collection of beautiful photographs that portray Brazilian geodiversity. The fact of having an English version makes the site visited by scholars from around the world (NASCIMENTO et al., 2008).</p>
          
        <p>In the scientific area of ​​Geography, geotourism is still an incipient discussion. To give you an idea, only at the XVI Brazilian Symposium on Applied Physical Geography, held in Teresina (PI), in 2015, a thematic axis on the theme was introduced, ET09 - “Geoconservation, Geotourism, Geomorphological Heritage and Environmental Impacts”, where, of the 50 expanded summaries published, only ten dealt specifically with geotourism (two in geoparks and eight in areas not associated with geoparks), which shows the little participation of geographers in this theme.</p>
          
        <p>As for the publication of monographs, masters and theses, the pioneering work was produced by Barreto, in 2007, about the proposal for a geotouristic tour in Chapada Diamantina, belonging to the “National Circuit of Estrada Real” (BARRETO, 2007 apud RUCHKYS et al. , 2017). The first doctoral thesis on the theme of geotourism was published in 2008, defended by the student of the Federal University of Santa Catarina (UFSC), Jasmine Moreira, with the title "Geological Heritage in Conservation Units: interpretive, educational and geotouristic units" (MOREIRA, 2008), awarded with the 'CAPES Award for theses', in 2011. The same author published, in that year, the first exclusive book on the theme, entitled “Geotourism and environmental interpretation”, emphasizing the importance of geotouristic activity for geoconservation and as a tool for the dissemination of Geosciences from environmental education (MOREIRA, 2011).</p>
          
        <p>From these publications, several undergraduate works, master's dissertations and doctoral theses on the subject were defended, such as Carvalho (2010), Santos (2014), Pinto (2015), among others. Even so, when compared to discussions about geodiversity, geopatrimony or geoconservation, this topic is still incipient in the country.</p>
          
        <p>In 2011, the Support Center for Research in Geological Heritage and Geotourism (Geohereditas) was created by the faculty of the School of Arts, Sciences and Humanities and the Institute of Biosciences of the University of São Paulo (USP), in addition to the Institute Geological Survey of the Federal University of Rio de Janeiro (UFRJ) and the Complutense University of Madrid. The objective of the nucleus is to promote and promote research, debate and extension activities in the areas of Geotourism, Geoconservation and Environmental Education in several USP units, associated institutions and other sectors of society, through basic geological research, scientific dissemination geological and environmental knowledge and support for the professional insertion of the population through activities linked to geological heritage [2].</p>
          
        <p>In particular, the theme of coastal geotourism in Brazil is incipient, basically restricted to researchers from Pernambuco and São Paulo, with publications mainly in the annals of scientific events (GUIMARÃES et al., 2014; CANDEIAS et al., 2014; MOTA et al., 2014; GUIMARÃES et al., 2015). Noteworthy is the Master's Dissertation of Thaís Guimarães (GUIMARÃES, 2013), which makes reference to a proposal for the insertion of geotouristic practices in a coastal metropolitan park near Recife, aiming at geoconservation and the Project “Roteiro Geoturístico Litoral Norte de São Paulo ”, under the responsibility of USP's Geohereditas.</p>
          
          <p>In turn, the first work on urban geotourism carried out in Brazil, even if indirectly, involved studies on urban geology and was published in 2001 as a report of completion of the Undergraduate course in Geology, at USP. In this work, Stern (2001) traced a geological route through several buildings in the Historic Center of São Paulo, identifying and describing the lithologies that belong to them.</p>
          
          <p>Since then, there are several proposals for the study of geodiversity in Brazilian urban environments, whether in the form of geological routes for the purpose of urban geotourism or for pure scientific knowledge, when studying details, such as stonework or lithological pathologies in buildings [3 ]. As examples, we have the city of Natal (DANTAS, 2001; CARVALHO, 2010); São Paulo (STERN et al., 2006; REYS et al., 2008; AUGUSTO and DEL LAMA, 2011; MACHADO and DEL LAMA, 2014; DEL LAMA et al., 2015); Belo Horizonte (FERNANDES et al., 2007); the historic municipalities of the Gold Cycle, in Minas Gerais (LICCARDO, 2007; PEREIRA et al., 2007c; COSTA, 2014); Porto Alegre (PHILLIPP and BENEDETTI, 2007; BENEDETTI et al., 2007; PHILLIPP et al., 2009); Salvador (SILVA, 2008; PINTO et al., 2012; PINTO, 2015); Metropolitan Region of Recife (RIECK and SOUZA, 2008); Curitiba (LICCARDO et al., 2008; LICCARDO, 2010); Pirenópolis (CONCEIÇÃO et al., 2009); Ouro Preto (MORAES et al., 2011; PAULA, 2013); Rio de Janeiro (MELLO et al., 2014); João Pessoa (PEREIRA and AMARAL, 2014; PEREIRA et al., 2015a; 2015b; 2016b; PEREIRA, 2017a), among others.</p>
          
          <p>In the Brazilian Southeast Region, for example, the floor of the Shopping Center Eldorado, in São Paulo, is covered with marble with stromatolites that date back more than two billion years (LICCARDO et al., 2012), originating from the geological formations of the company itself. region, having been released to the population only in 2006, even though it has been known to academia since 1976 (SALLUN FILHO and FAIRCHILD, 2005; FAIRCHILD et al., 2006). It should be noted that this mall, in 2008, received the visit of 1.5 million people per month, who travel over these ornamental rocks without recognizing their scientific importance. For comparison, the Iguaçu Falls, an important natural monument, considered a World Heritage Site by UNESCO, received 1.15 million inhabitants throughout 2008 (LICCARDO et al., 2012). This is a clear example of the potential that the urban environment has for geotourism.</p>
          
          <p>Another geotouristic activity that can occur in urban or rural environments is that of geotourism in ex situ pieces, in museums, which can be installed in the vicinity of the geopatrimony visited or in urban centers. In any case, the museum's role should be to draw a dialogue between the object and the visitor, as an educational, cultural and tourist location (MAGALHÃES-GOMES and AZEVEDO, 2003 apud NASCIMENTO et al., 2008). The way in which the collection will be presented to the visitor is crucial to enhance its educational and entertainment role.</p>
          
          <p>Cemetery tourism is also a very particular aspect of urban geotourism, on the rise in the country (KUZMICKAS and DEL LAMA, 2012, 2015; LICCARDO and GRASSI, 2014; RODRIGUES and DEL LAMA, 2014), whose observation of aesthetics and analysis of stone materials used in the tombs make many tourists and scholars move to this new geotouristic segment.</p>
          
          <p>Ruban (2015) emphasizes that Brazil is among the main research centers on geotourism in the world. Analyzing publications in magazines and newspapers, published between 2012 and 2014, the author places Brazil in 2nd place, with 59 publications, behind Italy, with 61 publications, followed by China (52) and Poland (38). These data prove that the Brazilian scientific community has adopted and supports the theme, which has openly grown and become dynamic in academic circles and outside them as well.</p>
          
          Thus, based on Ruban (2015), we propose four stages for the dissemination of the theme “geotourism” in Brazil, as shown in figure 4.2: <br />
          <a href={pesquisa}><img src={pesquisa} alt="" class="img-fluid mx-auto d-block" /></a>
          <p><b>Fig 4.2</b></p><br />
          i) until 2004, when the theme was still incipient and the number of publications was reduced, it resulted in publications that were practically nonexistent, being restricted to scripts involving urban geology, theory development, with basic ideas or the discussion about proposals for geoparks, where geotourism was a secondary activity; <br /> ii) from the creation of the Yahoo Groups “Patrimônio-Geológico” and the XLI Brazilian Congress of Geology, in 2004, the dissemination of the theme, even if timid, spreads, showing the interest that researchers have for it ; <br /> iii) between 2007-2008, the theme is consolidated in the country, based on the proposal of the site # geoturismobrasil.com ”, added to the publication of the book 'Geodiversidade, Geoconservação e Geoturismo' (NASCIMENTO et al., 2008 ) and Moreira's doctoral thesis, in the same year; <br /> iv) as of 2008, geotourism publications increase, as well as the studied objects and methods, with national and foreign publications.
          
          <p>It is concluded that by inserting elements of the natural landscape, especially the abiotic heritage, as well as the cultural heritage to the tourist activity, as a result of a more demanding market, it ends up providing the rise of niche tourism, and geotourism fits in this context, as an integrated activity between Geosciences, culture and the history of the place where they are inserted.</p>
          
          <hr />
          [1] DEPARTMENT OF MINERAL RESOURCES OF RIO DE JANEIRO-DRM / RJ. Geological Paths. Available in http://www.drm.rj.gov.br/index.php/downloads/section/13-placas-caminhos-geologicos. Accessed on November 9, 2017.<br />
          
          [2] UNIVERSITY OF SÃO PAULO-USP. Research Support Center. Geoheredites. Extracted from http://www.igc.usp.br/index.php?id=605. Accessed on August 22, 2015.<br />
          
          [3] In the case of the study and characterization of the rocks that make up churches, monasteries, etc., a new branch of urban geology called 'Ecclesiastical Geology' has recently emerged, the results of which can be inserted into urban geotouristic trails. For further discussion of this topic, Sutherland (2000), Potter (2005) and Caetano et al. (2006), among others.
        </>
        
    )
}


