import dominio1 from '../media/dominio1.jpg'
import dominio2 from '../media/dominio2.png'




export function Dominios(){
    return(
        <>
            <p class="paragraphy">Em uma escala regional, Melo e Rodriguez (2003) propuseram a divisão do relevo paraibano em cinco unidades geomorfológicas, do leste para o oeste: <b>baixada litorânea, baixos planaltos costeiros, depressão sublitorânea/Curimatau/Baixo Rio Paraíba, superfície da Borborema e pediplano sertanejo</b> (com a Bacia do Rio do Peixe). A área desta tese encontra-se totalmente inserida no domínio das terras baixas litorâneas e no domínio dos baixos planaltos ou tabuleiros, conforme pode-se ver na figura 1.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={dominio1}><img src={dominio1} class="img-fluid" alt="" /></a><br />
                    <figurecaption class="figure-caption">Figura 1- Unidades geomorfológicas da Paraíba, com a delimitação da área da tese em vermelho. Modificado de Melo e Rodriguez (2003).</figurecaption>
                </figure>
            </div>
            <h4>Domínio das terras baixas litorâneas</h4>
            <p class="paragraphy">Segundo Melo e Rodriguez (2003), o <b>domínio das terras baixas litorâneas</b> possui até 8 m de altitude, com exceção de algumas dunas com mais de 15 m. Os depósitos quaternários podem ser agrupados em dois sistemas deposicionais: continental e costeiro. No <b>sistema continental</b> estão inseridos os depósitos associados às vertentes, vinculados aos fenômenos de movimentos de massa generalizados em condições climáticas pretéritas, mas pertencentes ao Período Quaternário. Pertencem a este sistema os cones de dejeção, depósitos fluviais, coberturas elúvio-coluviais e coluviais.</p>
            <p class="paragraphy">O <b>sistema costeiro</b>, deposicional transicional litorâneo ou marinho, é resultante da variação do nível eustático do mar, resultado de condições paleoclimáticas e de fatores hidrodinâmicos costeiros, a exemplo do vento, marés, ondas e correntes marítimas, ocorridas a partir do Pleistoceno<sup>1</sup>. Este sistema está representado por terraços marinhos pleistocênicos e holocênicos, depósitos fluviolagunares, depósitos de mangues em pântanos, depósitos eólicos, recifes de corais, beach rocks (arenitos praiais) e areias praiais. As feições mais representativas foram selecionadas como Local de Interesse Geoturístico.</p>
            <h4>Domínio dos baixos planaltos costeiros</h4>
            <p class="paragraphy">Os <b>baixos planaltos costeiros</b> são representados pelos tabuleiros, com topos planos ou suavemente ondulados que encerram abruptamente, nas planícies adjacentes, na forma de vertentes relativamente íngremes. Na planície litorânea, estas vertentes recebem o nome de <b>falésias</b>, podendo ser ativas ou não, formadas pela <b>Formação Barreiras</b> e interrompidas pelos entalhes fluviais, na forma de vales abertos ou encaixados formando vastos anfiteatros. Dão sequência aos depósitos sedimentares das terras baixas litorâneas, com suas praias, terraços, planícies fluviais, campos de dunas, entre outros. Os tabuleiros apresentam, como já referido anteriormente, suave inclinação para leste e altitudes médias que atingem 40 a 50 m e afastamento de até 40 Km da linha de costa. Pontualmente, as águas pluviais são captadas em grande volume pelo baixo nível de inclinação do terreno, formando dutos internos, ao longo dos planos de estratificação, que resultam na abertura de espaços formando pequenas grutas, a exemplo da ‘Gruta’ das Marés, que foi selecionad como um Local de Interesse. Esta gruta foi escavada nos arenitos, argilitos e siltitos Plio-pleistocênicos da <b>Formação Barreiras</b>, nas proximidades do Rio Mumbaba, afluente da margem esquerda do Rio Gramame.</p>
            <p class="paragraphy">Todo o litoral paraibano apresenta falésias que podem sofrer abrasão marinha ou não. As <b>falésias ativas</b>, ou vivas, continuam recebendo o impacto das ondas nas marés de águas vivas e, portanto, o risco de desabamento, a exemplo da falésia do Cabo Branco, que teve parte desabada em janeiro de 2018, é iminente, merecendo cuidados especiais e atitudes mais drásticas das autoridades. A estrada que ligava a praia de Cabo Branco ao farol, no topo da falésia, foi fechada para reduzir a pressão sobre a falésia, e o acesso se dá, atualmente, por um caminho que a circunda. As <b>falésias inativas</b>, ou mortas, apresentam-se mais recuadas no continente, não sofrendo mais o solapamento marinho e são importantes indicadores da transgressão marinha pretérita. Um Local de Interesse foi selecionado em cada tipo de falésia (Falésias do Cabo Branco e Inativas Urbanas, respectivamente).</p>
            <p class="paragraphy">No litoral sul, a porção oriental dos tabuleiros, nas proximidades das falésias, apresentam cicatrizes de erosão pluvial, formando extensas voçorocas e ravinas, enquanto algumas falésias, um pouco mais recuadas, foram tomadas por vegetação na sua base, recobrindo sedimentos que formaram depósitos coluviais. Ambas as feições, voçorocas/ravinas e colúvios, foram selecionadas como Local de Interesse (Cânion de Coqueirinho e Cones de Dejeção, respectivamente, no litoral sul do Estado).</p>
            <p class="paragraphy">A heterogeneidade das falésias, segundo Neves (1993), é explicada, antes de mais, pelas diferenças litológicas da <b>Formação Barreiras</b>. No geral, suas vertentes deveriam manter-se estáveis ao longo do tempo, apesar de desgastes e arredondamento das formas como consequência da atuação dos agentes exógenos. Entretanto, a ação antrópica, na forma de desmatamento e ocupação irregular, entre outros, acabam por instabilizar estas vertentes, incrementando os processos erosivos na forma de movimentos de massa, como solifluxão e deslizamentos de vertente, além do aumento do escoamento das águas pluviais, o que agrava a possibilidade de inundações.</p>
            <p class="paragraphy">Assim, a dinâmica continental tem um papel predominante nas vertentes dos vales fluviais, localizados no interior da área, resultando em diferentes inclinações e padrões, neste caso, com as vertentes variando de retilíneas, convexas, côncavas ou com mais de um padrão.</p>
            <p class="paragraphy">Como referido no capítulo anterior, a morfologia dos baixos planaltos, formando altos e baixos que se intercalam no terreno, gerando uma superfície suavemente ondulada, com topo relativamente planos, é o resultado dos eventos de falhamentos que ocorreram desde o Plioceno, configurando estruturas tipo grabens e horsts, que acabam abruptamente na linha de costa na forma das falésias. Esta estrutura falhada, com soerguimentos e aprofundamento de blocos podem ser corroborados, conforme referido anteriormente, por meio da análise de testemunhos de sondagens retirados de poços tubulares, onde a grande variação nas cotas dos níveis do calcário Gramame atesta esta ocorrência (ARAÚJO, 1993; LEAL E SÁ, 1998; BARBOSA, 2007). Os tabuleiros são, portanto, um compartimento fragmentado que tangencia a linha de costa e que foi preenchido por sedimentos dispostos à retaguarda da planície costeira.</p>
            <p class="paragraphy">Em várias porções da área estudada, feições geomorfológicas cársticas e antrópicas se fazem presentes. No caso das feições cársticas, as de dissolução são as mais comuns, como dolinas e lapiás. Em relação às dolinas, com base em análise de fotografias aéreas e cartas planaltimétricas, pode-se identificar várias porções do município de João Pessoa que possuem subsidência do terreno por dissolução do calcário Maastrichtiano da <b>Formação Gramame</b>, ao longo de planos de falhas que servem de conduto para a percolação das águas superficiais, com o abatimento dos sedimentos Barreiras e posterior ocupação destas dolinas por população de baixa renda e que, por ser uma área topograficamente deprimida, é suscetível a inundações em épocas de chuvas intensas. Vital (2015), por meio de trabalho de campo e de gabinete, com imagens de radar Shuttle Radar Topography Mission (SRTM) e cartas topográficas, obteve dados morfométricos sobre as dolinas da região, estabelecendo relações genéticas entre estas e os lineamentos tectônicos presentes, assim como foram indicadas relações entre as depressões superficiais e as depressões soterradas, com a detecção de feições de dissolução, ao longo de planos de descontinuidade, associadas a ocorrência de epicarste. Um exemplo de dolina mapeada localiza-se nas proximidades do Viaduto de Oitizeiro, denominada Três Lagoas, que possui uma ligação direta com a nascente do Rio Jaguaribe. Entretanto, a mais imponente destas dolinas, selecionada como um Local de Interesse e, portanto, avaliada, foi a Dolina dos Irerês, no centro de João Pessoa, que integra o atual Parque Solon de Lucena.</p>
            <p class="paragraphy">Campos de lapiás afloram em diversas porções da área de estudo, mostrando a origem carbonática de parte dos terrenos da Bacia da Paraíba. As mais interessantes feições deste tipo são as que afloram entre as praias de Tambaba e Tabatinga, tendo também sido selecionadas como Local de Interesse (Praia de Tambaba e Pedra do Amor, no litoral sul) e, posteriormente avaliadas.</p>
            <p class="paragraphy">As feições antropogênicas mais comuns são as minas de exploração de calcário, as lagoas antropogênicas e os viveiros de carcinocultura.</p>
            <p class="paragraphy">A figura 2 representa o mapa geológico-geomorfológico da área, retratando as unidades litoestratigráficas presentes e principais feições estruturais mapeadas nesta escala, assim como i dentifica as formas de relevo costeiras, considerando-se a 5ª, 6ª e 7ª ordens de grandeza taxonômica, com a delimitação de todos os Locais de Interesse selecionados para a avaliação qualitativa e semiquantitativa.</p>
            <div class="text-center">
                <figure class="figure">
                    <a href={dominio2}><img src={dominio2} alt="" class="img-fluid" /></a><br />
                    <figurecaption class="figure-caption">Figura 2 - Mapa geológico-geomorfológico da área da tese, com a demarcação dos Locais de Interesse Geoturístico. Elaborado pelo autor.</figurecaption>
                </figure>
            </div>
        </>
    )
}