import pero from './media/pero.png';
import duarte from './media/duarte.png';
import valdez from './media/valdez.png';
import indios_ataque from '../../assets/indios-ataque.jpg';
import barco from '../../assets/barco.jpg';
import castelinho from '../../assets/castelinho.jpg';
import indios_conversa from '../../assets/indio-conversa.jpg';
import castelochamas from '../../assets/castelo-chamas.jpg';
import jogados from '../../assets/jogados.jpg';
import acordo from '../../assets/acordo.jpg';
import tabela_cidade from '../../assets/tabela-cidade.jpg';


function Antecedentes(){
    return(
       <>
        <p className="paragraphy">Vários relatos da época apontam a importância estratégica e natural das capitanias do norte no processo de colonização,<sup>1</sup> , assim como ressaltam as qualidades do meio natural para tal.. A proximidade da Europa, matas abundantes em pau Brasil, solo favorável à cultura de cana de açúcar, rios largos e com bom calado eram algum dos requisitos que a região possuía e que fazia com que os olhos da Coroa se voltassem para lá.</p>
        <p className="paragraphy">Desde antes da delimitação das capitanias e ocupação efetiva da região, várias expedições já haviam deixado suas marcas no nordeste. Como citado anteriormente, a passagem da expedição de Cristóvão Jaques lançou a base de uma feitoria em Itamaracá. Pelas mesmas águas havia passado Martim Afonso de Sousa em 1531, participando desta viagem seu irmão, Pero Lopes de Sousa. Foi o próprio Pero Lopes, quando da divisão do território em capitanias, que solicitou ao rei a capitania de Itamaracá para si, além de outras na porção meridional da colônia. Diferentemente de Duarte Pereira, que levou a sério a ocupação e colonização da sua, Pernambuco, o espírito desbravador, aventureiro e inquieto de Pero Lopes fez com que o donatário se mantivesse na área não mais do que dois meses e meio (ALMEIDA, op. cit., p. 45), deixando em seu lugar, como administrador da feitoria, Francisco Braga. Entretanto, foi numa nova expedição às Índias que Pero Lopes acabou por perder a vida em um naufrágio (leia o quadro 1 para a biografia de Pero Lopes). A partir daí, iniciou-se um imbróglio entre a capitania de Itamaracá e de Pernambuco. Para se ter uma noção desta relação entre capitanias, Francisco Braga, foi agredido com uma cutilada no rosto a mando de Duarte Coelho, se obrigando a retornar à Portugal e deixando, novamente, a capitania a toda sorte de administradores (SALVADOR, 2010, op. cit., p. 156). Duarte Coelho, em várias cartas enviadas ao rei entre 1546 e 1549, fazia graves acusações à Capitania de Itamaracá onde, segundo ele, residiam homens desonestos e mercenários, que trocavam o trabalho dos índios por armas de fogo, espadas e ferramentas, contrabandeavam pau Brasil ou que viviam do negócio de aprisionamento de índios, que prejudicava sobremaneira a indústria açucareira de sua capitania (MELLO; ALBQUERQUE, 1997), o qual nunca obteve resposta. Com o abandono da capitania por Francisco Braga, a esposa do donatário, D. Isabel de Gamboa, então em Portugal e herdeira da capitania, pouco se interessou em administrá-la, passando para João Gonçalves a responsabilidade de administrar a falida capitania. Neste meio tempo, a viúva havia abdicado de vinte e três léguas da capitania, devolvidas à Coroa, ficando ela, portanto, responsável pela manutenção das sete léguas restantes. A data correta desta devolução, entretanto, permanece lacunar entre os historiadores.</p>
        <p className="paragraphy">Durante parte do governo de João Gonçalves (veja biografia no quadro 1), a capitania viveu sua ‘era dourada’, pois seu carisma e bom trato facilitou uma relação pacífica com os índios, possibilitando, inclusive, um incipiente crescimento econômico com a instalação de engenhos em terra firme e continuação da edificação da Vila de Conceição (ALMEIDA, 1978, op. cit., p. 46) <sup>2</sup>, sem o risco de ataques-surpresa impetrados pelos gentios.</p>
        <p className="paragraphy">Duarte Coelho, natural de Viana, desde o início empregou muito dinheiro seu na empreitada de conquista das terras da Nova Lusitânia, conforme apelido por ele dado, ou capitania de Pernambuco, inclusive convidando, praticamente, todos os seus familiares para virem morar na colônia. O abandono e má gestão de sua vizinha ao norte lhe causavam muita preocupação. A porção norte da capitania de Itamaracá, onde hoje se encontra a Paraíba, era dominada pelos potiguaras, do grupo Tupi, que aliados aos franceses, declararam os portugueses seus inimigos mortais.</p>
        <p className="paragraphy">Vários são os episódios de lutas entre os portugueses e os indígenas. Em 1548, por exemplo, Igarassu foi cercado por oito mil caetés e durante várias semanas ninguém entrava nem saia da vila. Numa última tentativa de massacrar os colonos, os índios foram surpreendidos pelos portugueses e acabaram retornando para suas aldeias. Entretanto, neste levante, muitas vidas foram perdidas (ALMEIDA, 1978, op. cit., p. 46- 47) . Na década de 1560, com a chegada de Duarte Coelho de Albuquerque, filho de Duarte Coelho, falecido em 1554, os caetés continuavam sem dar descanso aos moradores de Pernambuco. Durante cinco anos, o donatário empreendeu um levante de guerra contra os caetés, até sua efetiva rendição (JABOATÃO, 1858, op. cit., p. 143- 145). Entretanto, os conflitos com os potiguaras, na banda norte da capitania de Itamaracá continuaria, pelo menos mais uns 35 anos.</p>
        <p className="paragraphy">Um dos episódios mais marcantes da relação dos Potiguaras com os portugueses se refere ao que os historiadores chamam de ‘Massacre de Tracunhaém’. Conta a história que o sesmeiro Diogo Dias, proprietário do Engenho Tracunhaém, em Itamaracá, se aproximou de uma tribo de potiguaras, na Serra da Copaoba, fazendo amizade com os nativos e se afeiçoando por uma índia de 15 anos, filha de um dos líderes da tribo, Inigaçu, a qual fez promessas de casamento. Em um dado momento, aproveitando um descuido dos pais, acaba por sequestrar e levar para seu engenho a jovem índia, o que gera revolta na tribo. Entretanto, os índios, chefiados pelos irmãos da jovem, tentam, através de uma negociação com o governador do Brasil, Antonio Salema, então em visita à Itamaracá, recuperar a filha, o que Diogo Dias não aceita. O final desta história é narrado por Salvador (2010):</p>
        <div className="paragraphy-modifded">
            <p className="paragraphy"><i>“[...] e com serem infinitos em número ainda usaram de uma grande astúcia, que não remeteram todos à cerca nem se descobriram, senão somente alguns, e ainda estes começando os nossos a feri-los de dentro com flechas e pelouros, se foram retirando como que fugiam; o que visto por Diogo Dias se pôs a cavalo, e saindo da cerca com seus escravos, foi em seu seguimento, mas tanto que o viram fora rebentaram os mais da cilada com um urro, que atroava a terra, e o cercaram de modo, que não podendo recolher-se à sua cerca, foi ali morto com todos os seus, e a cerca entrada, onde não deixaram branco nem negro, grande nem pequeno, macho nem fêmea, que não matassem e esquartejassem (SALVADOR, 2010, op. cit., p. 237). <sup>4</sup> ”</i></p>
        </div>
        <p className="paragraphy">Após este episódio, ocorrido em 1574, era iminente a possibilidade de uma nova invasão de potiguaras a Itamaracá, Olinda e Recife, insuflados pelos atos ocorridos no Engenho de Diogo Dias. O temor tomava conta dos moradores. O sucesso desta missão ultramarina estava comprometida. Era necessário que o rei tomasse uma atitude e mudasse sua postura. Vinte e três léguas norte da Capitania de Itamaracá que haviam sido desmembradas pela viúva de Pero Lopes e estavam abandonadas, do rio Abiaí à Baia da Traição, foram abdicadas pelo rei e fundada a Capitania Real da Parahyba (ALMEIDA, 1978, op. cit., p. 53- 54)<sup>5</sup>. Foi a terceira capitania régia fundada, posterior, respectivamente, à Bahia e Rio de Janeiro. Assim, o rei d. Sebastião iria assumir pessoalmente um compromisso de colonizar e conquistar a região que posteriormente daria origem a Paraíba, com o intuito de “garantir a manutenção e o reconhecimento internacional da sua soberania sobre aqueles territórios” (GONÇALVES, 2007, op. cit., p. 71), sendo época de “rasgar cartas e forais”, pois desde a fundação do Governo Geral, o poder discricionário dado por regimento a Tomé de Sousa havia enfraquecido o poder das capitanias (ALMEIDA, 1978, op. cit., p. 54). A Coroa portuguesa sabia que era um desperdício um território com tão imensa e reconhecida potencialidade permanecer inerte por tanto tempo, o que requeria sua efetiva conquista e povoamento. Na verdade, uma reconquista, especialmente daqueles espaços fragilizados, que haviam sido abandonados pelos que estavam responsáveis por sua ocupação, muitos deles derrotados pelo hostil nativo ou pela falta de subsídios para manter esta empresa ultramarina e, por conseguinte, à mercê da invasão francesa e contrabando de pau Brasil. A Coroa portuguesa, com esta medida, estava indo na contramão das medidas propostas décadas antes, quando havia deixado nas mãos do capital privado os investimentos de povoamento e colonização de sua possessão.</p>
        <h3>As Expedições de Conquista da Paraíba</h3>
        <h3 id="subtitle-persona">PERSONAGENS DA CONQUISTA DA PARAHYBA</h3>
            <div className="text-center">
                <img src={pero} className="figure-img img-fluid rounded" alt="PERO"/>
                <li> <b>Pero Lopes de Sousa</b> - Nascido em uma família abastada, seu pai, Lopo de Sousa, nobre fidalgo, recebeu o título de Senhor do Prado. Pero Lopes, sob o comando do irmão, Martim Afonso de Sousa, participou da armada de reconhecimento da costa brasileira em 1530. Com o sucesso desta empreitada, recebeu como recompensa do rei D. João III, quando da instituição do sistema das Capitanias, a partir da carta régia de doação em 1º de setembro de 1534 e foral de 6 de outubro do mesmo ano, 80 léguas de terra na costa brasileira, as quais foram divididas em três capitanias (Santo Amaro e Santana, ao sul, com 10 e 40 léguas, respectivamente; e Itamaracá, ao norte, com 30 léguas, de onde se desmembraria, futuramente, a Capitania da Parahyba). Seus interesses sempre se voltaram para a navegação. Assim, passou a administração de Itamaracá para Francisco Braga, que foi o responsável pelo povoamento e fundação da Vila da Conceição, na ilha de Itamaracá, entre 1535-36. Em uma nova expedição às Índias, em 1539, faleceu em um naufrágio quando retornava a Portugal, no Canal de Moçambique, às costas de Madagascar.</li>
            </div>
            <div className="text-center">
                <img src={duarte} className="figure-img img-fluid rounded" alt="DUARTE"/>
                <li>
                    <b>Duarte Coelho Pereira</b> - filho de Gonçalo Coelho, que foi emissário de d. João II, capitão-mor da armada de 1503 e escrivão da família real. Descendente de Viana, Duarte Coelho, foi elevado à condição de fidalgo pelo rei d. João III em 1521. Participou de diversas expedições bem sucedidas às Índias, como a tomada de Malaca e a possibilidade de comércio pacífico com os portugueses, missões diplomáticas à Tailândia, ao reino de Sião e à China, entre outros, tornando-se donatário das 50 léguas da Capitania de Pernambuco, vizinha sul da Capitania de Itamaracá, a partir da carta régia de doação em 10 de 
                    março de 1534 e foral de 24 de setembro do mesmo ano. Em sua chegada às novas terras, encontrou algumas povoações e edificações, a exemplo de Olinda e Recife. Foi importante, pois esta capitania, assim como a de Itamaracá, serviu de núcleo inicial daqueles que povoaram a Parahyba, e dali partiram inúmeras expedições de conquista e cartas de pedido de socorro ao Rei para aquelas terras, assoladas pela agressão dos gentios às tentativas de colonização. Em 1554, resolveu retornar a Portugal para resolver problemas pertinentes à capitania, onde veio a falecer logo depois.
                </li>
            </div>
            <li><b>João Gonçalves</b> - conhecido como o ‘Capitão Velho’, o Capitão João Gonçalves participou da armada que aportou em 1532 em Itamaracá e expulsou os franceses que lá tinham se estabelecido. Posteriormente, logo após o retorno de Pero Lopes à Portugal, assumiu o cargo de Governador da Capitania em 1539, e enquanto esteve no poder, abriu-se a ‘era dourada’ em Itamaracá, devido a sua boa relação com os índios. O ano de seu falecimento permanece incógnito, mas em 1570 ainda governava Itamaracá.</li>
            <li><b>Fructuoso Barbosa</b> - rico proprietário e mercador português, fidalgo da casa real, negociante de pau-brasil, nascido em Viana e residente em Olinda, mas profundo conhecedor das redondezas da foz do Rio Paraíba recebe, em 25 de janeiro de 1579, do Rei d. Henrique, o Alvará régio de capitão-mor das terras da Parahyba por 10 anos, no momento em que esta fosse ocupada e colonizada. Assim, não desistiu deste objetivo, sendo responsável por várias expedições para a Paraíba. De personalidade controversa: para alguns historiadores, foi considerado arrogante, ganancioso, brigão e soberbo, e co-responsável pelo insucesso destas missões; para outros, ambicioso, incapaz, pobre de inteligência e ânimo frouxo; ou empreendedor, contundente nas suas decisões e vítima das adversidades. Após a conquista desta e a fundação da cidade de Nossa Senhora das Neves, atual João Pessoa, recebeu o tão sonhado cargo de capitão-mor, entre 1588- 1591, substituindo João Tavares, o governador precursor destas novas terras.</li>
            <div className="text-center">
                <img src={valdez} className="figure-img img-fluid rounded" alt="VALDEZ"/>
                <li><b>Diogo Flores Valdez</b> - general espanhol, participou da fracassada armada ao Estreito de Magalhães contra corsários que atacavam o Peru, em 1581. Durante a União Ibérica, foi nomeado pelo Rei d. Filipe II para auxiliar na conquista da Parahyba, entre março e maio de 1584, sendo responsável pela construção do forte de São Filipe e São Tiago, ou Forte Velho, em frente à Ilha da Restinga, na margem esquerda do Rio Paraíba. Ao regressar à Espanha, em 1º de maio, deixou no cargo de acaide desta fortaleza, seu conterrâneo Francisco Castejon.
                </li>
            </div> 
            <li><b>Martim Leitão</b> - residente em Olinda, Ouvidor Geral da Capitania de Pernambuco, é o ‘braço direito’ do rei nestas paragens. Teve um papel fundamental na conquista da Parahyba, através do envio de armadas, mantendo contato com os nobres em Portugal, chefiando expedições, remetendo provisões e sendo o protagonista, juntamente com João Tavares, no acordo de paz entre os portugueses e os índios tabajaras, no dia da considerada fundação da cidade de Nossa senhora das Neves. Corajoso, político estrategista, perspicaz, letrado, hábil em armas, carismático e respeitado por seus soldados, mas disciplinador, nunca declinou de uma missão de guerra contra os gentios, recebendo a alcunha, por parte de alguns cronistas da época, de General. Após a conquista, foi fundamental no processo de povoamento do núcleo urbano, assim como na organização dos arredores para sua expansão. Sua participação na Parahyba termina no início de 1587, quando retorna, doente e cansado, para Pernambuco. É demitido do cargo de Ouvidor Geral e enviado para a metrópole, resultado de um atrito com o governador Manoel Teles Barreto, quando se posicionou a favor dos padres da Companhia de Jesus na demarcação e posse de terras de Camamu, o que gerou revolta local. </li>
        <li><b>Piragibe (‘Braço de Peixe’)</b> - chefe da etnia Tabajara, esta tribo havia sido expulsa de suas terras pelos Potiguaras, localizadas entre o rio Goiana e a ilha de Itamaracá, indo se alojar nas redondezas da foz do Rio São Francisco. Teve um papel crucial na conquista da Parahyba, quando se alia aos portugueses em 05 de agosto de 1585, episódio que marca a fundação de Nossa Senhora das Neves. Provavelmente um octogenário, era considerado corajoso, valente, sagaz e mártir.</li>
        <li><b>João Tavares</b> - personagem histórico do ‘dia da aliança’, portador da paz, que marca a data de fundação de Nossa Senhora das Neves (05 ago 1585), juntamente com Piragibe, ocupava o cargo de Escrivão da Câmara e Juíz dos Órfãos, em Olinda, sendo homem de confiança de Martim Leitão. Se torna, no início de 1586, o primeiro capitão-mor da Parahyba, nomeado interinamente por Martim Leitão, cargo que ocupa, mesmo que não continuamente, até 1588, quando é substituído por Fructuoso Barbosa. Conhecido como ‘Capitão’ João Tavares, homem valoroso, com sangue frio, morre em uma expedição para a Paraíba, em 1590.</li>
        <li><b>Duarte Gomes da Silveira</b> - senhor de engenho e um dos mais ricos lavradores da época, respeitado, morador de Olinda, participou das primeiras expedições à Parahyba, com o interesse de expandir seus negócios para a nova Capitania Real. Uma vez fundada Nossa Senhora das Neves, foi residir na Rua Nova (atual General Osório), sendo genro de João Tavares, e teve papel crucial na expansão urbana da capital, inclusive através de oferta pessoal de dinheiro a quem edificasse novas moradias na nascente urbe, além de ser o fundador da Santa Casa da Misericórdia. Posteriormente, participou de inúmeras expedições para limpeza dos arredores da capital. Personagem controverso: grande político, empresário de engenhos, homem de posses, inescrupuloso. Em 1616, é denunciado por fraudar a Fazenda Real, uma década antes. Por interesses pessoais, tornou-se aliado dos holandeses quando estes invadiram a região (entre 1634- 1654), gerando antipatia dos moradores da cidade. Faleceu em Frederica (então denominação de João pessoa), em 1644.</li>
        <p className="paragraphy">Para se conquistar esta inóspita, mas crucial, paragem que envolve o Rio São Domingos, o primeiro passo seria organizar uma expedição que se direcionasse à foz do Rio Paraíba para expulsar todo e qualquer povo que lá estivesse, seja o nativo potiguar ou estrangeiro, e fincar em terras paraibanas, o marco colonizatório e de conquista. A Paraíba representaria um ponto estratégico para o povoamento das colônias do norte, em direção ao Maranhão e Pará. Ademais, a expulsão dos franceses consolidaria a cultura do pau Brasil como monopólio da Coroa, que introduziria, também, os engenhos de cana-de-açúcar, como está descrito no texto de Gabriel Soares de Sousa, datado de 1587:</p>
       <div className="paragraphy-modifded">
            <i>“[...] assentou Sua Majestade de o mandar povoar e fortificar... (...) Este rio da Paraíba é muito necessário fortificar-se, a uma por tirar-se esta ladroeira dos franceses dele, a outra por se povoar, pois é a terra capaz para isso, onde se podem fazer muitos engenhos de açúcar (SOUSA, 1879, op. cit., p. 14; 16).”</i>
       </div>
       <p className="paragraphy">A primeira tentativa de expedição que se tem notícia ocorreu antes da emancipação da Capitania Real da Parahyba, em 1570. O rei D. Sebastião despachou o capitão e Governador Geral D. Luis de Vasconcelos para o Brasil, especificamente para expulsar os franceses do rio Paraíba. Entretanto, está armada foi interceptada por naus francesas e o capitão nunca chegou ao seu destino (MACHADO, 1977a, op. cit., p. 43).</p>
        <p className="paragraphy">O documento definitivo, que narra as expedições de conquista da Paraíba, é o “Summario das Armadas”<sup>6</sup> . Segundo Almeida (1978, p. 77), a obra “não tem [...] assinatura, mas está apurado que foi escrito em 1603”. O importante é que seu autor, mesmo desconhecido mas pertencente à Companhia de Jesus, se diz “testemunha de vista [...] desta empresa da Parahyba” (SUMMARIO, 1848, op. cit., p. 38), tendo participado de praticamente todas as armadas até a conquista da Paraíba e narrando fidedignamente os acontecimentos.  Assim, esta será a obra que embasará os relatos a seguir.</p>
        <div className="text-center">
            <a href={indios_ataque}><img src={indios_ataque} className="desenhos" alt="" /></a>
        </div>
        <p className="paragraphy">O rei, em 1574, ordenou ao Governador Geral Luis de Brito de Almeida, que chefiasse uma expedição e “afose ver e elegesse sitio para a povoação” (SUMMARIO, 1848, op. cit., p. 33). O Governador declinou do pedido e nomeou o ouvidor geral e provedor mor da fazenda Fernão da Silva, então na Bahia. Esta expedição, entretanto, resultou em um retumbante fracasso. Cumprindo as ordens do Governador, Fernão rumou para Pernambuco, onde abarcou uma grande leva de soldados, que a pé e de cavalo rumaram, confiantes, para a Parahyba, onde tinham a intenção de castigar os gentios  e seus aliados, os franceses. Depois de longos dias de viagem, chegaram à foz do Rio Paraíba, em Cabedelo e, assim que tomaram posse da área, sofreram uma investida dos índios, que os obrigou a retornar para Itamaracá no mesmo instante (SALVADOR, 2010, op. cit., 240).</p>
        <p className="paragraphy">Era indispensável que a Paraíba fosse conquistada o quanto antes. Assim, uma nova armada, assumida pelo próprio governador Luis de Brito partiu da Bahia em setembro de 1575 e, apesar dos ventos contrários, que o fizeram arribar novamente à Bahia, com muita dificuldade conseguiram atracar em Pernambuco. Entretanto, esta dispendiosa e cansativa empreitada fez com que a expedição fosse cancelada e o retorno à Bahia foi imediato. O sonho de conquista dos arredores do Rio Paraíba mais uma vez tinha sido adiado.</p>
        <div className="text-center">
            <a href={barco}><img src={barco} className="desenhos" alt="BARCO" /></a>
        </div>
            <p className="paragraphy">Entretanto, a insistência da Coroa permanecia inabalável. Por ordem do novo governador Diogo Lourenço da Veiga, foi enviada outra armada à Paraíba, chefiada pelo ouvidor-geral Cosme Rangel de Macedo, em 1578. Mais uma vez resultou em insucesso frente às investidas potiguares, e os aventureiros recuaram para a Ilha de Itamaracá (SUMMARIO, 1848, op. cit., p. 34- 35)<sup>7</sup>.</p>
        <p className="paragraphy">Depois desse vexame, a crise da sucessão de D. Sebastião da Coroa, somada à má vontade do governador Lourenço da Veiga, apesar das súplicas do governador de Pernambuco Jorge de Albuquerque e dos moradores de Itamaracá, assolados por potiguaras cada vez mais insolentes, as expedições à Paraíba tiveram um breve hiato. Segundo alguns autores, incluindo Irineu Pinto e Maximiano Lopes Machado, no ano de 1579, a pedido do governador de Pernambuco, Jerônimo de Albuquerque, João Tavares (para conhecer sua biografia, veja quadro 1) teria fundado um fortim de madeira na Ilha de Gambôa, atual Ilha da Restinga, sem ter sido importunado pelos nativos. Entretanto, não há unanimidade deste evento entre a historiografia paraibana (PINTO, 1977, op. cit., p. 14)<sup>8</sup>.</p>
        <p className="paragraphy">Foi apenas na curta gestão de D. Henrique que os clamores de Itamaracá e de Pernambuco foram ouvidos, e neste momento entra o personagem de Fructuoso Barbosa (leia o quadro 1 para maiores detalhes), profundo conhecedor das redondezas da foz do Rio Paraíba, a qual explorava pau-brasil já a alguns anos. Fructuoso Barbosa possuía uma motivação extra: havia recebido do rei um Alvará régio de capitão-mor, datado de 25 de novembro de 1579 (BARBOSA, 1946, p. 173-174), pelo período de dez anos, das terras da Parahyba que conseguisse conquistar e povoar. Assim, a partir desta iniciativa de colonização, envolvendo capitais privados e monárquicos, Fructuoso partiu de Lisboa no ano de 1580<sup>9</sup> , com quatro naus equipadas com todo o aparato humano e bélico<sup>10</sup>  necessário para que esta empresa definitivamente se fixasse na Paraíba e a protegesse através da edificação de uma fortificação na barra do rio. Mas novamente sopraram literalmente ventos contrários e as armadas se dispersaram, indo parar no Caribe.</p>
        <p className="paragraphy">Após a morte de D. Henrique, em 31 de janeiro de 1580, assume o poder de uma península ibérica unificada o castelhano Filipe<sup>11</sup> , perdendo Portugal a sua independência. Estava formada a União das Coroas Ibéricas, que durou entre 1580 a 1640. Não nos adentraremos nas consequências geopolíticas desta união, pois não é o escopo deste trabalho. Entretanto, é pertinente ressaltar que, uma vez agora a possessão brasileira inserida nas malhas da Coroa espanhola e, por conseguinte, os interesses da conquista da Paraíba, novos personagens foram acrescidos, a exemplo de soldados e autoridades metropolitanas, tanto espanholas quanto portuguesas, autoridades coloniais (do Governo Geral e das capitanias de Pernambuco e Itamaracá), índios aldeados, escravos, além dos povoadores já estabelecidos (GONÇALVES, 2007, op. cit., p. 77- 78), o que gerou muitas intrigas e conflitos, tornando mais complexo o processo e dificultando, por vezes, o sucesso deste empreendimento.</p>
        <p className="paragraphy">Fructuoso Barbosa tentou uma nova investida de colonização, agora sob a perspectiva da União Ibérica, em fins de 1482, tendo sido confirmado no posto de Capitão-mor da Paraíba pelo rei Filipe II. Sua armada, composta de 200 homens a pé ou a cavalo, mais um esquadrão, que o incluía, por mar (ALMEIDA, 1978, op. cit., p. 65- 66) onde “assim chegarão a barra do Rio da banda do norte [...] e animados uns com os outros e tratados  em sete ou oito dias que ali estiverão os meios de se fortificarem e povoarem da banda do norte [...]” (SUMMARIO, 1848, op. cit., p. 35) Atracando no local, encontraram e capturaram cinco de oito naus francesas, na altura da Ilha da Restinga, que contrabandeavam pau-brasil. Posteriormente, enquanto parte da esquadra marinha foi realizar o reconhecimento do sítio que daria origem às futuras instalações do povoado e sede do governo, novamente foram surpreendidos pelos hostis selvagens<sup>12</sup>  e alguns franceses remanescentes. Com a chegada posterior da esquadra terrestre, os potiguaras resistiram o quanto puderam nesta sangrenta batalha, acabando por recuar para suas aldeias. Assim, com o caminho aberto, Fructuoso Barbosa pode iniciar um povoamento e fortificação na margem esquerda da foz do Rio Paraíba<sup>13</sup>. Um dos maiores problemas enfrentados nos dias em que as tropas por lá permaneceram foi o abastecimento de água, sendo que nos dois lados do rio, após uma breve avaliação, encontrou-se água de má qualidade. Somado a isso, um novo levante indígena fez parte dos soldados retornarem assustados para Pernambuco. Não seria dessa vez que Fructuoso Barbosa realizaria o sonho de conquistar a Paraíba. Assim, enviou um navio para o rei, atualizando-o dos acontecimentos e retornou para a Bahia para pedir socorro ao Governador Manoel Teles Barreto, deixando na Paraíba índios cada vez mais soberbos e animados de suas sucessivas vitórias. Os moradores de Itamaracá e Pernambuco voltariam a ser assediados, agora mais intensamente, pelos potiguaras.</p>
        <p className="paragraphy">A pedido do Governador Manuel Teles Barreto, ao ouvir as lamentações dos moradores das capitanias setentrionais enviados por Fructuoso Barbosa, temerosos de uma iminente invasão potiguara a seus povoados, o general hispânico Diogo Flores Valdez (leia quadro 1 para conhecer sua biografia) então se recuperando, na Bahia, de uma má sucedida ação no Estreito de Magalhães, parte para o nordeste, na companhia do Ouvidor- geral Martim Leitão (veja biografia no quadro 1), do Provedor da Fazenda Martim Carvalho<sup>14</sup>  e de Fructuoso Barbosa (sempre com o Alvará régio expedido pelo falecido rei D. Henrique, embaixo do braço), em 01 de março de 1584, com uma armada de sete naus espanholas e duas portuguesas. Vinte dias depois, atracaram em Pernambuco para o desembarque de Martim Leitão, Martim Carvalho e Fructuoso Barbosa. Passado alguns dias, após a formação de um verdadeiro conselho de guerra, partiram para o rio Paraíba, juntamente com a participação de uma tropa a pé, chefiada por D. Filipe de Moura, formando, na totalidade, uma força tarefa composta por cerca de mil homens. Desta vez, a conquista da Paraíba era dada como certa! Já na barra do rio, encontraram cinco naus francesas, quatro delas prontamente incendiadas. Uma vez dispersos os nativos, iniciou-se um litígio entre o general espanhol, que chefiava a expedição, e Fructuoso Barbosa, que se dizia Governador da Povoação, que curiosamente ainda não estava edificada. O primeiro imbróglio dizia respeito ao local de fundação de um forte para proteção da foz do rio: Valdez defendia a posição na margem esquerda, enquanto Barbosa argumentava o contrário, na qualidade de Governador da Paraíba, dizendo já conhecer, da expedição anterior, esta margem e possuir um sítio mais favorável à edificação, conforme relata Machado (1977a, op. cit., p 78)<sup>15</sup>.</p>
        <p className="paragraphy-modifded">“[...] a fim de examinar o sítio indicado nas suas instruções, para a fundação do povoado e sede do governo. Era o sítio indicado na margem meridional, extensa planície de muitas léguas, lavada pelos ventos do mar, com surgidouro profundo e amplo, e completamente ao abrigo dos temporais do sul, frequente na estação invernosa” (MACHADO, 1977a, op. cit., p. 49).</p>
        <div className="text-center">
            <a href={castelinho}><img src={castelinho} className="desenhos" alt="CASTELO" /></a>
        </div>
        <p className="paragraphy">A escolha deste sítio seria, estrategicamente falando, a pior possível, argumentou Fructuoso Barbosa. “[...] além de contrariar o regulamento que lhe fora dado como Governador da Paraíba<sup>16</sup> , nenhuma segurança oferecia aos moradores, antes os expunha à toda sorte de perigos, pois do lado esquerdo é que vinha o ataque do gentio [...] sem poder auxílio de Pernambuco, o que não daria se estivesse do lado direito do rio” (ALMEIDA, 1978, op. cit., p. 69). Foi voto vencido. Este conflito de interesses viria a marcar todas as ações que caracterizavam este momento histórico de União Ibérica, acabando por atrasar a conquista da Paraíba. Em 01 de maio, Valdez retornou à Espanha, nomeando por alcaide<sup>17</sup> o capitão de infantaria Francisco Castrejon do inacabado forte São Filipe e São Tiago, ou Forte Velho, que havia sido edificado no lado direito da foz do rio, em frente à Ilha da Restinga. Neste momento, segundo o autor do ‘Sumário’, o contingente do forte era “sento e setenta homens e alguns de cavallo”, incluindo Barbosa e Castrejon.</p>
        <p className="paragraphy">Uma vez instalados no forte, o ano de 1584 fora terrível para seus moradores. Já não bastassem o ininterrupto assédio dos hostis potiguaras e naus francesas, somava-se o abastecimento de água de má qualidade, causadora de males, falta de provimentos<sup>18</sup>  e a relação cada vez mais conflituosa entre Fructuoso Barbosa e Francisco Castrejon, que tornava o cotidiano dos soldados insustentável. Várias vezes Fructuoso Barbosa havia enviado cartas pedindo ajuda em Pernambuco e, apesar da boa vontade do Ouvidor geral em socorrê-los, encontravam sempre algum impedimento por parte de Martim Carvalho. Em agosto daquele ano, uma pequena comitiva com suprimentos aportava no forte, servindo mais como um paliativo do que qualquer outra coisa, assim como no final do ano, quando expulsaram duas naus francesas e reprimiram invasões nativas, o que deu alento aos cansados moradores do forte.</p>
        <p className="paragraphy">Entretanto, a chegada do célebre e valente Piragibe, o ‘Braço de Peixe’, líder da tribo Tabajara (veja quadro 1 para conhecer sua biografia), aliando-se aos potiguaras, era mais um péssimo sinal aos portugueses<sup>19</sup>. A linha demarcatória da povoação destas duas etnias, acordado entre eles, seria o Rio Paraíba: os potiguaras continuariam ocupando a margem esquerda, até a Serra de Copaoba (atual Serra da raiz), em direção ao Rio Grande; os tabajaras se estabeleceriam na margem direita, com liberdade para se expandirem até Pernambuco (ALMEIDA, 1978, op. cit., p. 75).</p>
        <p className="paragraphy">Em fins de janeiro de 1585, apesar de aumentar os reforços na edificação do forte, os nativos se aproximavam cada vez mais de um ataque definitivo. Assim, mais uma vez, Fructuoso Barbosa foi apelar por ajuda em Pernambuco. Desta vez, numa rara ocasião de consenso, foi prontamente ouvido por Martim Leitão. Durante dois meses, foi organizada uma comissão de grande porte, com mais de quinhentos homens, a qual o próprio Martim Leitão participou, e com recursos próprios financiou esta que seria a sua primeira para a Paraíba. Para Itamaracá e Olinda, esta expedição teria que ser definitiva, pois milhares de índios cercavam o forte e o destino de duas capitanias estaria fortemente interligado ao resultado na frente de batalha. Neste momento a personalidade política e pragmática de Martim Leitão aflorava.O deslocamento até a Paraíba havia sido penoso, e a expedição por terra, capitaneada por Francisco Barreto não tardou em encontrar uma cerca, na margem direita do rio Tibiri, protegendo três mil nativos tabajaras. Após uma peleja homérica, os índios se dispersaram para o interior e os soldados de Barreto se empanturraram com os mantimentos que encontraram no lugar.</p>
        <div className="text-center">
            <a href={indios_conversa}><img src={indios_conversa} alt="CONVERSANDO" /></a>
        </div>
        <p className="paragraphy">Martim Leitão, reconhecendo a participação de Piragibe nos eventos da noite anterior, tentou um acordo de paz com o líder tabajara, enviando para o acampamento tabajara o padre Jeronimo Machado e outros que falavam a língua de Piragibe.</p>
        <p className="paragraphy">Machado (1977a) descreve as vantagens deste acordo para as capitanias de Itamaracá e Pernambuco e para a conquista e povoamento da Paraíba.</p>
        <p className="paragraphy-modifded">“Não era somente arredar dos potyguaras tão valioso auxiliar, era introduzir entre elles a desmoralisação, incitando-os á deixarem a vida nos bosques e à procurarem a sociedade, onde iriam achar provas em contrário do que dos portugueses lhe diziam os franceses; era arredar e mesmo nullificar a influencia destes; era pelo menos fazer trocar os papeis que nesta luta representavam os tobayaras, fazendo com que estes fossem os guardas avançadas dos portugueses em vez de serem dos potyguares” (MACHADO, 1977a, op. cit., p. 71).</p>
        <p className="paragraphy">Entretanto, este acordo teria que ser adiado por mais alguns meses. A presença de potiguaras infiltrados na tribo ou a desconfiança de Piragibe que já havia sido traído pelos portugueses fez com que a reunião que selaria o acordo de paz se transformasse em um campo de batalha.</p>
        <div className="text-center">
            <a href={jogados}><img src={jogados} alt="JOGADOS" /></a>
        </div>
        <p className="paragraphy">Seguindo seu caminho, após alguns confrontos com tabajaras e potiguaras, a delegação chegou ao forte, que o autor do ‘Sumário’ descreve como “[...] cousa piadosa de se ver assim o danificamento com as peçoas [...] que bem mostravão a fome   e mizerias que tinhão pasado com as ruínas que por ser de taipa [...]” (SUMMARIO, 1848, op. cit., p. 57). Martim Leitão tentara persuadir Fructuoso Barbosa a seguir com ele e mais oitenta homens algumas léguas a montante para fundar o povoamento em um sítio alto que havia considerado bom e aprazível. Barbosa, entretanto, apresentava um estado de espírito tão desalentador e um moral tão baixo que, mesmo com a insistência do Ouvidor- geral, dissera que perdeu as esperanças de fundar esta povoação a qual governaria. Apenas uma aliança com os tabajaras poderia reverter o atual miserável quadro.</p>
        <p className="paragraphy">E esta aliança era iminente. O autor do Sumário cita a insatisfação por parte dos potiguaras com o comportamento de Braço de Peixe, no encontro com o branco às margens do rio Tibiri.</p>    
        <p className="paragraphy-modifded">“[...] por certo que os Tabajaras do gentio Braço de Peixe e Pitiguares por causa das rotas que lhes tinhamos dado nesta jornada estavão já desavidos de todo e os Pitiguares havia quebrado a cabeça a alguns tabajaras dizendo que eram manemos que quer dizer fracos e que não os havião defendido de nos como lhes tinhão prometido e estavam obrigados por terem tomado e aposento as nosas fronteiras [...] antes com ver muito por alguha via avisar o Braço de Peixe que lhe dariamos socorro contra os Pitiguares” (SUMMARIO, 1848, op. cit., p. 59- 60).</p>
        <p className="paragraphy">Machado (1977a, op. cit., p. 74), por sua vez, sem citar a fonte, descreve o aprisionamento de dois potiguaras durante o trajeto para o forte, e o anúncio, por parte deles, de que sua tribo estava inconformada com a tentativa de acordo de paz dos tabajaras com os portugueses<sup>20</sup>.Assim, a partir dali, os tabajaras haviam se tornado inimigos dos potiguaras. Esta informação causou alento a Martim Leitão, pois ter um aliado como os tabajaras, nesta altura, seria um feito de suma importância se os portugueses quisessem levar adiante a conquista da Paraíba.</p>
        <p className="paragraphy">As péssimas condições sanitárias do lugar colocaram abaixo parte da comitiva de Martim Leitão, que foi obrigado a enviar os doentes de volta a Olinda. Fazia um ano que o forte havia sido fundado e nada mudara. Não se vislumbrava a possibilidade de povoamento, visto que os investimentos para tal requereriam muitos gastos e a situação em Olinda não era das melhores. Ainda assim, Martim leitão e seus asseclas abasteceram com provisões o forte, realizaram algumas investidas contra potiguares nos arredores e retornaram, para Olinda em março de 1585, nomeando Pero Lopes substituto de Fructuoso Barbosa. Afinal, abandonar o forte não seria o melhor negócio. A conquista da Paraíba ainda não havia ocorrido.</p>
        <p className="paragraphy">O forte de São Filipe e São Tiago, mesmo nas condições em que se apresentava, era a barreira de proteção que os moradores de Itamaracá e Olinda tinham apreço. Este forte resguardava a região da posse dos potiguaras, impedia o contrabando de pau-brasil pelos franceses, assim como o avanço dos nativos mais para sul, onde estavam as duas capitanias supracitadas. Em junho de 1585, quando Martim Leitão recebeu a notícia de que o alcaide Castrejon havia abandonado o forte à própria sorte, não sem antes incendiá-lo, a população de Itamaracá e Pernambuco se alvoroçou. Novamente com recursos próprios, o Ouvidor- geral convidou Fructuoso Barbosa para esta empreitada, que declinou. O Capitão Simão Falcão aceitou, mas às vésperas da viagem adoeceu. Parece que o forte ficaria desguarnecido e era questão de tempo para que ele fosse tomado<sup>21</sup>.</p>
        <div className="text-center">
            <a href={castelochamas}><img src={castelochamas} alt="CHAMAS" /></a>
        </div>
        <p className="paragraphy">Neste exato instante, em Olinda, se aproximavam, estafados, dois índios tabajaras à procura de ajuda para Piragibe. A sua aldeia, na margem direita do Rio Tibiri, estava cercada, há meses, por centenas de potiguaras. Este pedido de socorro era respostas às orações de Martim Leitão. Sem perder tempo, se dirigiu a Recife para encontrar-se com João Tavares (leia a biografia no quadro 1), Escrivão da Câmara e Juiz dos Órfãos, responsável por formar uma comitiva com doze espanhóis e oito portugueses que, em uma caravela equipada, partiram do porto de Pernambuco no dia 02 de agosto de 1585 em direção à Paraíba, para encontrar-se com Piragibe. </p>
        <p className="paragraphy">Após espantar alguns potiguaras na margem do rio à tiros de espingarda, o encontro se deu algumas milhas adentro da barra do Rio Paraíba, na margem direita, aos pés de uma pequena elevação planáltica, nas proximidades da aldeia tabajara, no dia 05 de agosto de 1585, dia de Nossa Senhora das Neves. O local de encontro foi escolhido como sítio de povoamento da sede do governo e Nossa Senhora das Neves o nome da cidade, em homenagem a padroeira do dia do aperto de mãos que selou a paz entre os portugueses e tabajaras, entre João Tavares e o líder Piragibe, aliança que propiciou, finalmente, a tão desejada conquista da Paraíba.</p>
        <div className="text-center">
            <a href={acordo}><img src={acordo} alt="ACORDO" /></a>
        </div>
        <p className="paragraphy">O gráfico abaixo (figura 1) representa um resumo desta fase inicial de evolução e conquista do território da Parahyba, nas décadas que antecederam a fundação da cidade de Nossa Senhora das Neves, atual João Pessoa. Esta evolução, que resultou na conquista do território, sofreu, e provocou, estímulos provenientes de regiões próximas e até distantes, estímulos denominados “indutores da evolução urbana”, podendo ser traduzidos por fatores populacionais, econômicos, sócio-culturais, político-institucionais ou locacionais, ocasionando uma diversificação da função urbana à medida que estes fatores se interelacionam com o território em questão (SOUZA, 1998, p. 99).</p>
        <figurecaption className="figure-caption">Figura 1 - Indutores da evolução urbana nas décadas que antecederam à conquista de Nossa Senhora das Neves.</figurecaption>
        <div className="text-center">
            <a href={tabela_cidade}><img src={tabela_cidade} className="img-fluid" alt="TABELA DA CIDADE" /></a>
        </div>
        <hr />
        <span className="text-justify">
            <sup>1</sup>Estes relatos iniciam com a Carta de Pero Vaz de Caminha, perpassando por Ambrósio Brandão (cf. BRANDÃO, A. F., 1977, op. cit.), Gabriel Soares de Sousa (SOUSA, G. S. 1879, op. cit.), SUMÁRIO DAS ARMADAS (SUMMARIO, 1848) E GANDAVO (GANDAVO, P. de M.. Tratado da Terra do Brasil. História da Província Santa Cruz. Belo Horizonte: Ed. Itatiaia; São Paulo: Edusp, 1980), entre outros. <br />
            <sup>2</sup>O autor sugere que a morte de João Gonçalves tenha ocorrido em meados dos anos 1540; entretanto, documentos do Arquivo Público Estadual (1951), apontam que a doação da sesmaria a Diogo Dias, datada de 01 de janeiro de 1570, foi assinada por “João Gonçalves, capitão nesta ilha de Itamaracá pela Senhora d. Jerônima d’Albuquerque e Sousa”. <br />
            <sup>3</sup>Para mais detalhes deste episódio cf. STADEN, H.. Duas viagens ao Brasil. São Paulo: Beca, 2000, p. 32- 33. <br />
            <sup>4</sup>Um dos poucos historiadores que divergem desta versão é Maximiano Lopes Machado. Segundo ele, o massacre teria sido consequência de uma tentativa do comerciante e agricultor de fundar um engenho às margens do rio Capibaribe-Mirim, atual Goiana, fronteira com as terras potiguaras, o que resultaria num novo ânimo para que outros moradores de Itamaracá também fizessem o mesmo. Assim, insuflados pelos aliados franceses, que prevendo prejuízos na economia do pau-brasil, posteriormente substituído pela cana-de-açúcar, os potiguares iniciaram uma série de ataques, sendo o último a carnificina que, segundo Machado (1977a, op. cit., p. 44- 45), resultou em mais de 600 mortes. <br />
            <sup>5</sup>Não há unanimidade, entretanto, entre os historiadores, da data de fundação da capitania real da Parahyba. A maior parte da historiografia paraibana defende o ano de 1574, mesmo sem uma fonte primária comprobatória. Gonçalves (2007, p. 67), por outro lado, acredita que o despojamento das 23 léguas que formaram a capitania Real da Parahyba teria ocorrido em 1585, depois de efetivada a conquista da Paraíba. Vamos ratificar a informação da maioria, optando pelo ano de 1574. <br />
            <sup>6</sup>Resumo da obra intitulada “Sumário das Armadas que se fizeram, e guerras que se deram na conquista do rio Paraíba; escrito e feito por mandado do muito reverendo padre em Cristo, o padre Cristóvão de Gouveia, visitador da Companhia de Jesus, de toda a província do Brasil”. <br /> 
            <sup>7</sup>MACHADO (1977a, op. cit., p. 47) e ALMEIDA (1978, op. cit., p. 63), entre outros historiadores paraibanos, sem citar fontes, acreditam que está armada nem teria saído de Recife. <br /> 
            <sup>8</sup>ALMEIDA (1978, op. cit., p. 95- 98) anda na contramão destes fatos, sendo enfático em afirmar que esta suposta expedição nunca tenha ocorrida, se embasando no autor do ‘Sumário’ que também não teria registrado este acontecimento. Por outro lado, frei Jaboatão (cf. JABOATÃO, 1858, op. cit., p. 156- 157), teria sido a fonte para as afirmações de Irineu Pinto, Maximiano Machado, Aires de Casal, Pereira da Costa, entre outros. <br />
            <sup>9</sup>Pinto (1977, op. cit., p. 15- 16) foi um dos poucos historiadores paraibanos que apresentam o ano de 1580 como o de partida da armada de Fructuoso Barbosa, condicionado, muito provavelmente, pela data do alvará que Fructuoso havia recebido (fins de novembro do ano anterior), assim como respaldado por outros documentos do Arquivo da Torre do Tombo, em Lisboa, aos quais faz referência mas não publica. Almeida (1978, op. cit., p. 64), por outro lado, também fazendo referência mas não publicando documento encontrado no Arquivo Histórico Português descoberto por Francisco Varnhagen, data de 25 de janeiro de 1579 o Alvará dado a Fructuoso Barbosa. <br />
            <sup>10</sup>Este aparato incluía mantimentos, soldados, munições, apetrechos, material de armazém, um vigário, religiosos franciscanos e beneditinos, segundo o autor do ‘Sumário das Armadas’. Entretanto, Irineu Pinto (1977, op. cit., p. 15) enfatiza, a partir da obra “Memorias Historicas”, escrita pelo frei Manoel de Sá, em 1724, que religiosos da Ordem do Carmo também teriam participado desta expedição. <br />
            <sup>11</sup>Durante o reinado de D. Sebastião (1568- 1578), o monarca considerou prioridade investir nas feitorias africanas. Acabou falecendo na batalha de Alcácer- Quibir, ao prestar auxílio ao sultão marroquino. Sucedeu-o o cardeal D. Henrique, que governou durante dois anos, quando, ao morrer, não possuía descendentes diretos. Assim, o rei da Espanha, Filipe II (ou I em Portugal), de parentesco com os falecidos, invade Portugal, assume o trono lusitano, une os dois países e dá início à União Ibérica, que durou até 1640 (cf. VICENTINO, C.; DORIGO, G. História Geral e do Brasil- volume 2. São Paulo: Scipione, 2010, p. 39- 40). Para se aprofundar neste episódio, sugerimos consultar ELLIOT, J. H. A Europa Dividida, 1559-1598. Tradução de Conceição Jardim e Eduardo Nogueira. Lisboa: Presença, 1985, p. 199- 204, SERRÃO, J. V. O Tempo dos Filipes em Portugal e no Brasil (1580- 1668). Lisboa: Colibri, 1994, p. 245- 260 e HOLLANDA, S. B. de. História Geral da Civilização Brasileira, 11. ed. Rio de Janeiro:Bertrand Brasil, 2000 (em especial o capítulo de Antonia Fernanda Wright intitulado O Brasil no Período dos Filipes, p. 176- 189). <br />
            <sup>12</sup>MACHADO (1977a, op. cit., p. 49) sustenta que este fracasso teria decorrido da imprudência por parte dos soldados espanhóis, que agora participariam do processo no contexto de União Ibérica e familiares de Fructuoso, incluindo seu filho, que foram vistoriar as redondezas sem a devida precaução e “atrahidos pelos encantos naturaes de uma luxuosa e variada vegetação”, resultou na morte do filho de Fructuoso (cf. também ALMEIDA, 1978, op. cit., p. 66). <br />
            <sup>13</sup>Esta vitória, assim como o efêmero povoamento na margem esquerda do rio, narrada por Maximiano Lopes e Horácio de Almeida, entre outros historiadores paraibanos, foi subtraída por Irineu Pinto, segundo o qual o colonizador retornou a Pernambuco logo nos primeiros sinais de derrota. <br />
            <sup>14</sup>O papel do Ouvidor-geral seria fornecer todos os recursos necessários para que a esquadra lograsse êxito nesta missão, enquanto o provedor da fazenda, neste caso, cargo nomeado particularmente pelo Governador, a pedido do padre D. Antonio Barreiros, amigo pessoal de Carvalho, forneceria o dinheiro para que estes recursos chegassem à esquadra. A história relata que, sempre que requisitado, o provedor mostrou má vontade na liberação de recursos, o que gerou muitas desavenças, especialmente com Martim Leitão. <br />
            <sup>15</sup>Machado (1977a, op. cit., p. 58) sugere a hipótese de que a escolha desta margem tenha relação com a dificuldade de possíveis futuras deserções dos soldados, uma vez que eles teriam que atravessar o rio, profundo e largo, para se dirigir à Itamaracá ou Olinda. Assim, estava “segura a defesa dos povoadores pela necessidade quando não fosse pelo dever”, repetindo o que escrevera Salvador (2010, op. cit, p. 285) dois séculos antes. <br />
            <sup>16</sup>Posteriormente, Martim Leitão recebeu uma carta régia afirmando que “e vós me escreveis a causa que ouve para Diogo Flores de Valdez ordenar o forte que se largou então diferente lugar do q em q o mandaram fazer como verei pelo capítulo do regimento que levou Fructuoso Barbosa”, o que confirma a posição correta de edificação do forte como a margem direita da foz do Rio Paraíba (cf. Ministério do Reino, Colecção de plantas, mapas e outros documentos iconográficos, doc. 58, Torre do Tombo, referência PT-TT-CC-1-112-3_m0058, original em anexo). <br />
            <sup>17</sup>Denominação comum para o Comandante do forte (cf. JABOATÃO, A., 1848, op. cit., p. 159). Esta escolha contraria Fructuoso Barbosa, e a relação entre ele e o alcaide irá se deteriorar cada vez mais. <br />
            <sup>18</sup>No ápice da crise de alimentos, comeram os cavalos!!! <br />
            <sup>19</sup>Residentes tradicionais da Paraíba, entre o Rio Goiana e a Ilha de Itamaracá, a etnia tabajara havia sido expulsa pelos potiguaras e fixado residência às margens do Rio São Francisco, na fronteira Pernambuco- Bahia. Vivia em paz com os portugueses, até ser traído por eles. Horácio de Almeida conta que, durante o governo do segundo donatário de Pernambuco, Duarte Coelho de Albuquerque, a relação portugueses x tabajaras chegara ao máximo de hostilidade, onde os índios eram traficados como bichos (cf. ALMEIDA, H., 1978, op. cit., p. 74- 75). Em 1573, Francisco de Caldas e Gaspar de Ataíde, comerciantes de índios, adentraram no sertão para mais uma aventura de aprisionamento, tendo encontrado Piragibe e sua tribo, que acabou por tornarem-se aliados. Depois de cativarem mais de sete mil índios, com o apoio de Piragibe, os dois comerciantes, não se dando por satisfeitos, resolveram aprisionar também o chefe tabajara e os seus. Entretanto, desconfiado desta possibilidade, com a ajuda de seu parente Guirajibe, os índios arremetem-se contra os portugueses, resultando em uma sangrenta carnificina. Uma vez soltos os índios cativos, e receosos de uma represália por parte dos portugueses, os tabajaras resolvem retornar para a Paraíba (cf. GUERRA, F. História de Pernambuco. 2ª. Ed. Recife: ALEPE, 1979, p. 39). <br />
            <sup>20</sup>Regina Célia Gonçalves, por sua vez, afirma, sem citar fontes, que a inimizade criada entre potiguares e tabajaras foi implantada por boatos infundados pelos portugueses que, através de seus “espias, [...]se encarregaram de disseminar a versão de que os tabajaras haviam facilitado as coisas para os portugueses, permitindo que os mesmos conquistassem a margem sul do Rio Paraíba e, mais ainda,indicando-lhes os melhores roteiros para chegarem com maior facilidade a Acejutibiró, a Baia da Traição, onde os homens de Martim Leitão fizeram grandes estragos nas aldeias e roçados dos potiguaras.” (cf. GONÇALVES, R. C., 2007, op. cit., p. 81- 82). <br />
            <sup>21</sup>Machado (1977a, op. cit., p. 84), na contramão dos fatos narrados no ‘Summario’, argumenta que Fructuoso Barbosa aceitou se deslocar para o forte, tendo a companhia de Pero Lopes. Lá, encontraram o prédio em ruínas mas conseguiram expulsar os nativos e reerguer, provisoriamente, o lugar. <br />
        </span>
       </>
    )
}

export default Antecedentes;