import turismo1 from './media/turismo1.png';



export function Turismo(){
    return(
        <>
        <h5>Uma visão geral</h5>
        <p class="paragraphy">O <b>Estado da Paraíba</b> é um dos mais pobres do país. Segundo dados do IBGE de 2012, quando o PIB do Brasil foi de R$ 4.403 trilhões, o do Estado da Paraíba alcançou apenas 0,8%, ou seja, R$ 38,731 bilhões. João Pessoa, o município com o melhor PIB no Estado, 29% do total, ocupa a 57ª posição dos municípios brasileiros. A tabela 1 reflete os dados do PIB e o papel dos setores da economia em João Pessoa, entre 2006 e 2012, assim como sua posição no ranking dos 223 municípios do Estado.</p>
        <p class="paragraphy">Uma informação relevante presente no quadro acima é a participação dos setores econômicos no PIB. O fenômeno da terciarização mostra-se marcante, seguindo o padrão nacional. Já a participação do setor primário aumenta substancialmente em direção ao litoral sul, diretamente proporcional ao afastamento da capital. No caso de João Pessoa e Cabedelo, por não possuírem zona rural, o setor secundário e terciário respondem quase que totalmente por estes valores, essencialmente o setor de serviços. Em <b>João Pessoa</b>, o centro de dinamismo econômico do Estado, as atividades de maior relevância são os segmentos do comércio e serviços de manutenção, imobiliárias e aluguéis, intermediação financeira e o da administração pública, com participação mais expressiva. Na capital, se localiza o maior distrito industrial do Estado, com mais de 200 fábricas com todo o tipo de produção. As atividades da indústria de transformação, de distribuição de eletricidade e de construção civil contribuem com expressivo peso, também para a economia estadual.</p>
        <div class="text-center">
            <figure class="figure">
                <figurecaption class="figure-caption">Tabela 1 - Dados econômicos de João Pessoa (de 2006 a 2012)</figurecaption><br />
                <a href={turismo1}><img src={turismo1} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">RPC-Renda per capita, P - Primário, S - Secundário, T - Terciário. Fonte: IBGE.</figurecaption>
            </figure>
        </div>
        <p class="paragraphy">Convém salientar que o IBGE considera pertencente à População Economicamente Ativa (PEA) aqueles com mais de 10 anos de idade e que esteja efetivamente trabalhando (ocupado) ou desempregado até um ano (desocupado), formais ou não. Assim, segundo o Censo 2010, a participação da PEA no total demográfico em João Pessoa foi de 49%.</p>
        <h5>A atividade turística</h5>
        <p class="paragraphy">O setor que conecta e incrementa a economia em toda a área é o de turismo, aproveitando uma diversificação cultural e natural muito singular. Convém lembrar que o contexto aqui utilizado para definir ‘turismo’ transcende os aspectos econômicos, incluindo os sociais, culturais e ambientais, buscando equilibrar o desenvolvimento com a proteção ambiental e a cultura local, dentro da ótica da sustentabilidade (CORIOLANO e SILVA, 2005).</p>
        <p class="paragraphy">Segundo Leal (2001), no governo Ivan Bichara, em maio de 1975, foi criado a Empresa Paraibana de Turismo S.A. (PBTur), atualmente vinculada à Secretaria de Turismo e Desenvolvimento Econômico do Estado, com o objetivo principal de desenvolver a política de marketing e divulgação do destino turístico ‘Paraíba’.  O litoral paraibano, em especial o litoral sul, tem recebido incentivo governamental com maior robustez, desde o final dos anos 1980, com o projeto Cabo Branco, e do início dos anos 1990, com o <b>Programa de Ação para o Desenvolvimento do Turismo no Nordeste</b> (PRODETUR-NE), na Paraíba separado em duas etapas: etapa I, de 1994-1999 e etapa II, de 1999 em diante, que visavam desenvolver a infraestrutura, incentivando investimentos privados da rede hoteleira, por exemplo. Trata-se de um programa de crédito para o setor público, com o intuito de “gerar condições favoráveis à expansão e melhoria da qualidade da atividade turística no Nordeste, melhorando também a qualidade de vida das populações residentes nas áreas beneficiadas”, financiado pelo Banco Interamericano de Desenvolvimento (BID) e executado pelo Banco do Nordeste (MOURA, 2008, p. 67).</p>
        <p class="paragraphy">Em 1994, o documento “Estratégia para o Desenvolvimento da Atividade Turística no Estado da Paraíba” marca o início das negociações do Governo do Estado com o Banco do Nordeste e define eixo litorâneo e o eixo interior como estratégicos para a dinamização da atividade turística no Estado. Com relação ao eixo litorâneo foram definidos dois “assentamentos turísticos”: o ‘Complexo Turístico Cabo Branco’ e o ‘Centro de Animação Tauá’. O primeiro, cujo locus seria a região sul do município de João Pessoa, compreenderia o desenvolvimento de uma estrutura hoteleira e a implantação de 2700 unidades habitacionais, numa área de 507 ha. O segundo, localizado no litoral sul do Estado, tendo o município do Conde como base, com uma área de 200 ha, daria ênfase ao desenvolvimento de equipamentos para a prática de esportes, aventura e cultura da saúde e do corpo, com implantação de 250 unidades habitacionais (MOURA, 2008). Em ambos os “assentamentos”, o patrimônio natural, em especial o geopatrimônio, numa contextualização atualizada, foi o aspecto mais relevante, como falésias, piscinas naturais, recifes, praias, mangues, entre outros, entrelaçados com o patrimônio cultural, em especial o de João Pessoa. Posteriormente, o PRODETUR-NE relegou o eixo interior para segundo plano, considerando apenas o eixo litorâneo (BANCO DO NORDESTE, 2005), com ênfase especial no setor de transportes e saneamento básico. Como a Paraíba não foi signatária do PRODETUR II, ficou excluída dos subsídios.</p>
        <p class="paragraphy">Em 2000, um novo plano foi colocado em prática pelo Governo do Estado, denominado ‘Plano Amanhecer’ ou ‘Plano Estratégico de Desenvolvimento do Turismo’, com o intuito, entre outras ações, de destravar o ‘Projeto Cabo Branco’, até então nunca efetivamente desenvolvido. Com a troca de governo, entretanto, foi engavetado e não teve continuidade.</p>
        <p class="paragraphy">Com a criação, no final dos anos 1990, da rodovia PB-008, que liga a capital ao litoral sul, o fluxo para essa área aumentou consideravelmente, incentivando a fixação de moradias do tipo ‘veraneio’, especialmente na Praia de Jacumã, de maneira desordenada, gerando inúmeros impactos negativos. A invasão frenética e anárquica de áreas de mangues por cabanas transformadas em bares, a ocupação irregular de solos marginais aos mananciais e a deterioração de reservas ambientais são alguns exemplos da má fixação da população. Soma-se a isto um fluxo turístico ‘de massas’, ávido por paisagens naturais mas sem a mínima consciência ambientalista, que resultou em impactos ambientais, alguns irreversíveis.</p>
        <p class="paragraphy">Segundo dados da Empresa Brasileira de Infraestrutura Portuária (INFRAERO) e da Agência Nacional de Aviação Civil (ANAC), presentes no Anuário Estatístico 2016, do Ministério do Turismo <sup>1</sup> , a movimentação nacional de passageiros em aeroportos do Brasil, no ano de 2015, foi de cerca de 95 milhões de passageiros. Na Paraíba, no mesmo ano, foi de 791 mil, participação pequena no fluxo nacional. Entretanto, cabe lembrar que nem todos se inserem na categoria de ‘turista’ que, segundo a OMT, são aqueles que não residem na região e irão permanecer nela por pelo menos 24 horas, com a finalidade de realizar passeios, negócios, participar de eventos, tratamento de saúde e/ou visitar parentes e amigos.</p>
        <p class="paragraphy">Em dezembro de 2015, segundo dados do mesmo anuário, cerca de 8,3 milhões de passageiros estrangeiros desembarcaram em aeroportos brasileiros. Na Paraíba, esse montante foi de 81.141 passageiros, ou seja, inexpressivo (inferior a 1%), enquanto nos estados vizinhos, Rio Grande do Norte e Pernambuco, a movimentação foi superior (130,5 mil e 326 mil, respectivamente). Quanto à movimentação nas estações rodoviárias do país, o fluxo foi de 46,1 milhões de passageiros no mesmo ano. Na Paraíba, o total foi de 427 mil (0,001% do total), ou seja, participação muito pequena.</p>
        <p class="paragraphy">O Fluxo Global de Turistas 2014, divulgado pelo Governo do Estado da Paraíba em seu site<sup>2</sup> , destaca o faturamento deixado pela atividade turística no Estado. O número de turistas no Estado foi de 1.649.965, que se hospedaram na rede hoteleira local, um aumento de 3,25% em relação ao ano anterior, com uma média geral de ocupação da rede hoteleira de 69%. Foram provenientes principalmente da região Nordeste (45,8%, em especial seus vizinhos Pernambuco e Rio Grande do Norte), seguido da Sudeste (33%), Centro-Oeste (10,5%), Sul (8,7%) e Norte (2%). O fluxo de turistas estrangeiros, no mesmo ano, aumentou 122% em relação a 2013, sendo os principais emissores Itália (17,5%) e Estados Unidos (11,3%).</p>
        <p class="paragraphy">Entre os dias 26 de dezembro de 2013 e 15 de janeiro de 2014, o Instituto Fecomércio de Pesquisas Econômicas e Sociais da Paraíba (IFEP)<sup>3</sup>  entrevistou 602 turistas no Aeroporto Internacional Castro Pinto, em Bayeux, e na Estação Rodoviária da Capital, e em diversos pontos turísticos da Região Metropolitana de João Pessoa (RMJP).</p>
        <p class="paragraphy">No caso do IFEP, no período amostrado, o turista que circulou pela RMJP era maduro (73,3% acima de 26 anos), com um poder aquisitivo relativamente baixo (25% com renda inferior a 2 s.m), mas literato (41% com o curso superior completo). São trabalhadores de empresas públicas ou privadas (55,6%), provenientes principalmente da Região Nordeste (41%). A maioria chegou de avião (46,5%), acompanhado da família (54,1%), para passar pelo menos 10 dias em férias, se hospedando principalmente na casa de amigos ou parentes, não sendo sua primeira vez no Estado (66%). A tendência é que retornem, uma vez que aprovaram o que visitaram e o modo como foram tratados.</p>
        <p class="paragraphy">Segundo a pesquisa, as belezas naturais das praias foram a grande motivação para a escolha desse destino. Os principais pontos de visitação (sublinhados os locais onde a geodiversidade e o geopatrimônio têm maior peso), em ordem decrescente, foram o Mercado de Artesanato, o Farol de Cabo Branco, Pôr-do-sol da Praia do Jacaré, a Estação Ciência, Hotel Tambaú, Parque Solon de Lucena, Centro Histórico, Areia Vermelha, Fortaleza de Cabedelo, Igreja de São Francisco, Centro de Convenções, Feirinha de Tambaú, Picãozinho, Praça dos Três Poderes, Parque Arruda Câmara, Mosteiro de São Bento, Teatro Santa Roza, Casa do Artista Popular, Igreja Nossa Senhora da Guia (em Lucena), Pedra do Reino, Mata do Buraquinho, Cânion do Coqueirinho, Capela de Nossa Senhora da Penha, Templo da Igreja Universal e Espaço Cultural.</p>
        <p class="paragraphy">Os vários pontos de visitação sublinhados fazem parte da geodiversidade e do geopatrimônio, seja direta ou indiretamente, além de uma série de edificações que foram incluídas no roteiro geoturístico proposto nesta tese, uma vez que possuem georecursos que possibilitam demonstrar a geodiversidade <i>ex situ </i>da região, entrelaçando a história geológica e cultural da Capitania da Parahyba.</p>
        <p class="paragraphy">Se o turismo de sol e mar foi o grande motivador da escolha e secundariamente o turismo cultural no Centro Histórico, há uma clara possibilidade da transferência dessas atividades em direção ao geoturismo urbano e costeiro, considerando a presença de elementos abióticos para tal. Dada a importância da atividade turística para a área de pesquisa, a elaboração do Guia Geoturístico proposto nesta tese servirá como uma tentativa de colaboração para o incremento do turismo em João Pessoa e região.</p>
        <hr />
        <span>
            <sup>1</sup>  MINISTÉRIO DO TURISMO. Dados e fatos. Disponível em <a href="http://www.dadosefatos.turismo.gov.br/dadosefatos/anuari">http://www.dadosefatos.turismo.gov.br/dadosefatos/anuario Acesso em 24 abril 2016.</a><br />
            <sup>2</sup>  PARAÍBA. Paraíba apresenta crescimento de turistas em 2014. Disponível em <a href="http://www.paraiba.pb.gov.br/">http://www.paraiba.pb.gov.br/</a> Acesso em 28 abril 2015.<br />
            <sup>3</sup>  INSTITUTO FECOMERCIO DE PESQUISAS ECONÔMICAS E SOCIAIS DA PARAÍBA – IFEP. Pesquisa Anual do Desempenho do Turismo na Região Metropolitana de João Pessoa- Pesquisa realizada junto aos turistas, ano 2014. Disponível em www.fecomercio-pb.com.br/index. Acesso em 24 abril 2015 Acesso em 12 abril 2015. <br />
        </span>
        </>
    )
}