import evolução1 from './media/evolução1.png';
import evolucao from './media/evolucao.png';





export function Evolucao(){
    return(
        <>
        <p class="paragraphy">As bacias marginais costeiras são divididas em Sergipe-Alagoas, Pernambuco, Paraíba, Potiguar e Barreirinhas. Sua formação tem relação direta com a deriva continental que separou os continentes africano e sul-americano, sendo a <b>Bacia da Paraíba</b> a última a manter contato com a África. A área desta tese insere-se inteiramente na Bacia da Paraíba, uma das bacias nordestinas pertencentes às bacias marginais brasileiras, denominadas de <b>Província Costeira</b> (Almeida et al., 1977). Para este trabalho, serão considerados os limites da Bacia da Paraíba, do Lineamento Pernambuco ao Lineamento Paraíba<sup>1</sup> . Na literatura, esta bacia fez parte, até meados dos anos 1990, da Bacia Sedimentar Costeira de Pernambuco-Paraíba<sup>2</sup> , quando foi proposta uma separação, por Lima Filho (1998) em duas bacias, Pernambuco e Paraíba, por apresentarem origem, evolução e distribuição das formações distintas, tendo o Lineamento Pernambuco como elemento limitador. Até hoje a delimitação do contorno das bacias Paraíba-Pernambuco-Potiguar não é consensual, assim como também são polêmicas as discussões acerca da coluna estratigráfica e da história evolutiva.</p>
        <p class="paragraphy">A figura 1 mostra a porção nordestina de algumas bacias marginais, localizando a <b>Bacia da Paraíba</b> entre a Zona de Cisalhamento Pernambuco e a Falha de Mamanguape. Esta bacia é subdividida, de sul para norte, em sub-bacias: Olinda, Alhandra (onde se localiza nossa área de estudo) e Miriri. Faz limites: a norte, com a Plataforma de Natal da Bacia Potiguar, através do Lineamento Paraíba, que se alonga através da Falha de Mamanguape; a sul, com a Bacia de Pernambuco, através do Lineamento Pernambuco; e, a oeste, com o embasamento cristalino. Esta será a configuração que será seguida nesta tese.</p>
        <div class="text-center">
            <figure class="figure">
                <a href={evolução1}><img src={evolução1} alt="" class="img-fluid" /></a><br /> 
                <figurecaption class="figure-caption">Figura 1 - Mapa de localização das bacias marginais brasileiras nordestinas, com a posição da área do projeto (em vermelho). Fonte: modificado de Barbosa e Lima Filho (2006).</figurecaption>
            </figure>
        </div>
        <p class="paragraphy">Todas as propostas evolutivas a seguir apresentadas, para a faixa sedimentar entre Recife e Natal, abrangendo, portanto, a <b>Bacia da Paraíba</b> e a porção leste da Bacia Potiguar, foram elaboradas a partir de um somatório de dados obtidos de estudos geofísicos, investigações paleoecológicas e paleontológicas, estudos de campo, estratigrafia, sedimentologia, entre outros, por diversos autores. Entretanto, é conveniente ressaltar que, das bacias marginais, a Bacia da Paraíba é uma das menos estudadas.</p>
        <p class="paragraphy">Após o advento da <b>Teoria das Placas Tectônicas</b>, nos anos 1970, se intensificaram as propostas explicativas para a dinâmica da deriva continental, especialmente entre as placas sul-americana e africana, e acerca das consequências tectônicas deste evento, como a expansão do assoalho oceânico, a abertura do Oceano Atlântico e, pertinente à nossa área de pesquisa, a formação das bacias sedimentares marginais costeiras do Brasil.</p>
		<p class="paragraphy">Naquela década, havia certa unanimidade entre os cientistas internacionais de que a separação da América do Sul e da África, com a completa abertura do Oceano Atlântico, sem uma conexão retardada, teria ocorrido no Cretáceo Inferior<sup>3</sup>. O Nordeste brasileiro seria o último elo entre as duas placas. A partir de estudos executados no Brasil, esta idade começou a ser questionada, por meio de informações que envolviam paleontologia, geofísica e sedimentologia (BEURLEN, 1971; TINOCO, 1971) onde, até ao Cretáceo Superior, haveria um elo, na forma de uma “<b><i>land bridge</i></b>” entre os dois continentes (RAND, 1976; RAND e MABESOONE, 1982).</p>
        <p class="paragraphy">Segundo Rand e Mabesoone (1982), antes do início da separação África-América do Sul, na região onde posteriormente se formaria a Bacia da Paraíba, provavelmente já existia um sistema de falhamentos, com direção E-W, que cruzava ambos os continentes, como o Lineamento Pernambuco, por exemplo, ainda no Cretáceo Inferior. A partir da abertura do proto-oceano, a norte e a sul desta conexão entre eles, as falhas existentes, à medida que avançava a separação, facilitaram o deslizamento das placas, agindo como falhas transcorrentes, até ocorrer a ruptura da ponte, no Campaniano (83,6-72,1 Ma.) - Maastrichtiano (72,1-66 Ma.). A partir daí, as falhas transversas alteraram-se para falhas transformantes e o Oceano Atlântico Equatorial se uniu ao Atlântico Sul, no Cretáceo Superior<sup>4</sup>.</p>
        <p class="paragraphy">Antes do rompimento desta ponte, durante o Jurássico-Cretáceo, segundo Asmus (1975) e Porto e Asmus (1978), adaptando seu modelo evolutivo para a Bacia da Paraíba, no chamado estágio pré-rift, ocorre um intumescimento pré-vulcânico e estiramento da crosta continental, com posterior falhamento em blocos e subsidência, numa mistura de fatores tectônicos e eustáticos (LIMA FILHO, 1998; LIMA FILHO et al., 2005), formando as bacias intracratônicas marginais e o sistema de horsts-grabens que as caracteriza e que será devidamente analisado no próximo subcapítulo.</p>
        <p class="paragraphy">Com a estabilização do embasamento, à medida que a divergência de placas avança, a crosta adelgaçada e fraturada do litoral nordestino resfria e o terreno afunda, no final do Turoniano (93,9-89,8 Ma, sensu PETRI, 1987; FEITOSA et al., 2002), ao longo de planos de falhas previamente formados, gerando uma rampa homoclinal e escalonada, suavemente inclinada para leste, enquanto a Bacia de Pernambuco se soergue (PETRI, 1987; LIMA FILHO et al., 2005). O Alto de Mamanguape serve como uma barreira que limita a Bacia da Paraíba, ao sul, com a Plataforma de Natal, a norte (FEITOSA et al., 2002).</p>
        <p class="paragraphy">No Santoniano-Campaniano Inferior, inicia-se a deposição na Bacia da Paraíba, em uma região deprimida, com sedimentação clástica das <b>Formações Beberibe</b> e, posteriormente, <b>Itamaracá</b>, típicos de ambiente costeiro (continental-estuarino) e transicional-marinho, respectivamente (AMARAL et al., 1977), formando-se uma cunha clástica continental. Asmus (1975) propõe que este preenchimento tenha se iniciado bem antes, no Aptiano (125-113 Ma), enquanto Lima Filho (1998) e Lima Filho et al. (2005) propõem o Conaciano (89,8-86,3 Ma) como o início da sedimentação, representando um evento marinho regressivo, o que mostra que, apesar dos intensos estudos executados no âmbito da evolução da bacia, a polêmica permanece.</p>
        <p class="paragraphy">No início do Campaniano vai ocorrer uma rápida submersão da bacia, resultado da subsidência do terreno que se estende do Alto de Mamanguape ao Alto de Touros, registrado pelo avanço da paleolinha de costa verificado em perfis de poços e em afloramentos (BARBOSA et al., 2003). Falhas antigas são reativadas e novas são geradas, inclusive submergindo o Alto de Mamanguape. Posteriormente, com a submersão bastante rápida, misturam-se os sedimentos clásticos da <b>Formação Beberibe</b> e da <b>Formação Itamaracá</b> com siltitos e arenitos de ambiente lacustre costeiro. Neste instante, os sedimentos clásticos carbonatados das áreas mais altas do sul teriam recoberto os sedimentos clásticos continentais da <b>Formação Beberibe</b>, na Bacia da Paraíba. Considera-se, portanto, um grande evento evolutivo que teria se disseminado por toda esta costa leste. Feitosa et al. (2002) sugerem a denominação de Bacia Costeira Pernambuco-Paraíba-Rio Grande do Norte para esta área que se estende da Zona de Cisalhamento Pernambuco ao Alto de Touros.</p>
        <p class="paragraphy">Convém salientar que, em pesquisas de campo, a exígua presença da sequência clástica da <b>Formação Beberibe</b> e da <b>Formação Itamaracá</b> nas proximidades da área da tese, porção norte da Bacia da Paraíba, em relação à abundância desta sedimentação na sub-bacia Olinda, nas proximidades de Recife, possibilita inferir que o comportamento da paleolinha de costa durante esta fase inicial de subsidência foi irregular (AMARAL et al., 1977). Foram encontrados alguns afloramentos de rochas da <b>Formação Beberibe</b> ao longo das vertentes do Rio Mumbaba, tendo sido selecionado um deles como Local de Interesse: Afloramento da Formação Beberibe.</p>
        <p class="paragraphy">Num primeiro momento, o mar invade apenas as sub-bacias ao norte, Miriri e Alhandra. Aos poucos, a sub-bacia Olinda é submersa, enquanto a transgressão atingiu quilômetros continente adentro nas sub-bacias do norte. A deposição fosfática nas proximidades de João Pessoa está bem mais afastadas da linha de costa do que nas proximidades de Recife, indicativo que o mar avançou muito mais nesta porção da bacia, o que corrobora a possibilidade da porção sul da bacia estar mais alta que a centro-norte. Todas estas informações foram confirmadas com amplo estudo de testemunhos de sondagens ao longo da costa em questão por vários autores, a exemplo de Souza (2006) e Barbosa (2007).</p>
        <p class="paragraphy">No final do Campaniano-Maastrichtiano Inferior, deposita-se uma camada métrica de fosforitos que recobrem a <b>Formação Itamaracá</b>, fora da área da tese, representando o máximo de submersão da bacia, denominada Superfície de Inundação Máxima, em um ambiente redutor e com presença de matéria orgânica e argilominerais, onde há uma redução significativa no aporte de sedimentação siliciclástica.</p>
        <p class="paragraphy">A Superfície de Inundação Máxima representa a substituição de um trato de sistema transicional continental-marinho, com a deposição da sedimentação clástica das <b>Formação Beberibe</b> e <b>Formação Itamaracá</b> para a sedimentação carbonática da <b>Formação Gramame</b>, já em ambiente marinho, que perdurará por todo o Maastrichtiano (LIMA FILHO e SOUZA, 2001). Este horizonte fosfático não foi depositado a norte do Alto de Mamanguape, no litoral leste do Rio Grande do Norte, o que pode ser representativo de que aquela área estava topograficamente mais elevada que a porção sul, não possibilitando a submersão pelas águas oceânicas a ponto de a Superfície de Inundação Máxima atingir uma grande extensão.</p>
        <p class="paragraphy">A deposição fosfática é resultado da diminuição do aporte sedimentar, onde os sedimentos clásticos dificilmente chegam ao interior da bacia (MENOR et al., 1977; MENOR e AMARAL, 1979; LIMA FILHO et al., 1998; SOUZA, 1999; LIMA FILHO e SOUZA, 2001; BARBOSA, 2004; SOUZA, 2006). O clima quente e seco (PETRI, 1987) favoreceu esta diminuição de sedimentação clástica, associado ao influxo de correntes de ressurgência (upwelling) que aumentaram a ação de algas e organismos bentônicos, responsáveis por fixar o fósforo sobre o substrato (MABESOONE, 1981). 
        </p>
        <p class="paragraphy">Como referido anteriormente, iniciou-se a deposição da <b>Formação Gramame</b>, já sob influência do Thetys e Oceano Atlântico Equatorial, uma vez que não existia mais ligação entre África e América do Sul (MAURY, 1930; OLIVEIRA, 1940; TINOCO, 1971; MUNIZ, 1993; CÓRDOBA et al., 2007). Durante todo o Maastrichtiano, o ambiente de sedimentação dos calcários então formados era de nível de mar alto, com não mais que 100-150 m de profundidade e calmaria tectônica. Ao final do Maastrichtiano, ocorreu um forte evento regressivo, influenciado pela queda do nível eustático (HAQ et al., 1988), que expôs e erodiu os calcários da <b>Formação Gramame</b>, principalmente nas sub-bacias do Norte (BARBOSA, 2004; BARBOSA, 2007; BARBOSA et al., 2003; CÓRDOBA et al., 2007), provavelmente concomitante a uma elevação tectônica desta porção.</p>
        <p class="paragraphy">Um dos grandes afloramentos da <b>Formação Gramame</b> na área, localizado na fábrica de cimento Intercement, foi selecionado como Local de Interesse: Afloramento da Formação Gramame, cujas fácies foram descritas, amostradas e analisadas em lâmina delgada.</p>
        <p class="paragraphy">No último estágio, a partir do Daniano (66-61,6 Ma), já em um contexto de ampla divergência de placas, a livre circulação das águas do oceano desenvolveu extensas plataformas carbonáticas onde, com as regressões e transgressões marinhas, se iniciou o estágio marinho franco. É representado na área pelos calcários da <b>Formação Maria Farinha</b>, associada a uma bacia do tipo Atlântico.</p>
        <p class="paragraphy">A sedimentação carbonática da <b>Formação Maria Farinha</b>, que sucede à Formação Gramame, foi depositada em um trato de sistema de mar baixo, representando um evento regressivo a partir do Paleoceno Inferior, ou seja, na passagem Cretáceo-Terciário. Esta sedimentação aflora mais abundantemente na sub-bacia Olinda, onde a deposição foi tardia, praticamente inexistindo nas sub-bacias Alhandra e Miriri, onde a transgressão chegou mais cedo. Na área da tese, na sub-bacia Alhandra, esta sequência aflora esporadicamente no litoral sul, em praias como Tambaba e Jacumã. Barbosa et al. (2003) sugerem que a inexistência ou restrição de depósitos do Paleoceno da <b>Formação Maria Farinha</b> na porção norte da bacia possa ser decorrência de sua não deposição ou da erosão desta sequência quando a plataforma foi exposta, no final do Maastrichtiano, pela regressão do nível do mar, ou que o terreno a norte da Falha de Goiana tenha sofrido um soerguimento, gerando a regressão forçada do nível do mar, que teria se estendido pelo Paleógeno (BARBOSA, 2007). Dois Locais de Interesse foram selecionados sobre esta unidade litoestratográfica (Pedra do Amor e Praia de Tambaba), por sua exclusividade na área e características texturais e estruturais, como feições de dissolução e abundância fossilífera.</p>
        <p class="paragraphy">O modelo evolutivo tratado neste subcapítulo até ao Cretáceo Superior pode ser sumarizado na figura 2. O resultado final da configuração da bacia é um sistema tafrogênico<sup>5</sup>  formando blocos desnivelados, por meio do soerguimento ou rebaixamento do terreno, definido como “<b>tectônica de teclas</b>” (FORTES, 1986), ao longo de planos de falhas perpendiculares à linha de costa, com sentido essencialmente NE e que será analisado a seguir. O modelamento exercido pelos fatores exógenos em períodos mais atuais resultou em um conjunto de formas de relevos de espetacular beleza, que possui qualidades geoturísticas intrínsecas.</p>
        <p class="paragraphy">Este subcapítulo abarcou informações acerca da geologia regional das bacias associadas à Paraíba que, durante algum tempo, salvo raríssimas exceções, foram consideradas pertencentes a um mesmo estágio tectônico e de preenchimento sedimentar. Visou traçar um avaliação histórica e comparativa acerca das Bacias da Paraíba e de Pernambuco, até recentemente consideradas uma única bacia, através de referências bibliográficas significativas para um melhor entendimento.</p>
        <div class="text-center">
                <a href={evolucao}><img src={evolucao} alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figura 2 - Evolução estratigráfica da Bacia da Paraíba entre o Coniaciano e o Maastrichtiano. Fonte: Souza (2006, p. 323).</figurecaption>
        </div>
		<hr />
		<span>
			<sup>1</sup>No meio científico, este lineamento/zona de cisalhamento aparece com o nome de Patos ou Paraíba. Por uma questão geográfica, optaremos, neste trabalho, pelo nome ‘Paraíba’, visto que corresponde à porção mais oriental desta feição, já no Estado da Paraíba, uma vez que Patos corresponde a um município do ‘Alto Sertão’, distante 400 Km do litoral. <br />
			<sup>2</sup>Sobre este agrupamento das duas bacias, propomos a leitura de Asmus e Carvalho (1978), Rand e Mabesoone (1982), Mabesoone e Alheiros (1988, 1993), Feijó (1994) e Córdoba et al. (2007). <br />
			<sup>3</sup>Entre eles, SCLATER et al. (1977) e SMITH e BRIDEN (1977), corroborando com a proposta de Beurlen (1962). <br />
			<sup>4</sup>Segundo Matos (1999), esta ruptura teria ocorrido bem antes, provavelmente no Albiano (113-110 Ma). <br />
			<sup>5</sup>Segundo Guerra (1987), corresponde a um afundamento crustal que conduz a formação e desenvolvimento de bacias geológicas onde se acumulam a sedimentação e/ou vulcanismo correspondente às fases de desenvolvimento de um rift.
		</span>
        </>
    )
}