export function Tectonica(){
    return(
        <>
        <p class="paragraphy">Mesmo localizado em uma margem passiva, o litoral do nordeste tem sofrido inúmeros eventos tectônicos, em diferentes tempos geológicos, eventos estes que afetam diretamente o pacote sedimentar estratigraficamente acima do embasamento. O objetivo deste subcapítulo é traçar um referencial teórico sobre a compartimentação tectônica desta porção litorânea do nordeste, em especial da faixa sedimentar entre Recife e Natal, e seu substrato, bem como analisar as consequências destes eventos para as bacias sobrepostas, cujo somatório de fatores é responsável pela morfologia atual. Esta análise permite facilitar a seleção dos Locais de Interesse de caráter tectônico, inventariados e quantificados, para a inserção, ou não, no mapa geoturístico da área.</p>
        <p class="paragraphy"> Considerando-se o caráter frágil do substrato rochoso que embasa os sedimentos da Bacia da Paraíba, caracterizado por um conjunto de falhas normais, o ‘<b>saliente oriental</b>’, nas adjacências da área de estudo e em parte dela, é representado por um sistema de grabens-horsts que Brito Neves et al. (2004) definiram como ‘<b>Sistema Tafrogênico Terciário</b>’, que é responsável pela trama estrutural da planície costeira. Pertencem a este sistema: Graben de Cariatá, Horst Boqueirão e sistema de grabens do Rio Mamanguape. Posteriormente, através de novos dados geológicos de superfície e subsuperfície e de dados geofísicos, Brito Neves et al. (2009) alargaram esta compartimentação, acrescentando o Graben do Rio Mamuaba, Baixo Rio Paraíba e Grande João Pessoa; e o Horst Tabuleiro das Lagoas, de Alto També-São Miguel de Taipu-Riacho Curimataú e Ciaisa. Destes, pertencem à área de estudo o Graben Cariatá, Graben Baixo Rio Paraíba, do Rio Mamuaba e Grande João Pessoa e o Horst Tabuleiro das Lagoas, unidades analisadas a seguir.</p>
        <p class="paragraphy">Este sistema tafrogênico, na Bacia da Paraíba, está relacionado com o colapso gravitacional da margem continental pós-rift (JARDIM DE SÁ et al., 2004), por meio de falhas planares normais de pouco rejeito, ocorrido após o Turoniano de maneira mais intensa (BARBOSA, 2007). O soerguimento do terreno facilita a exumação da sedimentação Plio-pleistocênica da <b>Formação Barreiras</b>, que representa a cobertura plataformal da Bacia da Paraíba, devidamente analisada a posteriori, enquanto o rebaixamento propicia a deposição de sedimentação quaternária, que inclui sedimentos aluviais, dunas, entre outros (LIMA et al., 1990). As falésias, de uma beleza cênica ímpar, correspondem à porção escarpada do horst, na linha de costa, podendo possuir mais de 40 m de altura.</p>
        <p class="paragraphy">O <b>Graben de Cariatá</b> tem sua máxima representatividade a leste do município paraibano de Itabaiana. Em direção a João Pessoa, os sedimentos Plio-pleistocênicos da <b>Formação Barreiras</b>, bem como os sedimentos quaternários, se espessam, mostrando o aspecto em rampa que caracteriza, mesmo escalonado, este sistema tafrogênico.</p>
        <p class="paragraphy">O <b>Graben do Rio Mamuaba</b> possui direção NNE-SSW, ao norte do município de Pedras de Fogo, abrange o curso inferior do rio homônimo e apresenta as maiores espessuras da sub-bacia Alhandra, assim como as mais elevadas altitudes, com 212 m, formando uma estutura dômica que serve como um divisor de águas para os tributários dos rios Gramame e Mamuaba.</p>
        <p class="paragraphy">O <b>Graben do Baixo Rio Paraíba</b> limita-se com o Horst Tabuleiro das Lagoas, ao norte, por um falhamento normal de direção W-SW/E-NE, que passa pelo município de Santa Rita, se prolongando até a praia de Tambaú, em João Pessoa. Atinge cerca de 50 m de profundidade, sendo preenchido pelos sedimentos terciários da <b>Formação Barreiras</b> e aluviais quaternários.</p>
        <p class="paragraphy">O <b>Graben da Grande João Pessoa</b> situa-se a leste do Horst Tabuleiro das Lagoas, possuindo um caráter escalonado para leste, através de um sistema de falhas que atinge os municípios de Bayeux e João Pessoa. Neste graben, espessam-se os sedimentos sobrepostos da <b>Formação Beberibe</b>, <b>Formação Gramame</b> e <b>Formação Barreiras</b>, em até 300 m.</p>
        <p class="paragraphy">O <b>Horst do Tabuleiro das Lagoas</b> apresenta leve basculamento para leste. Os sedimentos que o capeiam atingem cerca de 40 m de espessura, uma das menores nesta porção do ‘saliente’. Faz limite, a sul, com o Graben Mamuaba; a leste, com o sistema de grabens da Grande João Pessoa; a norte, com o Graben do Baixo Rio Paraíba. Três Locais de Interesse (LIG/CH 10, 11 e 12) estão inseridos neste horst, que possui papel fundamental na sua existência. O perfil do Graben da Grande João Pessoa e do Horst do Tabuleiro das Lagoas pode ser visualizado na figura 1.</p>
        <div class="text-center">
            <figure class="figure">
                <a href="media/tectonica1.jpg"><img src="media/tectonica1.jpg" alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figura 1 - Perfil ESE-WSW mostrando o comportamento do embasamento, formando o Graben da Grande João Pessoa, a leste e o Horst Tabuleiro das Lagoas, a oeste, e seus sedimentos sobrepostos, elaborado a partir de dados de dezenas de poços tubulares. Legenda: UPEN-Unidade Pedoestratigráfica Engenho Novo. Fonte: modificado de BRITO NEVES et al. (2009).</figurecaption>
            </figure>
        </div>
        <p class="paragraphy">Um perfil elaborado com base em testemunhos de perfurações foi proposto, partindo-se do horst de Alto També - São Miguel de Taipu - Riacho Curimataú, porção ocidental da ‘Saliente’ e fora da área da tese, em direção ao Graben de João Pessoa, na área do projeto, pode ser visualizado na figura 2.</p>
        <div class="text-center">
            <figure class="figure">
                <a href="media/tectonica2.png"><img src="media/tectonica2.png" alt="" class="img-fluid" /></a><br />
                <figurecaption class="figure-caption">Figura 2 - Perfil SSW- NNE mostrando o comportamento do embasamento, formando o Graben da Grande João Pessoa, a NNE e o Horst do Alto També - São Miguel de Taipu - Riacho Curimataú, a SSW, e seus sedimentos sobrepostos. Fonte: modificado de ROSSETTI et al. (2012).</figurecaption>
            </figure>
        </div>
        <p class="paragraphy">Em nenhum local do litoral paraibano aflora o escudo cristalino. A porção mais proximal do embasamento se dá nas proximidades do município de Conde, a cerca de 15 Km do litoral. Através da análise de centenas de sondagens ao longo da costa nordestina, ao norte de Recife até às proximidades de Natal, Barbosa (2007) elaborou um mapa de contorno estrutural, caracterizando o comportamento do embasamento ao longo da área supracitada, com resultados das feições regionais deste substrato rochoso.</p>
        <p class="paragraphy">Com isto, este sistema de grabens apresenta profundidade variável ao longo da faixa sedimentar supramencionada. Na Bacia de Pernambuco, os grabens são muito mais profundos que na Bacia da Paraíba e Plataforma de Natal, chegando a oito vezes a profundidade (em média 150-200 m até 3000 m, respectivamente). Assim, a profundidade do embasamento varia ao longo da faixa sedimentar entre Recife e Natal, assim como o ângulo da rampa que formam as bacias. Barbosa e Lima Filho (2005, 2006) e Barbosa (2007) elaboraram um mapa de contorno estrutural da faixa entre Recife e Natal, onde toda a área comporta-se como um rampa suave, com gradientes variando entre 1º e 3º<sup>1</sup>. As inclinações da rampa na Bacia da Paraíba, entretanto, apresentam-se maiores e a rampa é mais larga que suas vizinhas a norte e sul, respectivamente, Plataforma de Natal e a Bacia de Pernambuco. A sub-bacia Olinda é a mais larga das sub-bacias da Bacia da Paraíba, tendo como limite norte o Alto de Goiana. A Bacia de Pernambuco, localizada ao sul, possui, nas proximidades da Zona de Cisalhamento Pernambuco, uma zona costeira tão estreita que o embasamento praticamente aflora em contato com o mar.</p>
        <p class="paragraphy">Pode-se concluir, assim, que a paisagem costeira atual é resultado da interação de vários fatores, a citar a neotectônica, gerando falhamentos, com soerguimento e subsidência de blocos; regressões e transgressões marinhas; e intemperismo/erosão, com posterior deposição sedimentar, resultando em um conjunto de formas de relevos, associados à geologia, com um imenso potencial geoturístico, de acordo com a avaliação e quantificação, posteriormente realizada, de Locais de Interesse na área desta tese. </p>
        <hr />
        <span>
            <sup>1</sup>A maioria dos autores denomina este modelo de rampa como homoclinal, suavemente inclinada para leste. Barbosa e Lima Filho (2006) e Barbosa (2007) a consideram uma rampa distalmente inclinada com talude.
        </span>

        </>
    )
}