import unidade1 from './media/unidade1.png'


export function Unidades(){
    return(
        <>
            <p class="paragraphy">Considerando a área da tese, o <b>Grupo Paraíba</b> está representado pela sequência basal clástica da <b>Formação Beberibe</b> e pela sequência carbonática das <b>Formação Gramame</b> e <b>Formação Maria Farinha</b>, não aflorando a sequência clástica da <b>Formação Itamaracá</b>. A <b>Formação Barreiras</b>, que recobre discordantemente os sedimentos do <b>Grupo Paraíba</b> e o embasamento cristalino, representa uma cobertura plataformal, sobreposta pelos sedimentos inconsolidados quaternários, de depósitos de aluviões, sedimentos de terraços pleistocênicos e holocênicos, sedimentos praiais, recifes, depósitos fluviolagunares e de manguezais, entre outros, que ocorrem na unidade geomorfológica da planície costeira-fluvial. Este subcapítulo é resultado do mapeamento geológico realizado na área do projeto, no qual foi identificado o valor patrimonial da geodiversidade, caracterizando os Locais de Interesse Geoturístico de cunho geológico (petrográficos, paleontológicos, mineralógicos, estratigráficos e tectônicos). Convém salientar que pelo menos um Local de Interesse Geoturístico foi selecionado em cada unidade litoestratigráfica.</p>
                <p class="paragraphy">A Figura 1 esquematiza a coluna estratigráfica da faixa sedimentar pertencente à Sub-bacia Alhandra, da Bacia da Paraíba, onde, com exceção da <b>Formação Itamaracá</b> e o horizondte fosfático, as demais unidades litoestratigráficas afloram na área do projeto e serão apresentadas a seguir.</p>
                <div class="text-center">
                    <figure class="figure">
                        <a href={unidade1}><img src={unidade1} alt="" class="img-fluid" /></a><br />
                        <figurecaption class="figure-caption">Figura 1 - Coluna estratigráfica esquemática da faixa sedimentar pertencente à sub-bacia Alhandra, da Bacia da Paraíba. Fonte: modificado de Barbosa (2007, p. 29).</figurecaption>
                    </figure>
                </div>
                <h3>Formação Beberibe</h3>
                <p class="paragraphy">A <b>Formação Beberibe</b> representa o início do aporte sedimentar na bacia da Paraíba, no Santoniano - Campaniano Inferior (83,6 - 72,15 Ma). A denominação foi proposta por Kegel (1953, 1955), como Membro Beberibe e Beurlen (1967a) elevou o Membro Beberibe, pertencente à <b>Formação Itamaracá</b>, ao status de Formação, enquanto a <b>Formação Itamaracá</b> foi anexada à <b>Formação Gramame</b>, que se tornou, automaticamente, mais espessa.</p>
                <p class="paragraphy">A <b>Formação Beberibe</b> possui uma espessura máxima de 280 m, repousando discordantemente sobre o embasamento cristalino, por meio de uma discordância erosiva. Compreende uma espessa cunha de arenitos quartzosos, de origem continental, mal selecionados, finos a grossos, friáveis e porosos, de cor cinzenta a creme, pobremente fossilíferos, com estratificação plano – paralela. Contém alguns componentes mais finos, como siltitos e arenitos finos a muito finos, representativos de planície fluvial-lagunar, variando de arenitos conglomeráticos monomíticos a oligomíticos com clastos de 15 cm, cujo ambiente de sedimentação arenítica é flúvio-lacustre, especificamente de canal fluvial do tipo ‘<i>braided</i>’ de alta energia. Lateralmente, podem interdigitar com um arenito mais compacto, cimentado por carbonatos, representando a antiga <b>Formação Itamaracá</b>, típico de um domínio de fácies fluviolagunar a fluviodeltaica. É importante salientar que esta fácies porosa da formação é responsável pelo alojamento de um substancial reservatório de água subterrânea, o <b>Aquífero Beberibe</b>, localizado a profundidades superiores a 100 m, portanto de difícil contaminação, e que abastece a Região Metropolitana de Recife e João Pessoa, neste caso o Sistema Mamuaba-Gramame, da Companhia de Água e Esgotos da Paraíba (CAGEPA).</p>
                <p class="paragraphy">Beurlen (1967a, b) define a idade Coniaciana-Santoniana (89,8 – 83,6 Ma) para esta deposição. Segundo Barbosa et al. (2003), esta idade foi inferida através do conteúdo fossilífero de ambiente marinho que mais tarde foi atribuído à <b>Formação Itamaracá</b>, o que pressupõe que a <b>Formação Beberibe</b> seja mais antiga que o Santoniano. A deposição da <b>Formação Beberibe</b> se iniciou nas sub-bacias Alhandra e Miriri (porção centro-norte) antes da sub-bacia Olinda (porção sul), que se achava já soerguida, no Turoniano (93,9 – 89,8 Ma), quando se iniciou seu preenchimento, provavelmente no Campaniano Médio-Superior. Esta formação é mais expressiva na sub-bacia Olinda do que nas sub-bacias do centro-norte, não ocorrendo ao norte do Lineamento Paraíba. </p>
                <p class="paragraphy">Os principais afloramentos desta unidade se localizam essencialmente ao longo dos vales fluviais, diretamente sobre a rampa estrutural de baixo ângulo do embasamento, e foram expostos pela ação da água que erodiu as camadas sobrepostas, exumando esta formação. Localizam-se no curso intermediário do rio Mumbaba, como é o caso do Local de Interesse selecionado. Convém salientar que para os geólogos de campo há uma grande dificuldade de diferenciar os arenitos desta formação daqueles da <b>Formação Barreiras</b>, pela sua semelhança textural, ainda mais se o afloramento estiver intensamente intemperisado.</p>
                <h3>Formação Gramame</h3>
                <p class="paragraphy">Corresponde à primeira unidade carbonática de domínio marinho, repousando concordantemente sobre a sequência clástica da <b>Formação Itamaracá</b>, por meio de uma inconformidade (MANSO, 1982). Possui cerca de 70 m de espessura (ALMEIDA, 2000b), tendo sido primeiramente referida na literatura por Oliveira (1940), e respeitando aos calcários margosos aflorantes ao longo do Rio Gramame, extrapolando, posteriormente, sua área de extensão para Pernambuco. </p>
                <p class="paragraphy">Os calcários e margas da <b>Formação Gramame</b> se intercalam com uma estratificação plano-paralela de grande continuidade lateral, típica de uma plataforma carbonática extensa de baixo gradiente (BARBOSA, 2007). A partir do estudo do conteúdo fossilífero, Maury (1930), ratificado por Muniz (1993) e Córdoba et al. (2007), propôs uma idade do Campaniano Superior (72 Ma), sendo revisto por Beurlen (1967a) para o Maastrichtiano (72,1 – 66 Ma), no que foi corroborado por Tinoco (1967, 1971).</p>
                <p class="paragraphy">A área de afloramento-tipo se localiza na margem direita do rio homônimo, que limita João Pessoa com o município de Conde, aparecendo também na Ilha do Bispo, na periferia de João Pessoa, onde se situa o Local de Interesse e em outros vales fluviais no litoral sul, incluídos na área deste projeto: margem esquerda do Rio Abiaí, margem direita do Rio Camocim, entre outros. A ausência desta formação a oeste da BR-101 pode refletir a não deposição desta sequência na área ou a erosão após a exposição sub-aérea, gerada pela regressão do nível do mar ao final do Maastrichtiano (FURRIER, 2007). A deposição é mais larga nas sub-bacias Alhandra e Miriri em relação a Olinda (BARBOSA, 2007).</p>
                <h3>Formação Maria Farinha</h3>
                <p class="paragraphy">A <b>Formação Maria Farinha</b> corresponde ao último pacote de sedimentação da Bacia da Paraíba, representando o topo do <b>Grupo Paraíba</b>, cuja base é referente à Formação Beberibe. Foi datada como Paleocênica (66 – 56 Ma), sendo separada da <b>Formação Gramame</b> por uma discordância, formada com uma delgada camada de calcário detrítico, que marca a passagem Cretáceo-Terciário (Maastrichtiano/Daniano – 66 Ma, sensu ALBERTÃO, 1993; ALBERTÃO e MARTINS JUNIOR, 1996; BARBOSA, 2007; CÓRDOBA et al., 2007), com um suave mergulho de 5º para leste e ondulação no sentido norte-sul (OLIVEIRA e ANDRADE RAMOS, 1956).</p>
                <p class="paragraphy">O autor pioneiro na denominação desta formação foi Oliveira (1940), para caracterizar os calcários fossilíferos aflorantes nas redondezas de Recife. Beurlen (1967a) dividiu a Formação em <b>Maria Farinha Inferior e Superior</b>. A porção inferior refere-se às rochas aflorantes na sub-bacia de Olinda, representadas por uma sequência de calcários argilosos e margas, com idade Daniana (66 – 61,6 Ma), representativa de uma plataforma continental interna, influenciada por estuários, enquanto a superior está associada às sub-bacias Miriri e Alhandra, representadas por calcários dolomíticos, localmente biodetríticos, associados a um ambiente marinho extremamente raso, lagunar e/ou recifal (MUNIZ, 1993; ALMEIDA, 2000b; BARBOSA et al., 2006), possivelmente representativo de uma parada do nível do mar durante o evento regressivo, no Eoceno (56 – 33,9 Ma), quando o mar estava relativamente raso e quente, propiciando a deposição das franjas calcárias que atualmente afloram no litoral sul paraibano (BARBOSA et al., 2006; BARBOSA, 2007).  Barbosa et al. (2006) e Barbosa (2007) corroboram a existência de uma diferenciação paleofaunística, litofaciológica e de ambiente de sedimentação entre a porção inferior e superior da <b>Formação Maria Farinha</b>. A passagem da <b>Formação Gramame</b> para a <b>Formação Maria Farinha</b> Inferior pode ser evidenciado na Pedreira Poty e em Nassau, na sub-bacia Olinda, fora da área da tese, onde 15 m de calcários e margas gradativamente vão se tornando mais argilosos e mais siliciclásticos no topo, evidenciando o efeito gradual da regressão marinha. Nesta sub-bacia, a <b>Formação Maria Farinha</b> mostra-se mais preservada, mesmo que a transgressão marinha tenha sido tardia, diferentemente das sub-bacias ao norte, onde a cobertura plataformal da <b>Formação Barreiras</b> se depositou sobre a <b>Formação Gramame</b>. </p>
                <p class="paragraphy">Nas sub-bacias setentrionais da Bacia da Paraíba, a <b>Formação Maria Farinha</b> aflora como franjas na costa, em praias como Coqueirinho, Jacumã, Tabatinga e Tambaba, no litoral sul da área de estudo (LEAL E SÁ, 1998; ALMEIDA, 2000b; BARBOSA, 2004; SOUZA, 2006), influenciando a configuração da atual linha de costa, já que forma praias em ‘zeta’. Pode ocorrer como bancos rochosos submersos, onde se desenvolve fartos organismos coralinos (ALMEIDA, 1989) ou mais próximos da costa ou na forma de pequenas ilhas, cuja deposição sedimentar, em áreas de menor energia, acaba por formar tômbolos.</p>
                <p class="paragraphy">Com uma espessura de cerca de 35 m, seu conteúdo faunístico é representado por gastrópodes, moluscos, corais, lamelibrânquios, restos de tartarugas e equinodermas (BEURLEN, 1959), típicos de um ambiente marinho raso, próximo da costa a recifal. Este conteúdo propiciou a proposição de idade da deposição como sendo paleocênica-eocênica inferior (MABESOONE, 1995; ALMEIDA, 2000b). Do ponto de vista das feições estruturais, apresenta estratificação cruzada hummocky, granodecrescência ascendente e estratificação ondular, o que possibilita caracterizar sua deposição como sendo associada a eventos de tempestade em uma plataforma em rampa carbonática (SOUZA, 2006).</p>
                <h3>Formação Barreiras</h3>
                <p class="paragraphy">O primeiro autor a citar o nome ‘Barreiras’ na literatura foi Branner (1902), referindo-se a rochas aflorantes na costa nordestina, termo repetido por Moraes (1928), com a denominação Formação das Barreiras, sem conotação científica ou estratigráfica formal.</p>
                <p class="paragraphy">A estratigrafia da <b>Formação Barreiras</b> é alvo de polêmica até hoje. Oliveira e Leonardos (1943) posicionaram a sequência a nível de Série Barreiras, referindo-se aos tabuleiros salientes que se estendem pelo litoral paraibano. A denominação <b>Formação Barreiras</b> foi proposta por Oliveira e Andrade Ramos (1956) e Kegel (1957)<sup>1</sup>  para os sedimentos argilo-arenosos que afloram no litoral nordestino, afossilíferos e de cores vivas, que inclusive teriam chamado a atenção de Pero Vaz em sua primeira carta de descrição do território brasileiro. Foi elevada a nível de Grupo Barreiras por Bigarella e Andrade (1964), e dividida em Formação Guararapes e Riacho Morno, separadas por uma descontinuidade erosiva. Esta subdivisão foi questionada por Mabesoone et al. (1972), estudando afloramentos do Barreiras ao longo da costa de Pernambuco ao Rio Grande do Norte. Para os autores, a Formação Riacho Morno faria parte de um evento intempérico inserido na Formação Guararapes, e a razão pela qual subdividiram o grupo em mais duas formações: Serra dos Martins e Macaíba.</p>
                <p class="paragraphy">A definição de Formação será retomada, posteriormente, por Alheiros et al. (1988), cuja grande extensão lateral será considerada como uma única unidade litoestratigráfica, considerando suas características litológicas e desenvolvimento sedimentológico, por meio de estudos detalhados utilizando técnicas estratigráficas mais modernas. Optamos pela denominação <b>Formação Barreiras</b> em detrimento de <b>Grupo Barreiras</b> pois ainda há sérios problemas de delimitação estratigráfica e definição das formações que fariam parte deste grupo, pela dificuldade de distinção entre elas, motivo pelo qual, em encontros científicos para discutir várias informações acerca dos sedimentos Barreiras, a exemplo dos simpósios anexos ao Congresso da Associação Brasileiras de Estudos do Quaternário, a partir de 2005, a grande maioria dos estudiosos usa a denominação <b>Formação Barreiras</b>.</p>
                <p class="paragraphy">A <b>Formação Barreiras</b>, assim, é uma das mais vultosas sequências sedimentares do Brasil, aflorando em aproximadamente 4 mil Km de costa, da foz do Rio Amazonas (latitude 4º N) ao litoral fluminense (latitude 22º S; MABESOONE et al., 1972). Na Paraíba, sua geomorfologia é dominada pelos tabuleiros costeiros que terminam na costa na forma de grandiosas e belíssimas falésias, como a de Cabo Branco, com grande apreço turístico, apesar de ser no Rio Grande do Norte que elas possuem as maiores alturas (BARBOSA, 2007). Mesmo com esta grande extensão, a presença de uma discordância tortoniana (11,6-7,2 Ma) em toda a sequência possibilitou esta correlação inter-regional<sup>2</sup> . Esta discordância é marcada pela presença de um paleossolo laterítico ferruginoso, cujas 19 amostras de ghoetitas, retiradas do sedimento Barreiras na Bacia da Paraíba, foram datadas pelo método (U/ Th)/ He, resultando em picos de concentração de idades entre 1-2 Ma (ROSSETTI et al., 2012).</p>
                <p class="paragraphy">Ainda assim, sua idade mantém-se polêmica, principalmente pelo fraco conteúdo fossilífero. Suguio et al. (1986) e Lima et al. (1990), através de datação paleomagnética e do estudo de material palinológico, respectivamente, propuseram idade pliocênica, especificamente 4,5 a 5,0 Ma para a base do depósito e 3,0 a 3,4 Ma para o topo. Alheiros e Lima Filho (1991) propuseram idade plio-pleistocênica. Arai (2006), Arai et al. (1988, 1994) e Leite (2006), com base em estudos palinológicos, sugeriram o Mioceno inferior a médio, enquanto Bezerra et al. (2001a), com base em datação paleomagnética e micropolínica sugeriu idades entre o Mioceno e Plioceno. Lima et al. (2007) e Lima (2008) realizaram datações em sedimentos Barreiras localizados entre o litoral cearense e potiguar, por meio do método 40Ar/39Ar e (U/ Th)/ He, cuja idade da deposição resultou entre 18 e 22 Ma, ou seja, Mioceno Inferior, e o intemperismo prolongou-se até cerca de 7 Ma. Estes dados, acrescentados aos propostos por Rossetti et al. (2012), permitem afirmar que após a deposição da <b>Formação Barreiras</b>, no Mioceno Inferior, seus sedimentos foram expostos a um longo período de erosão subaérea que pode ter-se prolongado até ao Quaternário, quando se iniciou a deposição da sedimentação pós-Barreiras, no caso, as unidades denominadas PB-1/PB-2.</p>
                <p class="paragraphy">Outra polêmica decorre da origem da sedimentação Barreiras. Os primeiros pesquisadores a descreveram como tendo uma origem continental (OLIVEIRA e LEONARDOS, 1940). Este pensamento da origem continental retornou posteriormente, sendo descrito um ambiente de sedimentação que variaria do fluvial do tipo ‘<i>braided</i>’ ao de leques aluviais, passando por depósitos fluviolagunares, sempre em uma fase mais árida do que a atual, durante o Cenozóico, que se intercalou a períodos úmidos que foram responsáveis pela oxidação das rochas, gerando a coloração viva anteriormente citada. A fácies fluvial ‘<i>braided</i>’ está representada por sedimentos de granulação grosseira, como cascalhos e areias grossas, com coloração creme amarelada a avermelhada, interdigitados com argilas sílticas, típica de ambientes de planície aluvial. Apresentam estratificação cruzada acanalada de médio a grande porte, com sedimentos medianamente selecionados e com baixo grau de arredondamento. Na fácies de leques, as rochas são conglomeráticas polimíticas, com coloração creme avermelhado, intercalados com material pelítico e seixos de quartzo e blocos argilosos retrabalhados, geralmente em contato com as rochas do embasamento (ALHEIROS et al., 1988; ALHEIROS e LIMA FILHO, 1991; MABESOONE e ALHEIROS, 1993; LIMA FILHO e MELO, 2007).</p>
                <p class="paragraphy">Barbosa (2007), por meio do mapa de isópacas, determinou uma tabularidade para a <b>Formação Barreiras</b> na porção proximal da bacia, com domínio de leques aluviais. A espessura é pequena na sub-bacia Alhandra, entre Recife e João Pessoa, quando afloram os calcários da <b>Formação Gramame</b> e <b>Formação Maria Farinha</b>, aumentando no contato com a sub-bacia Miriri, nas redondezas de João Pessoa, voltando a adelgaçar no limite norte, no Alto de Mamanguape. A partir daí em direção a Natal, a formação possui as maiores espessuras desta área. As maiores altitudes, na Bacia da Paraíba, se localizam na porção mais afastada da linha de costa, enquanto na Plataforma Natal, estão associadas às falésias, ativas ou não.</p>
                <p class="paragraphy">Posteriormente, a descoberta de fauna marinha modificou as propostas de ambientação desta sedimentação (ARAI et al., 1988; ROSSETTI, et al., 1990; ARAI, 1997). Segundo Arai (2005), eventos transgressivos marinhos de idade Miocênica (Aquitaniano-Serravaliano) e Pliocênica (Zancleano), separados pela descontinuidade tortoniana, foram responsáveis pela deposição de um espesso pacote sedimentar, denominado <b>Barreiras Inferior e Superior</b>, respectivamente. Posteriormente, em um ambiente de trato de mar baixo, estes sedimentos foram erodidos e retrabalhados, dando origem à atual configuração da costa onde estão expostos, e que possui uma beleza cênica extremamente favorável ao geoturismo.</p>

                <hr />
                <span>
                    <sup>1</sup>As camadas inferiores da Formação foram denominadas ‘Infra-barreiras’.<br />
                    <sup>2</sup>Esta discordância foi consequência de um evento erosivo de idade tortoniana, causada pela queda eustática do Neógeno, resultado da formação de uma calota glacial na Antártida e, segundo alguns autores, separa o Barreiras Inferior do Superior. Rossetti et al. (2011, 2012), entretanto, considera que esta descontinuidade, na forma de um paleosolo laterítico ferruginoso, represente o topo da Formação Barreiras, e os sedimentos sobrepostos a ele fazem parte de um novo contexto de ambiente sedimentar, agora pertencente ao Quaternário, denominados PB-1 e PB-2, que foram mapeados pela CPRM  como depósitos elúvio-coluvionares, sendo a Bacia do Rio Gramame o limitador de ambos. A autora, entretanto, sugere que estes depósitos, se estendem por uma área muito maior. 
                </span>
        </>
    )
}